<?php
require_once(getabspath("classes/cipherer.php"));



$tdatadashboard = array();
$tdatadashboard[".ShortName"] = "dashboard";

$tdatadashboard[".pagesByType"] = my_json_decode( "{\"dashboard\":[\"dashboard\",\"all_in_one_training\"],\"search\":[\"search\"]}" );
$tdatadashboard[".originalPagesByType"] = $tdatadashboard[".pagesByType"];
$tdatadashboard[".pages"] = types2pages( my_json_decode( "{\"dashboard\":[\"dashboard\",\"all_in_one_training\"],\"search\":[\"search\"]}" ) );
$tdatadashboard[".originalPages"] = $tdatadashboard[".pages"];
$tdatadashboard[".defaultPages"] = my_json_decode( "{\"dashboard\":\"dashboard\",\"search\":\"search\"}" );
$tdatadashboard[".originalDefaultPages"] = $tdatadashboard[".defaultPages"];


//	field labels
$fieldLabelsdashboard = array();
$pageTitlesdashboard = array();

if(mlang_getcurrentlang()=="English")
{
	$fieldLabelsdashboard["English"] = array();
	$fieldLabelsdashboard["English"]["aio_training_tracking_participant_id"] = "P.ID";
	$fieldLabelsdashboard["English"]["aio_training_tracking_title"] = "Title";
	$fieldLabelsdashboard["English"]["aio_training_tracking_first_name"] = "First Name";
	$fieldLabelsdashboard["English"]["aio_training_tracking_middle_name"] = "Middle Name";
	$fieldLabelsdashboard["English"]["aio_training_tracking_last_name"] = "Last Name";
	$fieldLabelsdashboard["English"]["aio_training_tracking_gender"] = "Sex";
	$fieldLabelsdashboard["English"]["aio_training_tracking_participant_role"] = "Role";
	$fieldLabelsdashboard["English"]["aio_training_tracking_country"] = "Country";
	$fieldLabelsdashboard["English"]["aio_training_tracking_facility"] = "Facility";
	$fieldLabelsdashboard["English"]["aio_training_tracking_phone"] = "Phone";
	$fieldLabelsdashboard["English"]["aio_training_tracking_email"] = "Email";
	$fieldLabelsdashboard["English"]["aio_training_tracking_training_id"] = "Session#";
	$fieldLabelsdashboard["English"]["aio_training_tracking_training_name"] = "Training Name";
	$fieldLabelsdashboard["English"]["aio_training_tracking_program"] = "Program";
	$fieldLabelsdashboard["English"]["aio_training_tracking_partners"] = "Partners";
	$fieldLabelsdashboard["English"]["aio_training_tracking_training_type"] = "Training Type";
	$fieldLabelsdashboard["English"]["aio_training_tracking_training_approach"] = "Training Approach";
	$fieldLabelsdashboard["English"]["aio_training_tracking_training_language"] = "Training Language";
	$fieldLabelsdashboard["English"]["aio_training_tracking_training_lead"] = "Training Lead";
	$fieldLabelsdashboard["English"]["aio_training_tracking_quarter"] = "Quarter";
	$fieldLabelsdashboard["English"]["aio_training_tracking_start_date"] = "Start Date";
	$fieldLabelsdashboard["English"]["aio_training_tracking_end_date"] = "End Date";
	$fieldLabelsdashboard["English"]["aio_training_tracking_total_days"] = "Total Days";
	$fieldLabelsdashboard["English"]["aio_training_tracking_days_recorded"] = "Days Recorded";
	$fieldLabelsdashboard["English"]["aio_training_tracking_days_attended"] = "Days Attended";
	$fieldLabelsdashboard["English"]["aio_training_tracking_attendance_percentage"] = "Attendance %";
	$fieldLabelsdashboard["English"]["aio_training_tracking_attendance_status"] = "Attendance Status";
	$fieldLabelsdashboard["English"]["aio_training_tracking_pre_test_score"] = "Pre Test Score";
	$fieldLabelsdashboard["English"]["aio_training_tracking_post_test_score"] = "Post Test Score";
	$fieldLabelsdashboard["English"]["aio_training_tracking_ceu_points"] = "Ceu Points";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_participant_id"] = "Participant Id";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_title"] = "Title";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_first_name"] = "First Name";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_middle_name"] = "Middle Name";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_last_name"] = "Last Name";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_gender"] = "Gender";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_participant_role"] = "Participant Role";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_country"] = "Country";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_facility"] = "Facility";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_phone"] = "Phone";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_email"] = "Email";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_training_id"] = "Training Id";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_training_name"] = "Training Name";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_program"] = "Program";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_partners"] = "Partners";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_training_type"] = "Training Type";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_training_approach"] = "Training Approach";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_training_language"] = "Training Language";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_training_lead"] = "Training Lead";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_quarter"] = "Quarter";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_start_date"] = "Start Date";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_end_date"] = "End Date";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_total_days"] = "Total Days";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_days_recorded"] = "Days Recorded";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_days_attended"] = "Days Attended";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_attendance_percentage"] = "Attendance Percentage";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_attendance_status"] = "Attendance Status";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_pre_test_score"] = "Pre Test Score";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_post_test_score"] = "Post Test Score";
	$fieldLabelsdashboard["English"]["aio_training_tracking_Chart_ceu_points"] = "Ceu Points";
}

/*
//	search fields
$tdatadashboard[".searchFields"] = array();
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"gender" );
$tdatadashboard[".searchFields"]["aio_training_tracking_gender"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"participant_role" );
$tdatadashboard[".searchFields"]["aio_training_tracking_participant_role"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"country" );
$tdatadashboard[".searchFields"]["aio_training_tracking_country"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"facility" );
$tdatadashboard[".searchFields"]["aio_training_tracking_facility"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"training_id" );
$tdatadashboard[".searchFields"]["aio_training_tracking_training_id"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"training_name" );
$tdatadashboard[".searchFields"]["aio_training_tracking_training_name"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"program" );
$tdatadashboard[".searchFields"]["aio_training_tracking_program"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"partners" );
$tdatadashboard[".searchFields"]["aio_training_tracking_partners"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"training_type" );
$tdatadashboard[".searchFields"]["aio_training_tracking_training_type"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"training_approach" );
$tdatadashboard[".searchFields"]["aio_training_tracking_training_approach"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"training_language" );
$tdatadashboard[".searchFields"]["aio_training_tracking_training_language"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"training_lead" );
$tdatadashboard[".searchFields"]["aio_training_tracking_training_lead"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"quarter" );
$tdatadashboard[".searchFields"]["aio_training_tracking_quarter"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"attendance_status" );
$tdatadashboard[".searchFields"]["aio_training_tracking_attendance_status"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"gender" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_gender"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"participant_id" );
$tdatadashboard[".searchFields"]["aio_training_tracking_participant_id"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"title" );
$tdatadashboard[".searchFields"]["aio_training_tracking_title"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"first_name" );
$tdatadashboard[".searchFields"]["aio_training_tracking_first_name"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"middle_name" );
$tdatadashboard[".searchFields"]["aio_training_tracking_middle_name"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"last_name" );
$tdatadashboard[".searchFields"]["aio_training_tracking_last_name"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"phone" );
$tdatadashboard[".searchFields"]["aio_training_tracking_phone"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"email" );
$tdatadashboard[".searchFields"]["aio_training_tracking_email"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"start_date" );
$tdatadashboard[".searchFields"]["aio_training_tracking_start_date"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"end_date" );
$tdatadashboard[".searchFields"]["aio_training_tracking_end_date"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"total_days" );
$tdatadashboard[".searchFields"]["aio_training_tracking_total_days"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"days_recorded" );
$tdatadashboard[".searchFields"]["aio_training_tracking_days_recorded"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"days_attended" );
$tdatadashboard[".searchFields"]["aio_training_tracking_days_attended"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"attendance_percentage" );
$tdatadashboard[".searchFields"]["aio_training_tracking_attendance_percentage"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"pre_test_score" );
$tdatadashboard[".searchFields"]["aio_training_tracking_pre_test_score"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"post_test_score" );
$tdatadashboard[".searchFields"]["aio_training_tracking_post_test_score"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking", "field"=>"ceu_points" );
$tdatadashboard[".searchFields"]["aio_training_tracking_ceu_points"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"participant_id" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_participant_id"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"title" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_title"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"first_name" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_first_name"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"middle_name" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_middle_name"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"last_name" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_last_name"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"participant_role" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_participant_role"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"country" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_country"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"facility" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_facility"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"phone" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_phone"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"email" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_email"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"training_id" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_training_id"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"training_name" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_training_name"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"program" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_program"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"partners" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_partners"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"training_type" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_training_type"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"training_approach" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_training_approach"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"training_language" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_training_language"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"training_lead" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_training_lead"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"quarter" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_quarter"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"start_date" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_start_date"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"end_date" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_end_date"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"total_days" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_total_days"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"days_recorded" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_days_recorded"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"days_attended" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_days_attended"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"attendance_percentage" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_attendance_percentage"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"attendance_status" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_attendance_status"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"pre_test_score" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_pre_test_score"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"post_test_score" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_post_test_score"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"aio_training_tracking Chart", "field"=>"ceu_points" );
$tdatadashboard[".searchFields"]["aio_training_tracking_Chart_ceu_points"] = $dashField;

// all search fields
$tdatadashboard[".allSearchFields"] = array();
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_gender";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_participant_role";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_country";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_facility";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_training_id";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_training_name";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_program";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_partners";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_training_type";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_training_approach";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_training_language";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_training_lead";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_quarter";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_attendance_status";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_gender";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_participant_id";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_title";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_first_name";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_middle_name";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_last_name";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_phone";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_email";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_start_date";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_end_date";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_total_days";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_days_recorded";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_days_attended";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_attendance_percentage";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_pre_test_score";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_post_test_score";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_ceu_points";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_participant_id";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_title";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_first_name";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_middle_name";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_last_name";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_participant_role";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_country";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_facility";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_phone";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_email";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_training_id";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_training_name";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_program";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_partners";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_training_type";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_training_approach";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_training_language";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_training_lead";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_quarter";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_start_date";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_end_date";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_total_days";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_days_recorded";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_days_attended";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_attendance_percentage";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_attendance_status";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_pre_test_score";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_post_test_score";
$tdatadashboard[".allSearchFields"][] = "aio_training_tracking_Chart_ceu_points";

// good like search fields
$tdatadashboard[".googleLikeFields"] = array();
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_gender";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_participant_role";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_country";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_facility";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_training_id";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_training_name";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_program";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_partners";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_training_type";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_training_approach";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_training_language";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_training_lead";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_quarter";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_attendance_status";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_Chart_gender";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_participant_id";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_title";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_first_name";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_middle_name";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_last_name";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_phone";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_email";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_start_date";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_end_date";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_total_days";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_days_recorded";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_days_attended";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_attendance_percentage";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_pre_test_score";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_post_test_score";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_ceu_points";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_Chart_participant_role";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_Chart_country";
$tdatadashboard[".googleLikeFields"][] = "aio_training_tracking_Chart_training_name";
*/

/*
$tdatadashboard[".dashElements"] = array();

*/
$tdatadashboard[".shortTableName"] = "dashboard";
$tdatadashboard[".entityType"] = 4;




$tdatadashboard[".hasEvents"] = false;


$tdatadashboard[".tableType"] = "dashboard";



$tdatadashboard[".addPageEvents"] = false;

$tdatadashboard[".isUseAjaxSuggest"] = true;

$tables_data["Dashboard"]=&$tdatadashboard;
$field_labels["Dashboard"] = &$fieldLabelsdashboard;
$page_titles["Dashboard"] = &$pageTitlesdashboard;

?>