<?php
$securitySettings_var = array( 'providers' => array( array( 'type' => '%db',
'activationField' => 'active',
'active' => true,
'code' => '00',
'emailField' => 'email',
'extUserIdField' => 'ext_security_id',
'fullnameField' => 'fullname',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'password',
'resetDateField' => 'reset_date',
'resetTokenField' => 'reset_token',
'table' => array( 'connId' => 'lifebox_mesystem_at_localhost',
'table' => 'public.users' ),
'userGroupField' => 'username',
'usernameField' => 'username',
'userpicField' => 'userpic' ),
array( 'scope' => 'openid profile email ',
'nameClaim' => 'name',
'emailClaim' => 'email',
'logOut' => false,
'active' => true,
'clientId' => 'beaa6a03-9a79-4d3e-b927-88bf2dc9a0b7',
'clientSecret' => 'mwv8Q~kAE.04KcE5-Y29vR5K_6~VxrcPp2QDTcf5',
'code' => 'az',
'configUrl' => 'https://login.microsoftonline.com/012ecc7f-5a31-4035-9e04-0f01beef9799/.well-known/openid-configuration',
'label' => array( 'text' => 'AzureAD',
'type' => 0 ),
'name' => 'azure',
'type' => '%azure' ) ),
'sessionControl' => array( 'lifeTime' => 15,
'sessionName' => 'LifeboxSA7lVH6MEdvwh',
'JWTSecret' => 'KgDg763op72JzHiH0yQY',
'forceExpire' => true,
'keepAlive' => false,
'warnExpire' => true ),
'registration' => array( 'passwordValidation' => array( 'strong' => false,
'minimumLength' => 8,
'uniqueCharacters' => 4,
'digitsAndSymbols' => 2,
'upperAndLowerCase' => false ),
'remindMethod' => 1,
'hashAlgorithm' => 0,
'adminEmail' => 'admin@merqconsultancy.org',
'changePasswordPage' => true,
'changePwdPage' => true,
'hashPassword' => true,
'notifyAdmin' => true,
'notifyUser' => true,
'registerPage' => true,
'remindPage' => true,
'remindPasswordPage' => true,
'sendActivationLink' => true ),
'captchaSettings' => array( 'captchaType' => 1,
'siteKey' => '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI',
'secretKey' => '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe',
'passesCount' => 5 ),
'emailSettings' => array( 'fromEmail' => '',
'usePHPDefinedSMTP' => false,
'useBuiltInMailer' => false,
'SMTPServer' => '',
'SMTPPort' => 587,
'SMTPUser' => '',
'SMTPPassword' => '',
'securityProtocol' => 2 ),
'advancedSecurity' => array( 'allowGuestLogin' => false ),
'auditAndLocking' => array( 'loggingTable' => array( 'connId' => 'lifebox_mesystem_at_localhost',
'table' => 'public.lifeboxme__audit' ),
'lockingTable' => array( 'connId' => 'lifebox_mesystem_at_localhost',
'table' => 'public.lifeboxme__locking' ),
'tables' => array( 'Lifebox_DHIS2_OrgUnits' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'Lifebox_DHIS2_Settings' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'Lifebox_DHIS2_dataItems' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'admin_members' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'admin_rights' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'admin_users' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'aio_training_tracking' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.antibiotics' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.case_antibiotics' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.clean_cut_implementation_summary_view' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.clean_cut_implementations' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.countries' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.daily_attendance_view' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.device_distribution_log' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.device_distribution_summary_view' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.device_distributions' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.device_inventory_changes' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.devices' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.diagnoses' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.donors' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.facilities' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.follow_ups' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.languages' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.lbapt_all_activities_view' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.lbapt_annual_plan_tracker' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.lbapt_beginnings_fund' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.lbapt_communications' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.lbapt_cri' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.lbapt_dashboard_summary' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.lbapt_dashboard_summary_view' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.lbapt_development' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.lbapt_elma' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.lbapt_finance' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.lbapt_governance' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.lbapt_hr' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.lbapt_kpis_on_track' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.lbapt_kpis_tracking_view' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.lbapt_operations' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.lbapt_programs' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.lbapt_sample_workflow' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.lbapt_status' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.lbapt_strategic_areas' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.lbapt_unified_activities' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.lifebox_staff' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.lifeboxme__audit' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.lifeboxme__locking' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.lifeboxme_dhis2_analytics_data' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.lifeboxme_dhis2_analytics_settings' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.lifeboxme_dhis2_dataitems' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.lifeboxme_dhis2_orgunits' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.months' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.participant_attendance_detail' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.participant_attendance_summary' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.participant_role' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.partners' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.payment_methods' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.procedures' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.programs' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.quarters' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.regions' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.sex' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.smtp' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.surgical_case_summary_view' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.surgical_cases' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.trainers' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.training_approaches' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.training_attendance' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.training_courses' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.training_languages' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.training_leads' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.training_participants' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.training_participation' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.training_partners' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.training_sessions' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.training_summary_view' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.training_trainers' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.training_types' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.transaction_types' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.users' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.venues' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.ward_antibiotics' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.ward_rounds' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'public.years' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ) ),
'loggingMode' => 1,
'loggingFile' => 'audit.log',
'logSecurityActions' => true,
'lockAfterUnsuccessfulLogin' => true,
'enableLocking' => true ),
'twoFactorSettings' => array( 'available' => false,
'required' => false,
'enable' => true,
'remember' => true,
'types' => array(  ),
'twoFactorField' => '',
'emailField' => '',
'phoneField' => '',
'codeField' => '',
'projectName' => '' ),
'projectName' => 'LifeBoxME_V01',
'loginDataSource' => 'public.users',
'loginForm' => 0,
'dynamicPermissions' => true,
'dpTablePrefix' => 'public.lifeboxme_',
'dpTableConnId' => 'lifebox_mesystem_at_localhost',
'hardcodedLogin' => false,
'enabled' => true,
'advancedSecurityAvailable' => true,
'userGroupsAvailable' => true,
'defaultProviderCode' => '00',
'adOnlyLogin' => false,
'dbProvider' => array( 'type' => '%db',
'activationField' => 'active',
'active' => true,
'code' => '00',
'emailField' => 'email',
'extUserIdField' => 'ext_security_id',
'fullnameField' => 'fullname',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'password',
'resetDateField' => 'reset_date',
'resetTokenField' => 'reset_token',
'table' => array( 'connId' => 'lifebox_mesystem_at_localhost',
'table' => 'public.users' ),
'userGroupField' => 'username',
'usernameField' => 'username',
'userpicField' => 'userpic' ),
'adAdminGroups' => array(  ),
'showUserSource' => true,
'dbProviderCodes' => array( '00',
'az' ),
'notifications' => array(  ) );
?>