<?php
$securitySettings_var = array( 'providers' => array( array( 'type' => '%db',
'activationField' => 'active',
'active' => true,
'code' => '00',
'emailField' => 'email',
'extUserIdField' => 'ext_security_id',
'fullnameField' => 'fullname',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'password',
'resetDateField' => 'reset_date',
'resetTokenField' => 'reset_token',
'table' => array( 'connId' => 'lifebox_mesystem_at_localhost',
'table' => 'public.users' ),
'userGroupField' => 'username',
'usernameField' => 'username',
'userpicField' => 'userpic' ) ),
'sessionControl' => array( 'lifeTime' => 15,
'sessionName' => 'LifeboxSA7lVH6MEdvwh',
'JWTSecret' => 'KgDg763op72JzHiH0yQY',
'forceExpire' => true,
'keepAlive' => false,
'warnExpire' => true ),
'registration' => array( 'passwordValidation' => array( 'strong' => false,
'minimumLength' => 8,
'uniqueCharacters' => 4,
'digitsAndSymbols' => 2,
'upperAndLowerCase' => false ),
'remindMethod' => 1,
'hashAlgorithm' => 0,
'adminEmail' => 'admin@merqconsultancy.org',
'changePasswordPage' => true,
'changePwdPage' => true,
'hashPassword' => true,
'notifyAdmin' => true,
'notifyUser' => true,
'registerPage' => true,
'remindPage' => true,
'remindPasswordPage' => true,
'sendActivationLink' => true ),
'captchaSettings' => array( 'captchaType' => 1,
'siteKey' => '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI',
'secretKey' => '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe',
'passesCount' => 5 ),
'emailSettings' => array( 'fromEmail' => 'mne@lifebox.org',
'usePHPDefinedSMTP' => false,
'useBuiltInMailer' => false,
'SMTPServer' => 'smtp-mail.outlook.com',
'SMTPPort' => 587,
'SMTPUser' => 'mne@lifebox.org',
'SMTPPassword' => 'G.817939771353uk',
'securityProtocol' => 2 ),
'advancedSecurity' => array( 'allowGuestLogin' => false ),
'auditAndLocking' => array( 'loggingTable' => array( 'connId' => 'lifebox_mesystem_at_localhost',
'table' => 'public.lifeboxme__audit' ),
'lockingTable' => array( 'connId' => 'lifebox_mesystem_at_localhost',
'table' => 'public.lifeboxme__locking' ),
'tables' => array( 'admin_members' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'admin_rights' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'admin_users' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.antibiotics' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.case_antibiotics' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.clean_cut_implementation_summary_view' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.clean_cut_implementations' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.countries' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.daily_attendance_view' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.device_distribution_summary_view' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.device_distributions' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.diagnoses' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.facilities' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.follow_ups' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.languages' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.lifebox_staff' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.participant_attendance_detail' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.participant_attendance_summary' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.participant_role' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.partners' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.procedures' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.programs' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.quarters' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.regions' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.sex' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.surgical_case_summary_view' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.surgical_cases' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.trainers' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.training_approaches' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.training_attendance' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.training_courses' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.training_languages' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.training_leads' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.training_participants' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.training_participation' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.training_partners' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.training_sessions' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.training_summary_view' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.training_trainers' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.training_types' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.users' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.venues' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.ward_antibiotics' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'public.ward_rounds' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ) ),
'loggingMode' => 1,
'loggingFile' => 'audit.log',
'logSecurityActions' => true,
'lockAfterUnsuccessfulLogin' => true,
'enableLocking' => true ),
'twoFactorSettings' => array( 'available' => false,
'required' => false,
'enable' => true,
'remember' => true,
'types' => array(  ),
'twoFactorField' => '',
'emailField' => '',
'phoneField' => '',
'codeField' => '',
'projectName' => '' ),
'projectName' => 'LifeBoxME_V01',
'loginDataSource' => 'public.users',
'loginForm' => 0,
'dynamicPermissions' => true,
'dpTablePrefix' => 'public.lifeboxme_',
'dpTableConnId' => 'lifebox_mesystem_at_localhost',
'hardcodedLogin' => false,
'enabled' => true,
'advancedSecurityAvailable' => true,
'userGroupsAvailable' => true,
'defaultProviderCode' => '00',
'adOnlyLogin' => false,
'dbProvider' => array( 'type' => '%db',
'activationField' => 'active',
'active' => true,
'code' => '00',
'emailField' => 'email',
'extUserIdField' => 'ext_security_id',
'fullnameField' => 'fullname',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'password',
'resetDateField' => 'reset_date',
'resetTokenField' => 'reset_token',
'table' => array( 'connId' => 'lifebox_mesystem_at_localhost',
'table' => 'public.users' ),
'userGroupField' => 'username',
'usernameField' => 'username',
'userpicField' => 'userpic' ),
'adAdminGroups' => array(  ),
'showUserSource' => false,
'dbProviderCodes' => array( '00' ),
'notifications' => array(  ) );
?>