<?php
$dalTablelbpmi_summary = array();
$dalTablelbpmi_summary["indicator_id"] = array("type"=>3,"varname"=>"indicator_id", "name" => "indicator_id", "autoInc" => "0");
$dalTablelbpmi_summary["indicator_name"] = array("type"=>200,"varname"=>"indicator_name", "name" => "indicator_name", "autoInc" => "0");
$dalTablelbpmi_summary["indicator_code"] = array("type"=>200,"varname"=>"indicator_code", "name" => "indicator_code", "autoInc" => "0");
$dalTablelbpmi_summary["indicator_type"] = array("type"=>200,"varname"=>"indicator_type", "name" => "indicator_type", "autoInc" => "0");
$dalTablelbpmi_summary["formula"] = array("type"=>201,"varname"=>"formula", "name" => "formula", "autoInc" => "0");
$dalTablelbpmi_summary["period_type"] = array("type"=>200,"varname"=>"period_type", "name" => "period_type", "autoInc" => "0");
$dalTablelbpmi_summary["period_year"] = array("type"=>3,"varname"=>"period_year", "name" => "period_year", "autoInc" => "0");
$dalTablelbpmi_summary["period_quarter"] = array("type"=>3,"varname"=>"period_quarter", "name" => "period_quarter", "autoInc" => "0");
$dalTablelbpmi_summary["period_month"] = array("type"=>3,"varname"=>"period_month", "name" => "period_month", "autoInc" => "0");
$dalTablelbpmi_summary["region_id"] = array("type"=>3,"varname"=>"region_id", "name" => "region_id", "autoInc" => "0");
$dalTablelbpmi_summary["region_name"] = array("type"=>200,"varname"=>"region_name", "name" => "region_name", "autoInc" => "0");
$dalTablelbpmi_summary["country_id"] = array("type"=>3,"varname"=>"country_id", "name" => "country_id", "autoInc" => "0");
$dalTablelbpmi_summary["country_name"] = array("type"=>200,"varname"=>"country_name", "name" => "country_name", "autoInc" => "0");
$dalTablelbpmi_summary["facility_id"] = array("type"=>3,"varname"=>"facility_id", "name" => "facility_id", "autoInc" => "0");
$dalTablelbpmi_summary["facility_name"] = array("type"=>200,"varname"=>"facility_name", "name" => "facility_name", "autoInc" => "0");
$dalTablelbpmi_summary["actual_value"] = array("type"=>14,"varname"=>"actual_value", "name" => "actual_value", "autoInc" => "0");
$dalTablelbpmi_summary["target_value"] = array("type"=>14,"varname"=>"target_value", "name" => "target_value", "autoInc" => "0");
$dalTablelbpmi_summary["variance"] = array("type"=>14,"varname"=>"variance", "name" => "variance", "autoInc" => "0");
$dalTablelbpmi_summary["variance_percentage"] = array("type"=>14,"varname"=>"variance_percentage", "name" => "variance_percentage", "autoInc" => "0");
$dalTablelbpmi_summary["calculation_timestamp"] = array("type"=>135,"varname"=>"calculation_timestamp", "name" => "calculation_timestamp", "autoInc" => "0");
$dalTablelbpmi_summary["is_calculated"] = array("type"=>11,"varname"=>"is_calculated", "name" => "is_calculated", "autoInc" => "0");
$dalTablelbpmi_summary["decimals"] = array("type"=>3,"varname"=>"decimals", "name" => "decimals", "autoInc" => "0");
$dalTablelbpmi_summary["annualized"] = array("type"=>11,"varname"=>"annualized", "name" => "annualized", "autoInc" => "0");
$dalTablelbpmi_summary["data_completeness"] = array("type"=>3,"varname"=>"data_completeness", "name" => "data_completeness", "autoInc" => "0");
$dalTablelbpmi_summary["overall_completion_percentage"] = array("type"=>3,"varname"=>"overall_completion_percentage", "name" => "overall_completion_percentage", "autoInc" => "0");
$dalTablelbpmi_summary["actual_value_completion"] = array("type"=>3,"varname"=>"actual_value_completion", "name" => "actual_value_completion", "autoInc" => "0");
$dalTablelbpmi_summary["target_value_completion"] = array("type"=>3,"varname"=>"target_value_completion", "name" => "target_value_completion", "autoInc" => "0");
$dalTablelbpmi_summary["completion_status"] = array("type"=>201,"varname"=>"completion_status", "name" => "completion_status", "autoInc" => "0");
$dalTablelbpmi_summary["is_actual_missing"] = array("type"=>3,"varname"=>"is_actual_missing", "name" => "is_actual_missing", "autoInc" => "0");
$dalTablelbpmi_summary["is_target_missing"] = array("type"=>3,"varname"=>"is_target_missing", "name" => "is_target_missing", "autoInc" => "0");
$dalTablelbpmi_summary["data_freshness"] = array("type"=>201,"varname"=>"data_freshness", "name" => "data_freshness", "autoInc" => "0");
$dalTablelbpmi_summary["days_since_last_calculation"] = array("type"=>14,"varname"=>"days_since_last_calculation", "name" => "days_since_last_calculation", "autoInc" => "0");
$dalTablelbpmi_summary["performance_status"] = array("type"=>201,"varname"=>"performance_status", "name" => "performance_status", "autoInc" => "0");
$dalTablelbpmi_summary["performance_percentage"] = array("type"=>14,"varname"=>"performance_percentage", "name" => "performance_percentage", "autoInc" => "0");
$dalTablelbpmi_summary["data_quality_flag"] = array("type"=>201,"varname"=>"data_quality_flag", "name" => "data_quality_flag", "autoInc" => "0");
$dalTablelbpmi_summary["data_hierarchy_level"] = array("type"=>201,"varname"=>"data_hierarchy_level", "name" => "data_hierarchy_level", "autoInc" => "0");
$dalTablelbpmi_summary["period_completeness"] = array("type"=>201,"varname"=>"period_completeness", "name" => "period_completeness", "autoInc" => "0");
$dalTablelbpmi_summary["calculation_method"] = array("type"=>201,"varname"=>"calculation_method", "name" => "calculation_method", "autoInc" => "0");
$dalTablelbpmi_summary["formula_type"] = array("type"=>201,"varname"=>"formula_type", "name" => "formula_type", "autoInc" => "0");
$dalTablelbpmi_summary["org_unit_validity"] = array("type"=>201,"varname"=>"org_unit_validity", "name" => "org_unit_validity", "autoInc" => "0");
$dalTablelbpmi_summary["period_validity"] = array("type"=>201,"varname"=>"period_validity", "name" => "period_validity", "autoInc" => "0");
$dalTablelbpmi_summary["legacy_performance_status"] = array("type"=>201,"varname"=>"legacy_performance_status", "name" => "legacy_performance_status", "autoInc" => "0");

$dal_info["lifebox_mesystem_at_localhost_public_lbpmi_summary"] = &$dalTablelbpmi_summary;
?>