version: '3.9'

# NOTE: This file is intended to be used with the .env.dev file.
# Usage: docker-compose -f dev.docker-compose.yml --env-file .env.dev up -d

##########################################################################
# Start all services in detached mode (using .env variables automatically)
# docker-compose -p lifebox up -d

# Alternative form (explicitly specifying compose file - .env is still used)
# docker-compose -p lifebox -f dev.docker-compose.yml up -d

# Stop and remove all containers, networks, volumes, and images
# docker-compose -p lifebox down --volumes --rmi all

# Alternative form for down command
# docker-compose -p lifebox -f dev.docker-compose.yml down --volumes --rmi all

##########################################################################

# View logs (follow mode)
#docker-compose -p lifebox logs -f

# Access PostgreSQL database (note: USER comes from .env now)
#docker-compose -p lifebox exec -it lifeboxme_db psql -U ${POSTGRES_USER} -d ${POSTGRES_DB}

# Access pgAdmin container
#docker-compose -p lifebox exec -it lifeboxme_pgadmin bash

# Configure pgAdmin servers (Python commands remain the same)
#docker-compose -p lifebox exec -it lifeboxme_pgadmin python3 /pgadmin4/servers.py
#docker-compose -p lifebox exec -it lifeboxme_pgadmin python3 /pgadmin4/servers.py --load-servers /pgadmin4/servers.json

##########################################################################

# Clean data directories (same as before)
#rm -rf ./data/pgadmin-data
#rm -rf ./data/postgres-data
#rm -rf ./data/postgres-init

# Create directories (same as before)
#mkdir -p ./data/pgadmin-data
#mkdir -p ./data/postgres-data
#mkdir -p ./data/postgres-init

##########################################################################

# To see resolved configuration with variables substituted
#docker-compose -p lifebox config

# To use a different .env file (e.g., for production)
#docker-compose -p lifebox --env-file .env.prod up -d

# To check environment variables being used
#docker-compose -p lifebox exec lifeboxme_db env
##########################################################################

services:
  # Database Services
  lifeboxme_db:
    container_name: lifeboxme_db
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - .env.dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      TZ: ${TZ}
    networks:
      lifeboxnet:
        ipv4_address: ${DB_IP}
    volumes:
      - lifeboxme_db_data:/var/lib/postgresql/data
      - ./data/postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

    # Analytics Database (MariaDB)
  lifeboxme_mariadb:
    container_name: lifeboxme_mariadb
    image: mariadb:11.2.4
    restart: always
    env_file:
      - .env.dev
    environment:
      MYSQL_ROOT_HOST: localhost
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      TZ: ${TZ}
    networks:
      lifeboxnet:
        ipv4_address: ${MARIADB_IP}
    volumes:
      - lifeboxme_mariadb_data:/var/lib/mysql
#      - ./data/mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Database Management
  lifeboxme_pgadmin:
    container_name: lifeboxme_pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    env_file:
      - .env.dev
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE}
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: ${PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION}
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: ${PGADMIN_CONFIG_CONSOLE_LOG_LEVEL}
    networks:
      lifeboxnet:
        ipv4_address: ${PGADMIN_IP}
    volumes:
      - lifeboxme_pgadmin_data:/var/lib/pgadmin
      - ./pgadmin-servers.json:/pgadmin4/servers.json
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      lifeboxme_db:
        condition: service_healthy

  lifeboxme_phpmyadmin:
    container_name: lifeboxme_phpmyadmin
    image: phpmyadmin:5.2.1
    restart: always
    env_file:
      - .env.dev
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: lifeboxme_mariadb
      PMA_USER: ${MARIADB_USER}
      PMA_PASSWORD: ${MARIADB_PASSWORD}
      UPLOAD_LIMIT: 128M
    networks:
      lifeboxnet:
        ipv4_address: ${PHPMYADMIN_IP}
    depends_on:
      lifeboxme_mariadb:
        condition: service_healthy

  # Analytics Services
  lifeboxme_metabase:
    image: metabase/metabase:latest
    container_name: lifeboxme_metabase
    restart: unless-stopped
    env_file:
      - .env.dev
    ports:
      #- "127.0.0.1:${METABASE_PORT}:3000"
      - "0.0.0.0:${METABASE_PORT}:3000"
#      - "${METABASE_PORT}:3000"
    environment:
      MB_DB_TYPE: ${MB_DB_TYPE}
      MB_DB_DBNAME: ${MB_DB_DBNAME}
      MB_DB_PORT: ${POSTGRES_PORT}
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
      MB_DB_HOST: lifeboxme_db
      MB_ADMIN_EMAIL: ${MB_ADMIN_EMAIL}
      MB_ADMIN_FIRST_NAME: ${MB_ADMIN_FIRST_NAME}
      MB_ADMIN_PASSWORD: ${MB_ADMIN_PASSWORD}
      #MB_JETTY_PATH: /metabase # Optional, set if you want to change the context path
      MB_SITE_URL: https://viz.${BASE_URL}
      #MB_SITE_URL: https://${BASE_URL}/metabase/
      #MB_SITE_URL: http://localhost:${METABASE_PORT}
    networks:
      lifeboxnet:
        ipv4_address: ${METABASE_IP}
    depends_on:
      lifeboxme_db:
        condition: service_healthy

  lifeboxme_matomo:
    container_name: lifeboxme_matomo
    image: matomo:latest
    restart: always
    env_file:
      - .env.dev
    ports:
      - "${MATOMO_PORT}:80"
    networks:
      lifeboxnet:
        ipv4_address: ${MATOMO_IP}
    volumes:
      - ./analytics:/var/www/html
      - ./matomo-config:/var/www/html/config
    environment:
      MATOMO_DATABASE_HOST: lifeboxme_mariadb
      MATOMO_DATABASE_ADAPTER: ${MATOMO_DATABASE_ADAPTER}
      MATOMO_DATABASE_TABLES_PREFIX: ${MATOMO_DATABASE_TABLES_PREFIX}
      MATOMO_DATABASE_USERNAME: ${MARIADB_USER}
      MATOMO_DATABASE_PASSWORD: ${MARIADB_PASSWORD}
      MATOMO_DATABASE_DBNAME: ${MARIADB_DATABASE}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
    depends_on:
      lifeboxme_mariadb:
        condition: service_healthy
    command: /bin/bash -c "chmod -R 777 /var/www/html/tmp && apache2-foreground"

networks:
  lifeboxnet:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}

volumes:
  lifeboxme_db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/postgres-data
  lifeboxme_pgadmin_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/pgadmin-data
  lifeboxme_mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/mariadb-data