version: '3.8'

# Usage instructions:
# docker-compose -p lifebox up -d
# docker-compose -p lifebox -f docker-compose.yml up -d
# docker-compose -p lifebox down --volumes --rmi all
# docker-compose -p lifebox -f docker-compose.yml down --volumes --rmi all
# docker-compose -p lifebox logs -f
# docker-compose -p lifebox exec -it lifeboxme_db psql -U ${POSTGRES_USER} -d ${POSTGRES_DB}
# docker-compose -p lifebox exec -it lifeboxme_pgadmin bash
# docker-compose -p lifebox exec -it lifeboxme_pgadmin python3 /pgadmin4/servers.py
# docker-compose -p lifebox exec -it lifeboxme_pgadmin python3 /pgadmin4/servers.py --load-servers /pgadmin4/servers.json

# Alternative commands:
# docker-compose up -d
# docker-compose down --volumes --rmi all

# Cleanup commands:
# rm -rf ./data/pgadmin-data
# rm -rf ./data/postgres-data
# rm -rf ./data/postgres-init

# mkdir -p ./data/pgadmin-data
# mkdir -p ./data/postgres-data
# mkdir -p ./data/postgres-init

services:
  lifeboxme_db:
    container_name: lifeboxme_db
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - .env.dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      TZ: ${TZ}
    networks:
      lifeboxnet:
        ipv4_address: ${DB_IP}
    volumes:
      - lifeboxme_db_data:/var/lib/postgresql/data
      - ./data/postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  lifeboxme_pgadmin:
    container_name: lifeboxme_pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    env_file:
      - .env.dev
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE}
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: ${PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION}
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: ${PGADMIN_CONFIG_CONSOLE_LOG_LEVEL}
    networks:
      lifeboxnet:
        ipv4_address: ${PGADMIN_IP}
    volumes:
      - lifeboxme_pgadmin_data:/var/lib/pgadmin
      - ./pgadmin-servers.json:/pgadmin4/servers.json
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      lifeboxme_db:
        condition: service_healthy

  lifeboxme_metabase:
    image: metabase/metabase:latest
    container_name: lifeboxme_metabase
    restart: unless-stopped
    env_file:
      - .env.dev
    ports:
      - "0.0.0.0:${METABASE_PORT}:3000"
    environment:
      MB_DB_TYPE: ${MB_DB_TYPE}
      MB_DB_DBNAME: ${MB_DB_DBNAME}
      MB_DB_PORT: ${MB_DB_PORT}
      MB_DB_USER: ${MB_DB_USER}
      MB_DB_PASS: ${MB_DB_PASS}
      MB_DB_HOST: lifeboxme_db
      MB_ADMIN_EMAIL: ${MB_ADMIN_EMAIL}
      MB_ADMIN_FIRST_NAME: ${MB_ADMIN_FIRST_NAME}
      MB_ADMIN_PASSWORD: ${MB_ADMIN_PASSWORD}
      MB_SITE_URL: ${MB_SITE_URL}
      MB_SECRET_KEY: ${MB_SECRET_KEY}
    networks:
      lifeboxnet:
        ipv4_address: ${METABASE_IP}
    depends_on:
      lifeboxme_db:
        condition: service_healthy

  db:
    image: mariadb:11.2.4
    container_name: lifeboxme_mariadb
    restart: always
    env_file:
      - .env.dev
    environment:
      MYSQL_ROOT_HOST: localhost
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
    networks:
      lifeboxnet:
        ipv4_address: ${MARIADB_IP}

  phpmyadmin:
    image: phpmyadmin:5.2.1
    restart: always
    env_file:
      - .env.dev
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: db
      PMA_USER: ${MARIADB_USER}
      PMA_PASSWORD: ${MARIADB_PASSWORD}
    networks:
      lifeboxnet:
        ipv4_address: ${PHPMYADMIN_IP}

  lifeboxme_matomo:
    image: matomo:latest
    container_name: lifeboxme_matomo
    restart: always
    env_file:
      - .env.dev
    ports:
      - "${MATOMO_PORT}:80"
    networks:
      lifeboxnet:
        ipv4_address: ${MATOMO_IP}
    volumes:
      - ./analytics:/var/www/html
    depends_on:
      - db
    environment:
      MATOMO_DATABASE_HOST: ${MATOMO_DATABASE_HOST}
      MATOMO_DATABASE_ADAPTER: ${MATOMO_DATABASE_ADAPTER}
      MATOMO_DATABASE_TABLES_PREFIX: ${MATOMO_DATABASE_TABLES_PREFIX}
      MATOMO_DATABASE_USERNAME: ${MATOMO_DATABASE_USERNAME}
      MATOMO_DATABASE_PASSWORD: ${MATOMO_DATABASE_PASSWORD}
      MATOMO_DATABASE_DBNAME: ${MATOMO_DATABASE_DBNAME}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
    command: /bin/bash -c "chmod -R 777 /var/www/html/tmp && apache2-foreground"

networks:
  lifeboxnet:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}

volumes:
  lifeboxme_db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/postgres-data
  lifeboxme_pgadmin_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/pgadmin-data