version: '3.8'

# docker-compose -p lifebox up -d
# docker-compose -p lifebox -f docker-compose.yml up -d
# docker-compose -p lifebox down --volumes --rmi all
# docker-compose -p lifebox -f docker-compose.yml down --volumes --rmi all
##########################################################################
# docker-compose -p lifebox logs -f
# docker-compose -p lifebox exec -it lifeboxme_db psql -U lifebox_me -d lifebox_mesystem
# docker-compose -p lifebox exec -it lifeboxme_pgadmin bash
# docker-compose -p lifebox exec -it lifeboxme_pgadmin python3 /pgadmin4/servers.py
# docker-compose -p lifebox exec -it lifeboxme_pgadmin python3 /pgadmin4/servers.py --load-servers /pgadmin4/servers.json

# docker-compose up -d
# docker-compose down --volumes --rmi all

# rm -rf ./data/pgadmin-data
# rm -rf ./data/postgres-data
# rm -rf ./data/postgres-init

# mkdir -p ./data/pgadmin-data
# mkdir -p ./data/postgres-data
# mkdir -p ./data/postgres-init

services:
  lifeboxme_db:
    container_name: lifeboxme_db
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: lifebox_mesystem
      POSTGRES_USER: postgres  # lifebox_me
      POSTGRES_PASSWORD: mikeintosh
      POSTGRES_ROOT_PASSWORD: lifeboxme@sys
      TZ: UTC
    networks:
      lifeboxnet:
        ipv4_address: 192.168.47.2
    volumes:
      - lifeboxme_db_data:/var/lib/postgresql/data
      - ./data/postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  lifeboxme_pgadmin:
    container_name: lifeboxme_pgadmin
    image: dpage/pgadmin4:latest # 7.3
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@merqconsultancy.org
      PGADMIN_DEFAULT_PASSWORD: lifeboxme@sys
      PGADMIN_CONFIG_SERVER_MODE: 'False'  
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'True'
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: '10'
    networks:
      lifeboxnet:
        ipv4_address: 192.168.47.3
    volumes:
      - lifeboxme_pgadmin_data:/var/lib/pgadmin
      - ./pgadmin-servers.json:/pgadmin4/servers.json
    ports:
      - "5445:80"
    depends_on:
      lifeboxme_db:
        condition: service_healthy

  lifeboxme_metabase:
    image: metabase/metabase:latest
    container_name: lifeboxme_metabase
    restart: unless-stopped
    ports:
      #- "127.0.0.1:4000:3000"
      - "0.0.0.0:4000:3000"
      #- "4000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: lifeboxmeta
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: mikeintosh
#      MB_DB_HOST: 192.168.47.2  # Using IP address directly is not recommended in production for dev Only
      MB_DB_HOST: lifeboxme_db  # Using service name instead of IP
      MB_ADMIN_EMAIL: lifebox@cloud.merqconsultancy.org
      MB_ADMIN_FIRST_NAME: LIFEBOX
      MB_ADMIN_PASSWORD: lifeboxme0
      MB_SITE_URL: https://lifebox.merqconsultancy.org/metabase/
#      MB_SITE_URL: http://localhost:4000
    networks:
      lifeboxnet:
        ipv4_address: 192.168.47.4
    depends_on:
      lifeboxme_db:
        condition: service_healthy

  db:
    image: mariadb:11.2.4
    container_name: lifeboxme_mariadb
    restart: always
    environment:
      MYSQL_ROOT_HOST: localhost
      MYSQL_DATABASE: lifeboxme_matomo
      MYSQL_ROOT_PASSWORD: lifeboxme@system
      MYSQL_USER: lifeboxme_system
      MYSQL_PASSWORD: lifeboxme_system
    #volumes:
      # ./src/lifeboxme_dev.sql:/docker-entrypoint-initdb.d/lifeboxme_dev.sql
      #- ./src/lifeboxme_matomo.sql:/docker-entrypoint-initdb.d/lifeboxme_matomo.sql
      #- ./mysql-init:/docker-entrypoint-initdb.d
      #- /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock  # Mount the MySQL socket file if there is no conflict with the host server
    networks:
      lifeboxnet:
        ipv4_address: 192.168.47.5

  phpmyadmin:
    image: phpmyadmin:5.2.1
    restart: always
    ports:
      - "3309:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: db
      PMA_USER: lifeboxme_system
      PMA_PASSWORD: lifeboxme_system
    networks:
      lifeboxnet:
        ipv4_address: 192.168.47.6        

  lifeboxme_matomo:
    image: matomo:latest
    container_name: lifeboxme_matomo
    restart: always
    ports:
      - "8088:80"
    networks:
      lifeboxnet:
        ipv4_address: 192.168.47.7
    volumes:
      - ./analytics:/var/www/html
    depends_on:
      - db      
    environment:
      - MATOMO_DATABASE_HOST=192.168.47.7
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_USERNAME=lifeboxme_system
      - MATOMO_DATABASE_PASSWORD=lifeboxme_system
      - MATOMO_DATABASE_DBNAME=lifeboxme_matomo
      - PHP_MEMORY_LIMIT=256M
    command: /bin/bash -c "chmod -R 777 /var/www/html/tmp && apache2-foreground"        

networks:
  lifeboxnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.47.0/24
          gateway: 192.168.47.1

volumes:
  lifeboxme_db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/postgres-data
  lifeboxme_pgadmin_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/pgadmin-data
