<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'username',
'fullname',
'email',
'userpic',
'first_name',
'middle_name',
'last_name',
'sex',
'phone',
'region',
'country',
'designation_role',
'prefix_title' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'username' => array( 'integrated_edit_field' ),
'fullname' => array( 'integrated_edit_field1' ),
'email' => array( 'integrated_edit_field2' ),
'userpic' => array( 'integrated_edit_field3' ),
'first_name' => array( 'integrated_edit_field4' ),
'middle_name' => array( 'integrated_edit_field5' ),
'last_name' => array( 'integrated_edit_field6' ),
'sex' => array( 'integrated_edit_field7' ),
'phone' => array( 'integrated_edit_field8' ),
'region' => array( 'integrated_edit_field9' ),
'country' => array( 'integrated_edit_field10' ),
'designation_role' => array( 'integrated_edit_field11' ),
'prefix_title' => array( 'integrated_edit_field12' ) ) ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'below-grid' => array(  ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'loginform_login',
'username_button' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'top' => array(  ),
'grid' => array( 'user_fields_title',
'fields_message',
'user_fields_reset',
'user_fields_save',
'changepassword_link',
'integrated_edit_field12',
'integrated_edit_field4',
'integrated_edit_field2',
'integrated_edit_field9',
'integrated_edit_field6',
'integrated_edit_field8',
'integrated_edit_field5',
'integrated_edit_field7',
'integrated_edit_field',
'integrated_edit_field3',
'integrated_edit_field11',
'integrated_edit_field10',
'integrated_edit_field1' ) ),
'formXtTags' => array( 'above-grid' => array(  ),
'below-grid' => array(  ),
'top' => array(  ) ),
'itemForms' => array( 'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'user_fields_title' => 'grid',
'fields_message' => 'grid',
'user_fields_reset' => 'grid',
'user_fields_save' => 'grid',
'changepassword_link' => 'grid',
'integrated_edit_field12' => 'grid',
'integrated_edit_field4' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field9' => 'grid',
'integrated_edit_field6' => 'grid',
'integrated_edit_field8' => 'grid',
'integrated_edit_field5' => 'grid',
'integrated_edit_field7' => 'grid',
'integrated_edit_field' => 'grid',
'integrated_edit_field3' => 'grid',
'integrated_edit_field11' => 'grid',
'integrated_edit_field10' => 'grid',
'integrated_edit_field1' => 'grid' ),
'itemLocations' => array( 'user_fields_title' => array( 'location' => 'grid',
'cellId' => 'fields_message' ),
'fields_message' => array( 'location' => 'grid',
'cellId' => 'fields_message' ),
'user_fields_reset' => array( 'location' => 'grid',
'cellId' => 'buttons' ),
'user_fields_save' => array( 'location' => 'grid',
'cellId' => 'buttons' ),
'changepassword_link' => array( 'location' => 'grid',
'cellId' => 'fields' ),
'integrated_edit_field12' => array( 'location' => 'grid',
'cellId' => 'fields1' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'fields2' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'fields3' ),
'integrated_edit_field9' => array( 'location' => 'grid',
'cellId' => 'fields4' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'fields6' ),
'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'fields7' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'fields8' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'fields9' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'fields10' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'fields_message1' ),
'integrated_edit_field11' => array( 'location' => 'grid',
'cellId' => 'fields11' ),
'integrated_edit_field10' => array( 'location' => 'grid',
'cellId' => 'fields12' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'fields14' ) ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'fields_message' => array( 'fields_message' ),
'user_fields_reset' => array( 'user_fields_reset' ),
'user_fields_save' => array( 'user_fields_save' ),
'user_fields_title' => array( 'user_fields_title' ),
'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12' ),
'changepassword_link' => array( 'changepassword_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'fields_message1' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'fields_message' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'user_fields_title',
'fields_message' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'fields10' => array( 'cols' => array( 0,
1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'fields11' => array( 'cols' => array( 2,
3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'fields1' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'fields14' => array( 'cols' => array( 1,
2,
3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'fields2' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'fields8' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'fields6' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'fields9' => array( 'cols' => array( 3 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'fields3' => array( 'cols' => array( 0,
1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'fields7' => array( 'cols' => array( 2,
3 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'fields4' => array( 'cols' => array( 0,
1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'fields12' => array( 'cols' => array( 2,
3 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'fields13' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'fields15' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'fields' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 9 ),
'tags' => array( 'changepwd_link' ),
'items' => array( 'changepassword_link' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'buttons' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array( 'user_fields_reset',
'user_fields_save' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 11 ) ) ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'userinfo',
'type' => 'userinfo',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'empty-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'userinfo-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'fields_message1',
'colspan' => 4 ) ) ),
array( 'cells' => array( array( 'cell' => 'fields_message',
'colspan' => 4 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'fields10',
'colspan' => 2 ),
array( 'cell' => 'fields11',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'fields1' ),
array( 'cell' => 'fields14',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'fields2' ),
array( 'cell' => 'fields8' ),
array( 'cell' => 'fields6' ),
array( 'cell' => 'fields9' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'fields3',
'colspan' => 2 ),
array( 'cell' => 'fields7',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'fields4',
'colspan' => 2 ),
array( 'cell' => 'fields12',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'fields13',
'colspan' => 4 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'fields15',
'colspan' => 4 ) ) ),
array( 'cells' => array( array( 'cell' => 'fields',
'colspan' => 4 ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'buttons',
'colspan' => 4 ) ),
'section' => '' ) ),
'cells' => array( 'fields_message' => array( 'model' => 'fields_message',
'items' => array( 'user_fields_title',
'fields_message' ) ),
'buttons' => array( 'model' => 'buttons',
'items' => array( 'user_fields_reset',
'user_fields_save' ) ),
'fields' => array( 'model' => 'fields',
'items' => array( 'changepassword_link' ) ),
'fields1' => array( 'model' => 'fields',
'items' => array( 'integrated_edit_field12' ) ),
'fields2' => array( 'model' => 'fields',
'items' => array( 'integrated_edit_field4' ) ),
'fields3' => array( 'model' => 'fields',
'items' => array( 'integrated_edit_field2' ) ),
'fields4' => array( 'model' => 'fields',
'items' => array( 'integrated_edit_field9' ) ),
'fields6' => array( 'model' => 'fields',
'items' => array( 'integrated_edit_field6' ) ),
'fields7' => array( 'model' => 'fields',
'items' => array( 'integrated_edit_field8' ) ),
'fields8' => array( 'model' => 'fields',
'items' => array( 'integrated_edit_field5' ) ),
'fields9' => array( 'model' => 'fields',
'items' => array( 'integrated_edit_field7' ) ),
'fields10' => array( 'model' => 'fields',
'items' => array( 'integrated_edit_field' ) ),
'fields_message1' => array( 'model' => 'fields_message',
'items' => array( 'integrated_edit_field3' ) ),
'fields11' => array( 'model' => 'fields',
'items' => array( 'integrated_edit_field11' ) ),
'fields12' => array( 'model' => 'fields',
'items' => array( 'integrated_edit_field10' ) ),
'fields14' => array( 'model' => 'fields',
'items' => array( 'integrated_edit_field1' ) ),
'fields13' => array( 'model' => 'fields',
'items' => array(  ) ),
'fields15' => array( 'model' => 'fields',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'fields_message' => array( 'type' => 'fields_message' ),
'user_fields_reset' => array( 'type' => 'user_fields_reset' ),
'user_fields_save' => array( 'type' => 'user_fields_save' ),
'user_fields_title' => array( 'type' => 'user_fields_title',
'font-size' => '24px' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'integrated_edit_field' => array( 'field' => 'username',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field1' => array( 'field' => 'fullname',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'email',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'userpic',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'integrated_edit_field4' => array( 'field' => 'first_name',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'middle_name',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'last_name',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 'sex',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'phone',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'region',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'country',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field11' => array( 'field' => 'designation_role',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field12' => array( 'field' => 'prefix_title',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>