<?php
			$optionsArray = array( 'welcome' => array( 'welcomePageSkip' => true,
'welcomeItems' => array( 'text' => array( 'menutItem' => false ),
'text1' => array( 'menutItem' => false ),
'expand_menu_button' => array( 'menutItem' => false ),
'collapse_button' => array( 'menutItem' => false ),
'loginform_login' => array( 'menutItem' => false ),
'username_button' => array( 'menutItem' => false ),
'logo' => array( 'menutItem' => false ),
'expand_button' => array( 'menutItem' => false ),
'menu' => array( 'menutItem' => false ),
'welcome_item' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.antibiotics',
'page' => 'list' ),
'welcome_item1' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.case_antibiotics',
'page' => 'list' ),
'welcome_item2' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.clean_cut_implementations',
'page' => 'list' ),
'welcome_item3' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.countries',
'page' => 'list' ),
'welcome_item4' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.device_distributions',
'page' => 'list' ),
'welcome_item5' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.diagnoses',
'page' => 'list' ),
'welcome_item6' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.facilities',
'page' => 'list' ),
'welcome_item7' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.follow_ups',
'page' => 'list' ),
'welcome_item8' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.languages',
'page' => 'list' ),
'welcome_item9' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.lifebox_staff',
'page' => 'list' ),
'welcome_item10' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.partners',
'page' => 'list' ),
'welcome_item11' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.procedures',
'page' => 'list' ),
'welcome_item12' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.regions',
'page' => 'list' ),
'welcome_item13' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.surgical_cases',
'page' => 'list' ),
'welcome_item14' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.trainers',
'page' => 'list' ),
'welcome_item15' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.training_courses',
'page' => 'list' ),
'welcome_item16' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.training_languages',
'page' => 'list' ),
'welcome_item17' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.training_leads',
'page' => 'list' ),
'welcome_item18' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.training_partners',
'page' => 'list' ),
'welcome_item19' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.training_sessions',
'page' => 'list' ),
'welcome_item20' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.training_trainers',
'page' => 'list' ),
'welcome_item21' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.ward_antibiotics',
'page' => 'list' ),
'welcome_item22' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.ward_rounds',
'page' => 'list' ),
'welcome_item23' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.clean_cut_implementation_summary_view',
'page' => 'list' ),
'welcome_item24' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.device_distribution_summary_view',
'page' => 'list' ),
'welcome_item25' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.surgical_case_summary_view',
'page' => 'list' ),
'welcome_item26' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.training_summary_view',
'page' => 'list' ),
'welcome_item27' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.programs',
'page' => 'list' ),
'welcome_item28' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.training_approaches',
'page' => 'list' ),
'welcome_item29' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.training_types',
'page' => 'list' ),
'welcome_item30' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.quarters',
'page' => 'list' ),
'welcome_item31' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.participant_role',
'page' => 'list' ),
'welcome_item32' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.sex',
'page' => 'list' ),
'welcome_item33' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.training_participants',
'page' => 'list' ),
'welcome_item34' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.venues',
'page' => 'list' ),
'welcome_item35' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.training_attendance',
'page' => 'list' ),
'welcome_item37' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.participant_attendance_detail',
'page' => 'list' ),
'welcome_item38' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.participant_attendance_summary',
'page' => 'list' ),
'welcome_item36' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.training_participation',
'page' => 'list' ),
'welcome_item39' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.daily_attendance_view',
'page' => 'list' ),
'welcome_item40' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.lifeboxme__audit',
'page' => 'list' ),
'welcome_item41' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.lifeboxme__locking',
'page' => 'list' ),
'welcome_item42' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.months',
'page' => 'list' ),
'welcome_item43' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.devices',
'page' => 'list' ),
'welcome_item44' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.payment_methods',
'page' => 'list' ),
'welcome_item45' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.transaction_types',
'page' => 'list' ),
'welcome_item46' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'public.donors',
'page' => 'list' ),
'welcome_item47' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => '{04AFFBE6-86C0-47b0-ADD3-BA7FA19CA6FC}',
'page' => null ) ) ),
'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'text',
'text1' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'loginform_login',
'username_button' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'grid' => array( 'welcome_item',
'welcome_item1',
'welcome_item2',
'welcome_item3',
'welcome_item4',
'welcome_item5',
'welcome_item6',
'welcome_item7',
'welcome_item8',
'welcome_item9',
'welcome_item10',
'welcome_item11',
'welcome_item12',
'welcome_item13',
'welcome_item14',
'welcome_item15',
'welcome_item16',
'welcome_item17',
'welcome_item18',
'welcome_item19',
'welcome_item20',
'welcome_item21',
'welcome_item22',
'welcome_item23',
'welcome_item24',
'welcome_item25',
'welcome_item26',
'welcome_item27',
'welcome_item28',
'welcome_item29',
'welcome_item30',
'welcome_item31',
'welcome_item32',
'welcome_item33',
'welcome_item34',
'welcome_item35',
'welcome_item37',
'welcome_item38',
'welcome_item36',
'welcome_item39',
'welcome_item40',
'welcome_item41',
'welcome_item42',
'welcome_item43',
'welcome_item44',
'welcome_item45',
'welcome_item46',
'welcome_item47' ) ),
'formXtTags' => array(  ),
'itemForms' => array( 'text' => 'above-grid',
'text1' => 'above-grid',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'welcome_item' => 'grid',
'welcome_item1' => 'grid',
'welcome_item2' => 'grid',
'welcome_item3' => 'grid',
'welcome_item4' => 'grid',
'welcome_item5' => 'grid',
'welcome_item6' => 'grid',
'welcome_item7' => 'grid',
'welcome_item8' => 'grid',
'welcome_item9' => 'grid',
'welcome_item10' => 'grid',
'welcome_item11' => 'grid',
'welcome_item12' => 'grid',
'welcome_item13' => 'grid',
'welcome_item14' => 'grid',
'welcome_item15' => 'grid',
'welcome_item16' => 'grid',
'welcome_item17' => 'grid',
'welcome_item18' => 'grid',
'welcome_item19' => 'grid',
'welcome_item20' => 'grid',
'welcome_item21' => 'grid',
'welcome_item22' => 'grid',
'welcome_item23' => 'grid',
'welcome_item24' => 'grid',
'welcome_item25' => 'grid',
'welcome_item26' => 'grid',
'welcome_item27' => 'grid',
'welcome_item28' => 'grid',
'welcome_item29' => 'grid',
'welcome_item30' => 'grid',
'welcome_item31' => 'grid',
'welcome_item32' => 'grid',
'welcome_item33' => 'grid',
'welcome_item34' => 'grid',
'welcome_item35' => 'grid',
'welcome_item37' => 'grid',
'welcome_item38' => 'grid',
'welcome_item36' => 'grid',
'welcome_item39' => 'grid',
'welcome_item40' => 'grid',
'welcome_item41' => 'grid',
'welcome_item42' => 'grid',
'welcome_item43' => 'grid',
'welcome_item44' => 'grid',
'welcome_item45' => 'grid',
'welcome_item46' => 'grid',
'welcome_item47' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'welcome_item' => array( 'welcome_item',
'welcome_item1',
'welcome_item2',
'welcome_item3',
'welcome_item4',
'welcome_item5',
'welcome_item6',
'welcome_item7',
'welcome_item8',
'welcome_item9',
'welcome_item10',
'welcome_item11',
'welcome_item12',
'welcome_item13',
'welcome_item14',
'welcome_item15',
'welcome_item16',
'welcome_item17',
'welcome_item18',
'welcome_item19',
'welcome_item20',
'welcome_item21',
'welcome_item22',
'welcome_item23',
'welcome_item24',
'welcome_item25',
'welcome_item26',
'welcome_item27',
'welcome_item28',
'welcome_item29',
'welcome_item30',
'welcome_item31',
'welcome_item32',
'welcome_item33',
'welcome_item34',
'welcome_item35',
'welcome_item36',
'welcome_item37',
'welcome_item38',
'welcome_item39',
'welcome_item40',
'welcome_item41',
'welcome_item42',
'welcome_item43',
'welcome_item44',
'welcome_item45',
'welcome_item46',
'welcome_item47' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'text' => array( 'text',
'text1' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'menu',
'type' => 'menu',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'text' ),
'align' => 'center' ),
'c' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'text1' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'menu-topbar',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'welcome',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'welcome_item',
'welcome_item1',
'welcome_item2',
'welcome_item3',
'welcome_item4',
'welcome_item5',
'welcome_item6',
'welcome_item7',
'welcome_item8',
'welcome_item9',
'welcome_item10',
'welcome_item11',
'welcome_item12',
'welcome_item13',
'welcome_item14',
'welcome_item15',
'welcome_item16',
'welcome_item17',
'welcome_item18',
'welcome_item19',
'welcome_item20',
'welcome_item21',
'welcome_item22',
'welcome_item23',
'welcome_item24',
'welcome_item25',
'welcome_item26',
'welcome_item27',
'welcome_item28',
'welcome_item29',
'welcome_item30',
'welcome_item31',
'welcome_item32',
'welcome_item33',
'welcome_item34',
'welcome_item35',
'welcome_item37',
'welcome_item38',
'welcome_item36',
'welcome_item39',
'welcome_item40',
'welcome_item41',
'welcome_item42',
'welcome_item43',
'welcome_item44',
'welcome_item45',
'welcome_item46',
'welcome_item47' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'welcome_item' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.antibiotics',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.antibiotics',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'tree-conifer' ),
'linkComments' => array( 'text' => 'Antibiotics description',
'type' => 0 ),
'background' => '#BC8F8F',
'linkType' => 0 ),
'welcome_item1' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.case_antibiotics',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.case_antibiotics',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'shopping-cart' ),
'linkComments' => array( 'text' => 'Case Antibiotics description',
'type' => 0 ),
'background' => '#CFAE83',
'linkType' => 0 ),
'welcome_item2' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.clean_cut_implementations',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.clean_cut_implementations',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'camera' ),
'linkComments' => array( 'text' => 'Clean Cut Implementations description',
'type' => 0 ),
'background' => '#8FBC8B',
'linkType' => 0 ),
'welcome_item3' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.countries',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.countries',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'leaf' ),
'linkComments' => array( 'text' => 'Countries description',
'type' => 0 ),
'background' => '#D2AF80',
'linkType' => 0 ),
'welcome_item4' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.device_distributions',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.device_distributions',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'tree-conifer' ),
'linkComments' => array( 'text' => 'Device Distributions description',
'type' => 0 ),
'background' => '#CD853F',
'linkType' => 0 ),
'welcome_item5' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.diagnoses',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.diagnoses',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'shopping-cart' ),
'background' => '#B22222',
'linkType' => 0 ),
'welcome_item6' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.facilities',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.facilities',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'tree-conifer' ),
'background' => '#6493EA',
'linkType' => 0 ),
'welcome_item7' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.follow_ups',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.follow_ups',
'type' => 6 ),
'background' => '#E07878',
'linkType' => 0 ),
'welcome_item8' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.languages',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.languages',
'type' => 6 ),
'background' => '#CD5C5C',
'linkType' => 0 ),
'welcome_item9' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.lifebox_staff',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.lifebox_staff',
'type' => 6 ),
'background' => '#00C2C5',
'linkType' => 0 ),
'welcome_item10' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.partners',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.partners',
'type' => 6 ),
'background' => '#4682B4',
'linkType' => 0 ),
'welcome_item11' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.procedures',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.procedures',
'type' => 6 ),
'background' => '#EDCA00',
'linkType' => 0 ),
'welcome_item12' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.regions',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.regions',
'type' => 6 ),
'background' => '#1E90FF',
'linkType' => 0 ),
'welcome_item13' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.surgical_cases',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.surgical_cases',
'type' => 6 ),
'background' => '#CFAE83',
'linkType' => 0 ),
'welcome_item14' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.trainers',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.trainers',
'type' => 6 ),
'background' => '#D2691E',
'linkType' => 0 ),
'welcome_item15' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.training_courses',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.training_courses',
'type' => 6 ),
'background' => '#3CB371',
'linkType' => 0 ),
'welcome_item16' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.training_languages',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.training_languages',
'type' => 6 ),
'background' => '#E07878',
'linkType' => 0 ),
'welcome_item17' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.training_leads',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.training_leads',
'type' => 6 ),
'background' => '#4169E1',
'linkType' => 0 ),
'welcome_item18' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.training_partners',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.training_partners',
'type' => 6 ),
'background' => '#2F4F4F',
'linkType' => 0 ),
'welcome_item19' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.training_sessions',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.training_sessions',
'type' => 6 ),
'background' => '#2F4F4F',
'linkType' => 0 ),
'welcome_item20' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.training_trainers',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.training_trainers',
'type' => 6 ),
'background' => '#008B8B',
'linkType' => 0 ),
'welcome_item21' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.ward_antibiotics',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.ward_antibiotics',
'type' => 6 ),
'background' => '#D2691E',
'linkType' => 0 ),
'welcome_item22' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.ward_rounds',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.ward_rounds',
'type' => 6 ),
'background' => '#DB7093',
'linkType' => 0 ),
'welcome_item23' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.clean_cut_implementation_summary_view',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.clean_cut_implementation_summary_view',
'type' => 6 ),
'background' => '#DAA520',
'linkType' => 0 ),
'welcome_item24' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.device_distribution_summary_view',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.device_distribution_summary_view',
'type' => 6 ),
'background' => '#DAA520',
'linkType' => 0 ),
'welcome_item25' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.surgical_case_summary_view',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.surgical_case_summary_view',
'type' => 6 ),
'background' => '#4682B4',
'linkType' => 0 ),
'welcome_item26' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.training_summary_view',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.training_summary_view',
'type' => 6 ),
'background' => '#E8926F',
'linkType' => 0 ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => '<div style="display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center;">
  <img src="https://www.lifebox.org/wp-content/themes/lifebox/assets//images/lblogo-dark.svg" alt="Logo" style="height: 50px; margin-bottom: 5px;">
  <div style="font-size: 27px; font-weight: bold;">
    <span style="color: red;">M</span>
    <span style="color: #1e6a7d;">&amp;</span>
    <span style="color: orange;">E</span>
    <span style="color: #1e6a7d;"> System</span>
  </div>
</div>
',
'type' => 0 ),
'editedByRte' => false ),
'text1' => array( 'type' => 'text',
'label' => array( 'text' => '<p class="ql-align-center"><strong>DEMO VERSION</strong></p>',
'type' => 0 ),
'editedByRte' => true ),
'welcome_item27' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.programs',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.programs',
'type' => 6 ),
'background' => '#D2691E',
'linkType' => 0 ),
'welcome_item28' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.training_approaches',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.training_approaches',
'type' => 6 ),
'background' => '#2F4F4F',
'linkType' => 0 ),
'welcome_item29' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.training_types',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.training_types',
'type' => 6 ),
'background' => '#E07878',
'linkType' => 0 ),
'welcome_item30' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.quarters',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.quarters',
'type' => 6 ),
'background' => '#4682B4',
'linkType' => 0 ),
'welcome_item31' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.participant_role',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.participant_role',
'type' => 6 ),
'background' => '#B22222',
'linkType' => 0 ),
'welcome_item32' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.sex',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.sex',
'type' => 6 ),
'background' => '#7B68EE',
'linkType' => 0 ),
'welcome_item33' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.training_participants',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.training_participants',
'type' => 6 ),
'background' => '#DB7093',
'linkType' => 0 ),
'welcome_item34' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.venues',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.venues',
'type' => 6 ),
'background' => '#008B8B',
'linkType' => 0 ),
'welcome_item35' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.training_attendance',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.training_attendance',
'type' => 6 ),
'background' => '#E67349',
'linkType' => 0 ),
'welcome_item36' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.training_participation',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.training_participation',
'type' => 6 ),
'background' => '#D2AF80',
'linkType' => 0 ),
'welcome_item37' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.participant_attendance_detail',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.participant_attendance_detail',
'type' => 6 ),
'background' => '#BC8F8F',
'linkType' => 0 ),
'welcome_item38' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.participant_attendance_summary',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.participant_attendance_summary',
'type' => 6 ),
'background' => '#2F4F4F',
'linkType' => 0 ),
'welcome_item39' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.daily_attendance_view',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.daily_attendance_view',
'type' => 6 ),
'background' => '#E07878',
'linkType' => 0 ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'welcome_item40' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.lifeboxme__audit',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.lifeboxme__audit',
'type' => 6 ),
'background' => '#5F9EA0',
'linkType' => 0 ),
'welcome_item41' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.lifeboxme__locking',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.lifeboxme__locking',
'type' => 6 ),
'background' => '#E07878',
'linkType' => 0 ),
'welcome_item42' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.months',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.months',
'type' => 6 ),
'background' => '#BC8F8F',
'linkType' => 0 ),
'welcome_item43' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.devices',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.devices',
'type' => 6 ),
'background' => '#CFAE83',
'linkType' => 0 ),
'welcome_item44' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.payment_methods',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.payment_methods',
'type' => 6 ),
'background' => '#D2691E',
'linkType' => 0 ),
'welcome_item45' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.transaction_types',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.transaction_types',
'type' => 6 ),
'background' => '#4169E1',
'linkType' => 0 ),
'welcome_item46' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'public.donors',
'linkPage' => 'list',
'linkText' => array( 'table' => 'public.donors',
'type' => 6 ),
'background' => '#DAA520',
'linkType' => 0 ),
'welcome_item47' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => '{04AFFBE6-86C0-47b0-ADD3-BA7FA19CA6FC}',
'linkPage' => null,
'linkText' => null,
'linkType' => 0 ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>