<?php
			$optionsArray = array( 'captcha' => array( 'captcha' => true ),
'fields' => array( 'gridFields' => array( 'fullname',
'username',
'password',
'email',
'prefix_title',
'first_name',
'middle_name',
'last_name',
'sex',
'phone',
'region',
'country',
'designation_role' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'fullname' => array( 'integrated_edit_field' ),
'username' => array( 'integrated_edit_field1' ),
'password' => array( 'integrated_edit_field2' ),
'confirm_aoel3cx' => array( 'integrated_confirm_password' ),
'email' => array( 'integrated_edit_field3' ),
'prefix_title' => array( 'integrated_edit_field4' ),
'first_name' => array( 'integrated_edit_field5' ),
'middle_name' => array( 'integrated_edit_field6' ),
'last_name' => array( 'integrated_edit_field7' ),
'sex' => array( 'integrated_edit_field8' ),
'phone' => array( 'integrated_edit_field9' ),
'region' => array( 'integrated_edit_field10' ),
'country' => array( 'integrated_edit_field11' ),
'designation_role' => array( 'integrated_edit_field12' ) ) ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'register_message' ),
'top' => array( 'register_header',
'text' ),
'footer' => array( 'register_save',
'back_to_login',
'register_reset' ),
'grid' => array( 'integrated_edit_field1',
'captcha',
'integrated_edit_field5',
'integrated_edit_field2',
'integrated_confirm_password',
'integrated_edit_field3',
'integrated_edit_field10',
'integrated_edit_field8',
'integrated_edit_field4',
'integrated_edit_field6',
'integrated_edit_field',
'integrated_edit_field7',
'integrated_edit_field12',
'integrated_edit_field9',
'integrated_edit_field11' ) ),
'formXtTags' => array(  ),
'itemForms' => array( 'register_message' => 'above-grid',
'register_header' => 'top',
'text' => 'top',
'register_save' => 'footer',
'back_to_login' => 'footer',
'register_reset' => 'footer',
'integrated_edit_field1' => 'grid',
'captcha' => 'grid',
'integrated_edit_field5' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_confirm_password' => 'grid',
'integrated_edit_field3' => 'grid',
'integrated_edit_field10' => 'grid',
'integrated_edit_field8' => 'grid',
'integrated_edit_field4' => 'grid',
'integrated_edit_field6' => 'grid',
'integrated_edit_field' => 'grid',
'integrated_edit_field7' => 'grid',
'integrated_edit_field12' => 'grid',
'integrated_edit_field9' => 'grid',
'integrated_edit_field11' => 'grid' ),
'itemLocations' => array( 'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'captcha' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_confirm_password' => array( 'location' => 'grid',
'cellId' => 'c2' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c9' ),
'integrated_edit_field10' => array( 'location' => 'grid',
'cellId' => 'c10' ),
'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'c11' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c12' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c13' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c14' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c15' ),
'integrated_edit_field12' => array( 'location' => 'grid',
'cellId' => 'c16' ),
'integrated_edit_field9' => array( 'location' => 'grid',
'cellId' => 'c19' ),
'integrated_edit_field11' => array( 'location' => 'grid',
'cellId' => 'c22' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'register_header' => array( 'register_header' ),
'register_reset' => array( 'register_reset' ),
'register_message' => array( 'register_message' ),
'register_save' => array( 'register_save' ),
'back_to_login' => array( 'back_to_login' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12' ),
'integrated_confirm_password' => array( 'integrated_confirm_password' ),
'text' => array( 'text' ),
'captcha' => array( 'captcha' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c12' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 1,
2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c15' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 1,
2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 0,
1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c19' => array( 'cols' => array( 0,
1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c22' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c18' => array( 'cols' => array( 0,
1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c20' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0,
1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 2 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0,
1 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 2 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0,
1 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array( 'integrated_confirm_password' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 2 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array( 'captcha' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 11 ) ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'register' => array( 'gridFields' => array( 'fullname',
'username',
'password',
'email',
'prefix_title',
'first_name',
'middle_name',
'last_name',
'sex',
'phone',
'region',
'country',
'designation_role' ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'register',
'type' => 'register',
'layoutId' => 'pretty1',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'register-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'register_message' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'register-header',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'register_header' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'text' ),
'align' => 'center' ),
'c2' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'register-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'register_save',
'back_to_login' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'register_reset' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c12' ),
array( 'cell' => 'c14',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c13' ),
array( 'cell' => 'c15' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c11' ),
array( 'cell' => 'c16',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c9',
'colspan' => 2 ),
array( 'cell' => 'c10' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c19',
'colspan' => 2 ),
array( 'cell' => 'c22' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c18',
'colspan' => 2 ),
array( 'cell' => 'c20' ) ) ),
array( 'cells' => array( array( 'cell' => 'c3',
'colspan' => 2 ),
array( 'cell' => 'c5' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2',
'colspan' => 2 ),
array( 'cell' => 'c8' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c',
'colspan' => 3 ) ) ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field1' ) ),
'c' => array( 'model' => 'c3',
'items' => array( 'captcha' ) ),
'c4' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field5' ) ),
'c5' => array( 'model' => 'c3',
'items' => array(  ) ),
'c1' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field2' ) ),
'c2' => array( 'model' => 'c3',
'items' => array( 'integrated_confirm_password' ) ),
'c6' => array( 'model' => 'c3',
'items' => array(  ) ),
'c7' => array( 'model' => 'c3',
'items' => array(  ) ),
'c8' => array( 'model' => 'c3',
'items' => array(  ) ),
'c9' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field3' ) ),
'c10' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field10' ) ),
'c11' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field8' ) ),
'c12' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field4' ) ),
'c13' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field6' ) ),
'c14' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field' ) ),
'c15' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field7' ) ),
'c16' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field12' ) ),
'c18' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#70b497' ),
'c20' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#ef7541' ),
'c19' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field9' ) ),
'c22' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field11' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'register_header' => array( 'type' => 'register_header',
'bold' => true ),
'register_reset' => array( 'type' => 'register_reset' ),
'register_message' => array( 'type' => 'register_message' ),
'register_save' => array( 'type' => 'register_save' ),
'back_to_login' => array( 'type' => 'back_to_login' ),
'integrated_edit_field' => array( 'field' => 'fullname',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'fullname',
'table' => 'public.users',
'type' => 3 ) ),
'integrated_edit_field1' => array( 'field' => 'username',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'password',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_confirm_password' => array( 'type' => 'integrated_confirm_password',
'field' => 'confirm_aoel3cx',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'email',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => '<div style="display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center;">
  <img src="https://www.lifebox.org/wp-content/themes/lifebox/assets//images/lblogo-dark.svg" alt="Logo" style="height: 30px; margin-bottom: 5px;">
  <div style="font-size: 17px; font-weight: bold;">
    <span style="color: red;">M</span>
    <span style="color: #1e6a7d;">&amp;</span>
    <span style="color: orange;">E</span>
    <span style="color: #1e6a7d;"> System</span>
  </div>
</div>
',
'type' => 0 ),
'editedByRte' => false ),
'integrated_edit_field4' => array( 'field' => 'prefix_title',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'first_name',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'middle_name',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 'last_name',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'sex',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'phone',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'region',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field11' => array( 'field' => 'country',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field12' => array( 'field' => 'designation_role',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'captcha' => array( 'type' => 'captcha' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image',
'fullSize' => true,
'image' => array( 'image' => 'lifebox.svg',
'source' => 2 ) ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'left',
'listTotals' => 1 );
		?>