<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'implementation_id',
'facility_name',
'country_name',
'region_name',
'implementation_year',
'start_date',
'end_date',
'implementation_months',
'avg_monthly_surgical_volume',
'estimated_operations_impacted',
'general_surgery_volume',
'ob_gyn_volume',
'pediatrics_volume',
'ortho_volume',
'total_volume',
'remarks' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'implementation_id' => array( 'import_field' ),
'facility_name' => array( 'import_field1' ),
'country_name' => array( 'import_field2' ),
'region_name' => array( 'import_field3' ),
'implementation_year' => array( 'import_field4' ),
'start_date' => array( 'import_field5' ),
'end_date' => array( 'import_field6' ),
'implementation_months' => array( 'import_field7' ),
'avg_monthly_surgical_volume' => array( 'import_field8' ),
'estimated_operations_impacted' => array( 'import_field9' ),
'general_surgery_volume' => array( 'import_field10' ),
'ob_gyn_volume' => array( 'import_field11' ),
'pediatrics_volume' => array( 'import_field12' ),
'ortho_volume' => array( 'import_field13' ),
'total_volume' => array( 'import_field14' ),
'remarks' => array( 'import_field15' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'implementation_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'facility_name',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'country_name',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'region_name',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'implementation_year',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'start_date',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'end_date',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'implementation_months',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'avg_monthly_surgical_volume',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'estimated_operations_impacted',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'general_surgery_volume',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'ob_gyn_volume',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'pediatrics_volume',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'ortho_volume',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'total_volume',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'remarks',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>