<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'grid' => array( 'chart',
'chart1',
'dashboard-item',
'dashboard-item2' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'username_button' ),
'top' => array(  ) ),
'formXtTags' => array( 'top' => array(  ) ),
'itemForms' => array( 'chart' => 'grid',
'chart1' => 'grid',
'dashboard-item' => 'grid',
'dashboard-item2' => 'grid',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'username_button' => 'supertop' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'username_button' => array( 'username_button' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'chart' => array( 'chart',
'chart1' ),
'dashboard-item' => array( 'dashboard-item',
'dashboard-item2' ),
'list_options' => array( 'list_options' ),
'advsearch_link' => array( 'advsearch_link' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'dashboard',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dashboard' => array( 'elements' => array( array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'Dashboard',
'dashType' => 4,
'dashName' => 'Dashboard_search',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'bell' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'reloadInterval' => 0,
'pageId' => 'search',
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Dashboard Grid Search' ),
'tabLeaveSpace' => true ),
'elementName' => 'Dashboard_search',
'table' => 'Dashboard',
'pageName' => 'search',
'type' => 4,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'tabLeaveSpace' => true,
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'aio_training_tracking',
'dashType' => 0,
'dashName' => 'aio_training_tracking_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'heart-empty' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list' ),
'elementName' => 'aio_training_tracking_grid',
'table' => 'aio_training_tracking',
'pageName' => 'list',
'type' => 0,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ) ) ),
'dashSearch' => array( 'searchFields' => array( 'aio_training_tracking_gender' => array( array( 'field' => 'gender',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_participant_role' => array( array( 'field' => 'participant_role',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_country' => array( array( 'field' => 'country',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_facility' => array( array( 'field' => 'facility',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_training_id' => array( array( 'field' => 'training_id',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_training_name' => array( array( 'field' => 'training_name',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_program' => array( array( 'field' => 'program',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_partners' => array( array( 'field' => 'partners',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_training_type' => array( array( 'field' => 'training_type',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_training_approach' => array( array( 'field' => 'training_approach',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_training_language' => array( array( 'field' => 'training_language',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_training_lead' => array( array( 'field' => 'training_lead',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_quarter' => array( array( 'field' => 'quarter',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_attendance_status' => array( array( 'field' => 'attendance_status',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_Chart_gender' => array( array( 'field' => 'gender',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_participant_id' => array( array( 'field' => 'participant_id',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_title' => array( array( 'field' => 'title',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_first_name' => array( array( 'field' => 'first_name',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_middle_name' => array( array( 'field' => 'middle_name',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_last_name' => array( array( 'field' => 'last_name',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_phone' => array( array( 'field' => 'phone',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_email' => array( array( 'field' => 'email',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_start_date' => array( array( 'field' => 'start_date',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_end_date' => array( array( 'field' => 'end_date',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_total_days' => array( array( 'field' => 'total_days',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_days_recorded' => array( array( 'field' => 'days_recorded',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_days_attended' => array( array( 'field' => 'days_attended',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_attendance_percentage' => array( array( 'field' => 'attendance_percentage',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_pre_test_score' => array( array( 'field' => 'pre_test_score',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_post_test_score' => array( array( 'field' => 'post_test_score',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_ceu_points' => array( array( 'field' => 'ceu_points',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_Chart_participant_id' => array( array( 'field' => 'participant_id',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_title' => array( array( 'field' => 'title',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_first_name' => array( array( 'field' => 'first_name',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_middle_name' => array( array( 'field' => 'middle_name',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_last_name' => array( array( 'field' => 'last_name',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_participant_role' => array( array( 'field' => 'participant_role',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_country' => array( array( 'field' => 'country',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_facility' => array( array( 'field' => 'facility',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_phone' => array( array( 'field' => 'phone',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_email' => array( array( 'field' => 'email',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_training_id' => array( array( 'field' => 'training_id',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_training_name' => array( array( 'field' => 'training_name',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_program' => array( array( 'field' => 'program',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_partners' => array( array( 'field' => 'partners',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_training_type' => array( array( 'field' => 'training_type',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_training_approach' => array( array( 'field' => 'training_approach',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_training_language' => array( array( 'field' => 'training_language',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_training_lead' => array( array( 'field' => 'training_lead',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_quarter' => array( array( 'field' => 'quarter',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_start_date' => array( array( 'field' => 'start_date',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_end_date' => array( array( 'field' => 'end_date',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_total_days' => array( array( 'field' => 'total_days',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_days_recorded' => array( array( 'field' => 'days_recorded',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_days_attended' => array( array( 'field' => 'days_attended',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_attendance_percentage' => array( array( 'field' => 'attendance_percentage',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_attendance_status' => array( array( 'field' => 'attendance_status',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_pre_test_score' => array( array( 'field' => 'pre_test_score',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_post_test_score' => array( array( 'field' => 'post_test_score',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_ceu_points' => array( array( 'field' => 'ceu_points',
'table' => 'aio_training_tracking Chart' ) ) ),
'allSearchFields' => array( 'aio_training_tracking_gender',
'aio_training_tracking_participant_role',
'aio_training_tracking_country',
'aio_training_tracking_facility',
'aio_training_tracking_training_id',
'aio_training_tracking_training_name',
'aio_training_tracking_program',
'aio_training_tracking_partners',
'aio_training_tracking_training_type',
'aio_training_tracking_training_approach',
'aio_training_tracking_training_language',
'aio_training_tracking_training_lead',
'aio_training_tracking_quarter',
'aio_training_tracking_attendance_status',
'aio_training_tracking_Chart_gender',
'aio_training_tracking_participant_id',
'aio_training_tracking_title',
'aio_training_tracking_first_name',
'aio_training_tracking_middle_name',
'aio_training_tracking_last_name',
'aio_training_tracking_phone',
'aio_training_tracking_email',
'aio_training_tracking_start_date',
'aio_training_tracking_end_date',
'aio_training_tracking_total_days',
'aio_training_tracking_days_recorded',
'aio_training_tracking_days_attended',
'aio_training_tracking_attendance_percentage',
'aio_training_tracking_pre_test_score',
'aio_training_tracking_post_test_score',
'aio_training_tracking_ceu_points',
'aio_training_tracking_Chart_participant_id',
'aio_training_tracking_Chart_title',
'aio_training_tracking_Chart_first_name',
'aio_training_tracking_Chart_middle_name',
'aio_training_tracking_Chart_last_name',
'aio_training_tracking_Chart_participant_role',
'aio_training_tracking_Chart_country',
'aio_training_tracking_Chart_facility',
'aio_training_tracking_Chart_phone',
'aio_training_tracking_Chart_email',
'aio_training_tracking_Chart_training_id',
'aio_training_tracking_Chart_training_name',
'aio_training_tracking_Chart_program',
'aio_training_tracking_Chart_partners',
'aio_training_tracking_Chart_training_type',
'aio_training_tracking_Chart_training_approach',
'aio_training_tracking_Chart_training_language',
'aio_training_tracking_Chart_training_lead',
'aio_training_tracking_Chart_quarter',
'aio_training_tracking_Chart_start_date',
'aio_training_tracking_Chart_end_date',
'aio_training_tracking_Chart_total_days',
'aio_training_tracking_Chart_days_recorded',
'aio_training_tracking_Chart_days_attended',
'aio_training_tracking_Chart_attendance_percentage',
'aio_training_tracking_Chart_attendance_status',
'aio_training_tracking_Chart_pre_test_score',
'aio_training_tracking_Chart_post_test_score',
'aio_training_tracking_Chart_ceu_points' ),
'googleLikeFields' => array( 'aio_training_tracking_gender',
'aio_training_tracking_participant_role',
'aio_training_tracking_country',
'aio_training_tracking_facility',
'aio_training_tracking_training_id',
'aio_training_tracking_training_name',
'aio_training_tracking_program',
'aio_training_tracking_partners',
'aio_training_tracking_training_type',
'aio_training_tracking_training_approach',
'aio_training_tracking_training_language',
'aio_training_tracking_training_lead',
'aio_training_tracking_quarter',
'aio_training_tracking_attendance_status',
'aio_training_tracking_Chart_gender',
'aio_training_tracking_participant_id',
'aio_training_tracking_title',
'aio_training_tracking_first_name',
'aio_training_tracking_middle_name',
'aio_training_tracking_last_name',
'aio_training_tracking_phone',
'aio_training_tracking_email',
'aio_training_tracking_start_date',
'aio_training_tracking_end_date',
'aio_training_tracking_total_days',
'aio_training_tracking_days_recorded',
'aio_training_tracking_days_attended',
'aio_training_tracking_attendance_percentage',
'aio_training_tracking_pre_test_score',
'aio_training_tracking_post_test_score',
'aio_training_tracking_ceu_points',
'aio_training_tracking_Chart_participant_role',
'aio_training_tracking_Chart_country',
'aio_training_tracking_Chart_training_name' ) ) );
			$pageArray = array( 'id' => 'all_in_one_training',
'type' => 'dashboard',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'grid' => array( 'modelId' => 'dashboard-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c10' ),
array( 'cell' => 'c11' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'chart' ),
'align' => 'center' ),
'c' => array( 'model' => 'c1',
'items' => array( 'chart1' ),
'align' => 'center' ),
'c2' => array( 'model' => 'c1',
'items' => array(  ) ),
'c3' => array( 'model' => 'c1',
'items' => array(  ) ),
'c4' => array( 'model' => 'c1',
'items' => array(  ) ),
'c5' => array( 'model' => 'c1',
'items' => array(  ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'dashboard-item' ),
'align' => 'center',
'width' => '' ),
'c10' => array( 'model' => 'c1',
'items' => array(  ) ),
'c11' => array( 'model' => 'c1',
'items' => array(  ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'dashboard-item2' ),
'align' => 'center',
'width' => '' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-dashboard',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-dashboard',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'dashboard-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c4' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c4' => array( 'model' => 'c4',
'items' => array(  ) ),
'c' => array( 'model' => 'c4',
'items' => array(  ) ),
'c5' => array( 'model' => 'c4',
'items' => array(  ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'chart' => array( 'type' => 'chart',
'table' => 'aio_training_tracking Chart',
'icon' => array( 'glyph' => 'signal' ) ),
'chart1' => array( 'type' => 'chart',
'table' => 'aio_training_tracking Chart by sex',
'icon' => array( 'glyph' => 'signal' ) ),
'dashboard-item' => array( 'type' => 'dashboard-item',
'table' => 'aio_training_tracking',
'dashType' => 0,
'dashName' => 'aio_training_tracking_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'heart-empty' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'advsearch_link' ) ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'dashboard-item2' => array( 'type' => 'dashboard-item',
'table' => 'Dashboard',
'dashType' => 4,
'dashName' => 'Dashboard_search',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'bell' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'reloadInterval' => 0,
'pageId' => 'search',
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Dashboard Grid Search' ),
'tabLeaveSpace' => true ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>