<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'aio_training_tracking_gender',
'aio_training_tracking_participant_role',
'aio_training_tracking_country',
'aio_training_tracking_facility',
'aio_training_tracking_training_id',
'aio_training_tracking_training_name',
'aio_training_tracking_program',
'aio_training_tracking_partners',
'aio_training_tracking_training_type',
'aio_training_tracking_training_approach',
'aio_training_tracking_training_language',
'aio_training_tracking_training_lead',
'aio_training_tracking_quarter',
'aio_training_tracking_attendance_status',
'aio_training_tracking_Chart_gender',
'aio_training_tracking_Chart_participant_role',
'aio_training_tracking_Chart_country',
'aio_training_tracking_Chart_training_name' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'aio_training_tracking_gender' => array( 'integrated_search_field' ),
'aio_training_tracking_participant_role' => array( 'integrated_search_field1' ),
'aio_training_tracking_country' => array( 'integrated_search_field2' ),
'aio_training_tracking_facility' => array( 'integrated_search_field3' ),
'aio_training_tracking_training_id' => array( 'integrated_search_field4' ),
'aio_training_tracking_training_name' => array( 'integrated_search_field5' ),
'aio_training_tracking_program' => array( 'integrated_search_field6' ),
'aio_training_tracking_partners' => array( 'integrated_search_field7' ),
'aio_training_tracking_training_type' => array( 'integrated_search_field8' ),
'aio_training_tracking_training_approach' => array( 'integrated_search_field9' ),
'aio_training_tracking_training_language' => array( 'integrated_search_field10' ),
'aio_training_tracking_training_lead' => array( 'integrated_search_field11' ),
'aio_training_tracking_quarter' => array( 'integrated_search_field12' ),
'aio_training_tracking_attendance_status' => array( 'integrated_search_field13' ),
'aio_training_tracking_Chart_gender' => array( 'integrated_search_field14' ),
'aio_training_tracking_Chart_participant_role' => array( 'integrated_search_field15' ),
'aio_training_tracking_Chart_country' => array( 'integrated_search_field16' ),
'aio_training_tracking_Chart_training_name' => array( 'integrated_search_field17' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'below-grid' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'top' => array( 'search_header' ),
'grid' => array( 'integrated_search_field17',
'integrated_search_field14',
'integrated_search_field',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'search_search' => 'below-grid',
'search_reset' => 'below-grid',
'search_back_list' => 'below-grid',
'search_cancel' => 'below-grid',
'search_header' => 'top',
'integrated_search_field17' => 'grid',
'integrated_search_field14' => 'grid',
'integrated_search_field' => 'grid',
'integrated_search_field15' => 'grid',
'integrated_search_field16' => 'grid',
'integrated_search_field1' => 'grid',
'integrated_search_field2' => 'grid',
'integrated_search_field3' => 'grid',
'integrated_search_field4' => 'grid',
'integrated_search_field5' => 'grid',
'integrated_search_field6' => 'grid',
'integrated_search_field7' => 'grid',
'integrated_search_field8' => 'grid',
'integrated_search_field9' => 'grid',
'integrated_search_field10' => 'grid',
'integrated_search_field11' => 'grid',
'integrated_search_field12' => 'grid',
'integrated_search_field13' => 'grid' ),
'itemLocations' => array( 'integrated_search_field17' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field14' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field15' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field16' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field5' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field8' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field9' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field10' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field11' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field12' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field13' => array( 'location' => 'grid',
'cellId' => 'c3' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'search_header' => array( 'search_header' ),
'search_reset' => array( 'search_reset' ),
'search_back_list' => array( 'search_back_list' ),
'search_search' => array( 'search_search' ),
'search_cancel' => array( 'search_cancel' ),
'integrated_search_field' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field17',
'integrated_search_field14',
'integrated_search_field',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'search',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dashSearch' => array( 'searchFields' => array( 'aio_training_tracking_gender' => array( array( 'field' => 'gender',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_participant_role' => array( array( 'field' => 'participant_role',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_country' => array( array( 'field' => 'country',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_facility' => array( array( 'field' => 'facility',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_training_id' => array( array( 'field' => 'training_id',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_training_name' => array( array( 'field' => 'training_name',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_program' => array( array( 'field' => 'program',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_partners' => array( array( 'field' => 'partners',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_training_type' => array( array( 'field' => 'training_type',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_training_approach' => array( array( 'field' => 'training_approach',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_training_language' => array( array( 'field' => 'training_language',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_training_lead' => array( array( 'field' => 'training_lead',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_quarter' => array( array( 'field' => 'quarter',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_attendance_status' => array( array( 'field' => 'attendance_status',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_Chart_gender' => array( array( 'field' => 'gender',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_participant_id' => array( array( 'field' => 'participant_id',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_title' => array( array( 'field' => 'title',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_first_name' => array( array( 'field' => 'first_name',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_middle_name' => array( array( 'field' => 'middle_name',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_last_name' => array( array( 'field' => 'last_name',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_phone' => array( array( 'field' => 'phone',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_email' => array( array( 'field' => 'email',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_start_date' => array( array( 'field' => 'start_date',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_end_date' => array( array( 'field' => 'end_date',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_total_days' => array( array( 'field' => 'total_days',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_days_recorded' => array( array( 'field' => 'days_recorded',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_days_attended' => array( array( 'field' => 'days_attended',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_attendance_percentage' => array( array( 'field' => 'attendance_percentage',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_pre_test_score' => array( array( 'field' => 'pre_test_score',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_post_test_score' => array( array( 'field' => 'post_test_score',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_ceu_points' => array( array( 'field' => 'ceu_points',
'table' => 'aio_training_tracking' ) ),
'aio_training_tracking_Chart_participant_id' => array( array( 'field' => 'participant_id',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_title' => array( array( 'field' => 'title',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_first_name' => array( array( 'field' => 'first_name',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_middle_name' => array( array( 'field' => 'middle_name',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_last_name' => array( array( 'field' => 'last_name',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_participant_role' => array( array( 'field' => 'participant_role',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_country' => array( array( 'field' => 'country',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_facility' => array( array( 'field' => 'facility',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_phone' => array( array( 'field' => 'phone',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_email' => array( array( 'field' => 'email',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_training_id' => array( array( 'field' => 'training_id',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_training_name' => array( array( 'field' => 'training_name',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_program' => array( array( 'field' => 'program',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_partners' => array( array( 'field' => 'partners',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_training_type' => array( array( 'field' => 'training_type',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_training_approach' => array( array( 'field' => 'training_approach',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_training_language' => array( array( 'field' => 'training_language',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_training_lead' => array( array( 'field' => 'training_lead',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_quarter' => array( array( 'field' => 'quarter',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_start_date' => array( array( 'field' => 'start_date',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_end_date' => array( array( 'field' => 'end_date',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_total_days' => array( array( 'field' => 'total_days',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_days_recorded' => array( array( 'field' => 'days_recorded',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_days_attended' => array( array( 'field' => 'days_attended',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_attendance_percentage' => array( array( 'field' => 'attendance_percentage',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_attendance_status' => array( array( 'field' => 'attendance_status',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_pre_test_score' => array( array( 'field' => 'pre_test_score',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_post_test_score' => array( array( 'field' => 'post_test_score',
'table' => 'aio_training_tracking Chart' ) ),
'aio_training_tracking_Chart_ceu_points' => array( array( 'field' => 'ceu_points',
'table' => 'aio_training_tracking Chart' ) ) ),
'allSearchFields' => array( 'aio_training_tracking_gender',
'aio_training_tracking_participant_role',
'aio_training_tracking_country',
'aio_training_tracking_facility',
'aio_training_tracking_training_id',
'aio_training_tracking_training_name',
'aio_training_tracking_program',
'aio_training_tracking_partners',
'aio_training_tracking_training_type',
'aio_training_tracking_training_approach',
'aio_training_tracking_training_language',
'aio_training_tracking_training_lead',
'aio_training_tracking_quarter',
'aio_training_tracking_attendance_status',
'aio_training_tracking_Chart_gender',
'aio_training_tracking_participant_id',
'aio_training_tracking_title',
'aio_training_tracking_first_name',
'aio_training_tracking_middle_name',
'aio_training_tracking_last_name',
'aio_training_tracking_phone',
'aio_training_tracking_email',
'aio_training_tracking_start_date',
'aio_training_tracking_end_date',
'aio_training_tracking_total_days',
'aio_training_tracking_days_recorded',
'aio_training_tracking_days_attended',
'aio_training_tracking_attendance_percentage',
'aio_training_tracking_pre_test_score',
'aio_training_tracking_post_test_score',
'aio_training_tracking_ceu_points',
'aio_training_tracking_Chart_participant_id',
'aio_training_tracking_Chart_title',
'aio_training_tracking_Chart_first_name',
'aio_training_tracking_Chart_middle_name',
'aio_training_tracking_Chart_last_name',
'aio_training_tracking_Chart_participant_role',
'aio_training_tracking_Chart_country',
'aio_training_tracking_Chart_facility',
'aio_training_tracking_Chart_phone',
'aio_training_tracking_Chart_email',
'aio_training_tracking_Chart_training_id',
'aio_training_tracking_Chart_training_name',
'aio_training_tracking_Chart_program',
'aio_training_tracking_Chart_partners',
'aio_training_tracking_Chart_training_type',
'aio_training_tracking_Chart_training_approach',
'aio_training_tracking_Chart_training_language',
'aio_training_tracking_Chart_training_lead',
'aio_training_tracking_Chart_quarter',
'aio_training_tracking_Chart_start_date',
'aio_training_tracking_Chart_end_date',
'aio_training_tracking_Chart_total_days',
'aio_training_tracking_Chart_days_recorded',
'aio_training_tracking_Chart_days_attended',
'aio_training_tracking_Chart_attendance_percentage',
'aio_training_tracking_Chart_attendance_status',
'aio_training_tracking_Chart_pre_test_score',
'aio_training_tracking_Chart_post_test_score',
'aio_training_tracking_Chart_ceu_points' ),
'googleLikeFields' => array( 'aio_training_tracking_gender',
'aio_training_tracking_participant_role',
'aio_training_tracking_country',
'aio_training_tracking_facility',
'aio_training_tracking_training_id',
'aio_training_tracking_training_name',
'aio_training_tracking_program',
'aio_training_tracking_partners',
'aio_training_tracking_training_type',
'aio_training_tracking_training_approach',
'aio_training_tracking_training_language',
'aio_training_tracking_training_lead',
'aio_training_tracking_quarter',
'aio_training_tracking_attendance_status',
'aio_training_tracking_Chart_gender',
'aio_training_tracking_participant_id',
'aio_training_tracking_title',
'aio_training_tracking_first_name',
'aio_training_tracking_middle_name',
'aio_training_tracking_last_name',
'aio_training_tracking_phone',
'aio_training_tracking_email',
'aio_training_tracking_start_date',
'aio_training_tracking_end_date',
'aio_training_tracking_total_days',
'aio_training_tracking_days_recorded',
'aio_training_tracking_days_attended',
'aio_training_tracking_attendance_percentage',
'aio_training_tracking_pre_test_score',
'aio_training_tracking_post_test_score',
'aio_training_tracking_ceu_points',
'aio_training_tracking_Chart_participant_role',
'aio_training_tracking_Chart_country',
'aio_training_tracking_Chart_training_name' ) ) );
			$pageArray = array( 'id' => 'search',
'type' => 'search',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'search-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'search-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'search-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-search',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_search_field17',
'integrated_search_field14',
'integrated_search_field',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13' ) ) ),
'deferredItems' => array(  ),
'separateLabels' => false ) ),
'items' => array( 'search_header' => array( 'type' => 'search_header' ),
'search_reset' => array( 'type' => 'search_reset' ),
'search_back_list' => array( 'type' => 'search_back_list' ),
'search_search' => array( 'type' => 'search_search' ),
'search_cancel' => array( 'type' => 'search_cancel' ),
'integrated_search_field' => array( 'field' => 'aio_training_tracking_gender',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field1' => array( 'field' => 'aio_training_tracking_participant_role',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field2' => array( 'field' => 'aio_training_tracking_country',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field3' => array( 'field' => 'aio_training_tracking_facility',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field4' => array( 'field' => 'aio_training_tracking_training_id',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field5' => array( 'field' => 'aio_training_tracking_training_name',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field6' => array( 'field' => 'aio_training_tracking_program',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field7' => array( 'field' => 'aio_training_tracking_partners',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field8' => array( 'field' => 'aio_training_tracking_training_type',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field9' => array( 'field' => 'aio_training_tracking_training_approach',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field10' => array( 'field' => 'aio_training_tracking_training_language',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field11' => array( 'field' => 'aio_training_tracking_training_lead',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field12' => array( 'field' => 'aio_training_tracking_quarter',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field13' => array( 'field' => 'aio_training_tracking_attendance_status',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field14' => array( 'field' => 'aio_training_tracking_Chart_gender',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field15' => array( 'field' => 'aio_training_tracking_Chart_participant_role',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field16' => array( 'field' => 'aio_training_tracking_Chart_country',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field17' => array( 'field' => 'aio_training_tracking_Chart_training_name',
'type' => 'integrated_search_field',
'orientation' => 0 ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>