<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'follow_up_id',
'case_id',
'facility_id',
'phone_call_date',
'data_collector_name',
'call_successful',
'call_failure_reason',
'patient_status',
'neonatal_death',
'wound_opened',
'wound_drainage',
'drainage_type',
'visited_healthcare_provider',
'provider_location',
'scheduled_postop_visit',
'attended_postop_visit',
'missed_visit_reason',
'created_at',
'updated_at' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'follow_up_id' => array( 'import_field' ),
'case_id' => array( 'import_field1' ),
'facility_id' => array( 'import_field2' ),
'phone_call_date' => array( 'import_field3' ),
'data_collector_name' => array( 'import_field4' ),
'call_successful' => array( 'import_field5' ),
'call_failure_reason' => array( 'import_field6' ),
'patient_status' => array( 'import_field7' ),
'neonatal_death' => array( 'import_field8' ),
'wound_opened' => array( 'import_field9' ),
'wound_drainage' => array( 'import_field10' ),
'drainage_type' => array( 'import_field11' ),
'visited_healthcare_provider' => array( 'import_field12' ),
'provider_location' => array( 'import_field13' ),
'scheduled_postop_visit' => array( 'import_field14' ),
'attended_postop_visit' => array( 'import_field15' ),
'missed_visit_reason' => array( 'import_field16' ),
'created_at' => array( 'import_field17' ),
'updated_at' => array( 'import_field18' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'follow_up_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'case_id',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'facility_id',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'phone_call_date',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'data_collector_name',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'call_successful',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'call_failure_reason',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'patient_status',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'neonatal_death',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'wound_opened',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'wound_drainage',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'drainage_type',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'visited_healthcare_provider',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'provider_location',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'scheduled_postop_visit',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'attended_postop_visit',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'missed_visit_reason',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'created_at',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'updated_at',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>