<?php
			$optionsArray = array( 'totals' => array( 'program_id' => array( 'totalsType' => '' ),
'strategic_area_id' => array( 'totalsType' => '' ),
'key_objective' => array( 'totalsType' => '' ),
'activity' => array( 'totalsType' => '' ),
'kpi' => array( 'totalsType' => '' ),
'status_id' => array( 'totalsType' => '' ),
'planned_timeframe_q1' => array( 'totalsType' => '' ),
'planned_timeframe_q2' => array( 'totalsType' => '' ),
'planned_timeframe_q3' => array( 'totalsType' => '' ),
'planned_timeframe_q4' => array( 'totalsType' => '' ),
'achievement_q1' => array( 'totalsType' => '' ),
'achievement_q2' => array( 'totalsType' => '' ),
'achievement_q3' => array( 'totalsType' => '' ),
'achievement_q4' => array( 'totalsType' => '' ),
'notes' => array( 'totalsType' => '' ),
'created_at' => array( 'totalsType' => '' ),
'updated_at' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'program_id',
'strategic_area_id',
'key_objective',
'activity',
'kpi',
'status_id',
'planned_timeframe_q1',
'planned_timeframe_q2',
'planned_timeframe_q3',
'planned_timeframe_q4',
'achievement_q1',
'achievement_q2',
'achievement_q3',
'achievement_q4',
'notes',
'created_at',
'updated_at' ),
'exportFields' => array( 'program_id',
'strategic_area_id',
'key_objective',
'activity',
'kpi',
'status_id',
'planned_timeframe_q1',
'planned_timeframe_q2',
'planned_timeframe_q3',
'planned_timeframe_q4',
'achievement_q1',
'achievement_q2',
'achievement_q3',
'achievement_q4',
'notes',
'created_at',
'updated_at' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'program_id' => array( 'export_field' ),
'strategic_area_id' => array( 'export_field1' ),
'key_objective' => array( 'export_field2' ),
'activity' => array( 'export_field3' ),
'kpi' => array( 'export_field4' ),
'status_id' => array( 'export_field5' ),
'planned_timeframe_q1' => array( 'export_field6' ),
'planned_timeframe_q2' => array( 'export_field7' ),
'planned_timeframe_q3' => array( 'export_field8' ),
'planned_timeframe_q4' => array( 'export_field9' ),
'achievement_q1' => array( 'export_field10' ),
'achievement_q2' => array( 'export_field11' ),
'achievement_q3' => array( 'export_field12' ),
'achievement_q4' => array( 'export_field13' ),
'notes' => array( 'export_field14' ),
'created_at' => array( 'export_field15' ),
'updated_at' => array( 'export_field16' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'program_id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'strategic_area_id',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'key_objective',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'activity',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'kpi',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'status_id',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'planned_timeframe_q1',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'planned_timeframe_q2',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'planned_timeframe_q3',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'planned_timeframe_q4',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'achievement_q1',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'achievement_q2',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'achievement_q3',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'achievement_q4',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'notes',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'created_at',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'updated_at',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>