<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'spreadsheetMode' => false,
'reorderRows' => false,
'addToBottom' => false,
'delete' => false,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false,
'fieldFilter' => false,
'hideNumberOfRecords' => false ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'indicator_id' => array( 'totalsType' => '' ),
'result_area' => array( 'totalsType' => '' ),
'indicator_name' => array( 'totalsType' => '' ),
'indicator_description' => array( 'totalsType' => '' ),
'indicator_type' => array( 'totalsType' => '' ),
'unit_of_measurement' => array( 'totalsType' => '' ),
'formula' => array( 'totalsType' => '' ),
'reporting_frequency' => array( 'totalsType' => '' ),
'year' => array( 'totalsType' => '' ),
'baseline' => array( 'totalsType' => '' ),
'q1_target' => array( 'totalsType' => '' ),
'q2_target' => array( 'totalsType' => '' ),
'q3_target' => array( 'totalsType' => '' ),
'q4_target' => array( 'totalsType' => '' ),
'q1_actual' => array( 'totalsType' => '' ),
'q2_actual' => array( 'totalsType' => '' ),
'q3_actual' => array( 'totalsType' => '' ),
'q4_actual' => array( 'totalsType' => '' ),
'q1_calculated' => array( 'totalsType' => '' ),
'q2_calculated' => array( 'totalsType' => '' ),
'q3_calculated' => array( 'totalsType' => '' ),
'q4_calculated' => array( 'totalsType' => '' ),
'q1_combined' => array( 'totalsType' => '' ),
'q2_combined' => array( 'totalsType' => '' ),
'q3_combined' => array( 'totalsType' => '' ),
'q4_combined' => array( 'totalsType' => '' ),
'created_at' => array( 'totalsType' => '' ),
'updated_at' => array( 'totalsType' => '' ),
'actuals_updated_at' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'indicator_id',
'result_area',
'indicator_name',
'indicator_description',
'indicator_type',
'unit_of_measurement',
'formula',
'reporting_frequency',
'year',
'baseline',
'q1_target',
'q2_target',
'q3_target',
'q4_target',
'q1_actual',
'q2_actual',
'q3_actual',
'q4_actual',
'q1_calculated',
'q2_calculated',
'q3_calculated',
'q4_calculated',
'q1_combined',
'q2_combined',
'q3_combined',
'q4_combined',
'actuals_updated_at',
'created_at',
'updated_at' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'baseline',
'actuals_updated_at',
'q4_combined',
'q3_combined',
'q2_combined',
'q1_combined',
'year',
'updated_at',
'unit_of_measurement',
'result_area',
'reporting_frequency',
'q4_target',
'q4_calculated',
'q4_actual',
'q3_target',
'q3_calculated',
'q3_actual',
'q2_target',
'q2_calculated',
'q2_actual',
'q1_target',
'q1_calculated',
'q1_actual',
'indicator_type',
'indicator_name',
'indicator_id',
'indicator_description',
'formula',
'created_at' ),
'filterFields' => array(  ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'indicator_id' => array( 'simple_grid_field',
'simple_grid_field29' ),
'result_area' => array( 'simple_grid_field1',
'simple_grid_field30' ),
'indicator_name' => array( 'simple_grid_field2',
'simple_grid_field31' ),
'indicator_description' => array( 'simple_grid_field3',
'simple_grid_field32' ),
'indicator_type' => array( 'simple_grid_field4',
'simple_grid_field33' ),
'unit_of_measurement' => array( 'simple_grid_field5',
'simple_grid_field34' ),
'formula' => array( 'simple_grid_field6',
'simple_grid_field35' ),
'reporting_frequency' => array( 'simple_grid_field7',
'simple_grid_field36' ),
'year' => array( 'simple_grid_field8',
'simple_grid_field37' ),
'baseline' => array( 'simple_grid_field9',
'simple_grid_field38' ),
'q1_target' => array( 'simple_grid_field10',
'simple_grid_field39' ),
'q2_target' => array( 'simple_grid_field11',
'simple_grid_field40' ),
'q3_target' => array( 'simple_grid_field12',
'simple_grid_field41' ),
'q4_target' => array( 'simple_grid_field13',
'simple_grid_field42' ),
'q1_actual' => array( 'simple_grid_field14',
'simple_grid_field43' ),
'q2_actual' => array( 'simple_grid_field15',
'simple_grid_field44' ),
'q3_actual' => array( 'simple_grid_field16',
'simple_grid_field45' ),
'q4_actual' => array( 'simple_grid_field17',
'simple_grid_field46' ),
'q1_calculated' => array( 'simple_grid_field18',
'simple_grid_field47' ),
'q2_calculated' => array( 'simple_grid_field19',
'simple_grid_field48' ),
'q3_calculated' => array( 'simple_grid_field20',
'simple_grid_field49' ),
'q4_calculated' => array( 'simple_grid_field21',
'simple_grid_field50' ),
'q1_combined' => array( 'simple_grid_field24',
'simple_grid_field51' ),
'q2_combined' => array( 'simple_grid_field25',
'simple_grid_field52' ),
'q3_combined' => array( 'simple_grid_field26',
'simple_grid_field53' ),
'q4_combined' => array( 'simple_grid_field27',
'simple_grid_field54' ),
'actuals_updated_at' => array( 'simple_grid_field28',
'simple_grid_field55' ),
'created_at' => array( 'simple_grid_field22',
'simple_grid_field56' ),
'updated_at' => array( 'simple_grid_field23',
'simple_grid_field57' ) ),
'hideEmptyFields' => array(  ),
'fieldFilterFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => true ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'details_found',
'page_size',
'print_panel' ),
'below-grid' => array( 'pagination' ),
'left' => array( 'logo',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'top' => array(  ),
'grid' => array( 'simple_grid_field29',
'simple_grid_field',
'simple_grid_field30',
'simple_grid_field1',
'simple_grid_field31',
'simple_grid_field2',
'simple_grid_field32',
'simple_grid_field3',
'simple_grid_field33',
'simple_grid_field4',
'simple_grid_field34',
'simple_grid_field5',
'simple_grid_field35',
'simple_grid_field6',
'simple_grid_field36',
'simple_grid_field7',
'simple_grid_field37',
'simple_grid_field8',
'simple_grid_field38',
'simple_grid_field9',
'simple_grid_field39',
'simple_grid_field10',
'simple_grid_field40',
'simple_grid_field11',
'simple_grid_field41',
'simple_grid_field12',
'simple_grid_field42',
'simple_grid_field13',
'simple_grid_field43',
'simple_grid_field14',
'simple_grid_field44',
'simple_grid_field15',
'simple_grid_field45',
'simple_grid_field16',
'simple_grid_field46',
'simple_grid_field17',
'simple_grid_field47',
'simple_grid_field18',
'simple_grid_field48',
'simple_grid_field19',
'simple_grid_field49',
'simple_grid_field20',
'simple_grid_field50',
'simple_grid_field21',
'simple_grid_field51',
'simple_grid_field24',
'simple_grid_field52',
'simple_grid_field25',
'simple_grid_field53',
'simple_grid_field26',
'simple_grid_field54',
'simple_grid_field27',
'simple_grid_field55',
'simple_grid_field28',
'simple_grid_field56',
'simple_grid_field22',
'simple_grid_field57',
'simple_grid_field23',
'grid_checkbox_head',
'grid_checkbox' ) ),
'formXtTags' => array( 'above-grid' => array( 'details_found',
'recsPerPage',
'print_friendly' ),
'below-grid' => array( 'pagination' ),
'top' => array(  ) ),
'itemForms' => array( 'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'pagination' => 'below-grid',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'simple_grid_field29' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field34' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field37' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field38' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field39' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field40' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field41' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field42' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field43' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field44' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field45' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field46' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field47' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field48' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field49' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field50' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field51' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field52' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field53' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field54' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field55' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field56' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field57' => 'grid',
'simple_grid_field23' => 'grid',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid' ),
'itemLocations' => array( 'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field37' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field38' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field39' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field40' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field41' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field42' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field43' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field44' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field45' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field46' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field47' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field48' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'simple_grid_field49' => array( 'location' => 'grid',
'cellId' => 'headcell_field20' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'simple_grid_field50' => array( 'location' => 'grid',
'cellId' => 'headcell_field21' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'simple_grid_field51' => array( 'location' => 'grid',
'cellId' => 'headcell_field22' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_field22' ),
'simple_grid_field52' => array( 'location' => 'grid',
'cellId' => 'headcell_field23' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'simple_grid_field53' => array( 'location' => 'grid',
'cellId' => 'headcell_field24' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field24' ),
'simple_grid_field54' => array( 'location' => 'grid',
'cellId' => 'headcell_field25' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'cell_field25' ),
'simple_grid_field55' => array( 'location' => 'grid',
'cellId' => 'headcell_field26' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'cell_field26' ),
'simple_grid_field56' => array( 'location' => 'grid',
'cellId' => 'headcell_field27' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field27' ),
'simple_grid_field57' => array( 'location' => 'grid',
'cellId' => 'headcell_field28' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field28' ),
'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ) ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_menu_button' => 2,
'print_panel' => 5,
'expand_button' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'details_found' => array( 'details_found' ),
'search_panel' => array( 'search_panel' ),
'list_options' => array( 'list_options' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'search_panel_field' => array( 'search_panel_field',
'search_panel_field1',
'search_panel_field2',
'search_panel_field3',
'search_panel_field4',
'search_panel_field5',
'search_panel_field6',
'search_panel_field7',
'search_panel_field8',
'search_panel_field9',
'search_panel_field10',
'search_panel_field11',
'search_panel_field12',
'search_panel_field13',
'search_panel_field14',
'search_panel_field15',
'search_panel_field16',
'search_panel_field17',
'search_panel_field18',
'search_panel_field19',
'search_panel_field20',
'search_panel_field21',
'search_panel_field22',
'search_panel_field23',
'search_panel_field24',
'search_panel_field25',
'search_panel_field26',
'search_panel_field27',
'search_panel_field28' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'export' => array( 'export' ),
'-' => array( '-',
'-1',
'-2' ),
'advsearch_link' => array( 'advsearch_link' ),
'grid_field' => array( 'simple_grid_field',
'simple_grid_field1',
'simple_grid_field2',
'simple_grid_field3',
'simple_grid_field4',
'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field7',
'simple_grid_field8',
'simple_grid_field9',
'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field12',
'simple_grid_field13',
'simple_grid_field14',
'simple_grid_field15',
'simple_grid_field16',
'simple_grid_field17',
'simple_grid_field18',
'simple_grid_field19',
'simple_grid_field20',
'simple_grid_field21',
'simple_grid_field24',
'simple_grid_field25',
'simple_grid_field26',
'simple_grid_field27',
'simple_grid_field28',
'simple_grid_field22',
'simple_grid_field23' ),
'grid_field_label' => array( 'simple_grid_field29',
'simple_grid_field30',
'simple_grid_field31',
'simple_grid_field32',
'simple_grid_field33',
'simple_grid_field34',
'simple_grid_field35',
'simple_grid_field36',
'simple_grid_field37',
'simple_grid_field38',
'simple_grid_field39',
'simple_grid_field40',
'simple_grid_field41',
'simple_grid_field42',
'simple_grid_field43',
'simple_grid_field44',
'simple_grid_field45',
'simple_grid_field46',
'simple_grid_field47',
'simple_grid_field48',
'simple_grid_field49',
'simple_grid_field50',
'simple_grid_field51',
'simple_grid_field52',
'simple_grid_field53',
'simple_grid_field54',
'simple_grid_field55',
'simple_grid_field56',
'simple_grid_field57' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_checkbox' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'indicator_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'result_area_fieldheadercolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'indicator_name_fieldheadercolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'indicator_description_fieldheadercolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'indicator_type_fieldheadercolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'unit_of_measurement_fieldheadercolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'formula_fieldheadercolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'reporting_frequency_fieldheadercolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'year_fieldheadercolumn' ),
'items' => array( 'simple_grid_field37' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'baseline_fieldheadercolumn' ),
'items' => array( 'simple_grid_field38' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'q1_target_fieldheadercolumn' ),
'items' => array( 'simple_grid_field39' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'q2_target_fieldheadercolumn' ),
'items' => array( 'simple_grid_field40' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'q3_target_fieldheadercolumn' ),
'items' => array( 'simple_grid_field41' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'q4_target_fieldheadercolumn' ),
'items' => array( 'simple_grid_field42' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'q1_actual_fieldheadercolumn' ),
'items' => array( 'simple_grid_field43' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'q2_actual_fieldheadercolumn' ),
'items' => array( 'simple_grid_field44' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'q3_actual_fieldheadercolumn' ),
'items' => array( 'simple_grid_field45' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'q4_actual_fieldheadercolumn' ),
'items' => array( 'simple_grid_field46' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array( 'q1_calculated_fieldheadercolumn' ),
'items' => array( 'simple_grid_field47' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 20 ),
'rows' => array( 0 ),
'tags' => array( 'q2_calculated_fieldheadercolumn' ),
'items' => array( 'simple_grid_field48' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field20' => array( 'cols' => array( 21 ),
'rows' => array( 0 ),
'tags' => array( 'q3_calculated_fieldheadercolumn' ),
'items' => array( 'simple_grid_field49' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field21' => array( 'cols' => array( 22 ),
'rows' => array( 0 ),
'tags' => array( 'q4_calculated_fieldheadercolumn' ),
'items' => array( 'simple_grid_field50' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field22' => array( 'cols' => array( 23 ),
'rows' => array( 0 ),
'tags' => array( 'q1_combined_fieldheadercolumn' ),
'items' => array( 'simple_grid_field51' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field23' => array( 'cols' => array( 24 ),
'rows' => array( 0 ),
'tags' => array( 'q2_combined_fieldheadercolumn' ),
'items' => array( 'simple_grid_field52' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field24' => array( 'cols' => array( 25 ),
'rows' => array( 0 ),
'tags' => array( 'q3_combined_fieldheadercolumn' ),
'items' => array( 'simple_grid_field53' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field25' => array( 'cols' => array( 26 ),
'rows' => array( 0 ),
'tags' => array( 'q4_combined_fieldheadercolumn' ),
'items' => array( 'simple_grid_field54' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field26' => array( 'cols' => array( 27 ),
'rows' => array( 0 ),
'tags' => array( 'actuals_updated_at_fieldheadercolumn' ),
'items' => array( 'simple_grid_field55' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field27' => array( 'cols' => array( 28 ),
'rows' => array( 0 ),
'tags' => array( 'created_at_fieldheadercolumn' ),
'items' => array( 'simple_grid_field56' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field28' => array( 'cols' => array( 29 ),
'rows' => array( 0 ),
'tags' => array( 'updated_at_fieldheadercolumn' ),
'items' => array( 'simple_grid_field57' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_checkbox' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'indicator_id_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'result_area_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'indicator_name_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'indicator_description_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'indicator_type_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'unit_of_measurement_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'formula_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'reporting_frequency_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'year_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'baseline_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'q1_target_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'q2_target_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'q3_target_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'q4_target_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'q1_actual_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'q2_actual_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'q3_actual_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'q4_actual_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'q1_calculated_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 20 ),
'rows' => array( 1 ),
'tags' => array( 'q2_calculated_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 21 ),
'rows' => array( 1 ),
'tags' => array( 'q3_calculated_fieldcolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 22 ),
'rows' => array( 1 ),
'tags' => array( 'q4_calculated_fieldcolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 23 ),
'rows' => array( 1 ),
'tags' => array( 'q1_combined_fieldcolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 24 ),
'rows' => array( 1 ),
'tags' => array( 'q2_combined_fieldcolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 25 ),
'rows' => array( 1 ),
'tags' => array( 'q3_combined_fieldcolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 26 ),
'rows' => array( 1 ),
'tags' => array( 'q4_combined_fieldcolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field26' => array( 'cols' => array( 27 ),
'rows' => array( 1 ),
'tags' => array( 'actuals_updated_at_fieldcolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field27' => array( 'cols' => array( 28 ),
'rows' => array( 1 ),
'tags' => array( 'created_at_fieldcolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 29 ),
'rows' => array( 1 ),
'tags' => array( 'updated_at_fieldcolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 18 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 19 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 20 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field20' => array( 'cols' => array( 21 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field21' => array( 'cols' => array( 22 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field22' => array( 'cols' => array( 23 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field23' => array( 'cols' => array( 24 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field24' => array( 'cols' => array( 25 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field25' => array( 'cols' => array( 26 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field26' => array( 'cols' => array( 27 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field27' => array( 'cols' => array( 28 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field28' => array( 'cols' => array( 29 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 30,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field19' ),
array( 'cell' => 'headcell_field20' ),
array( 'cell' => 'headcell_field21' ),
array( 'cell' => 'headcell_field22' ),
array( 'cell' => 'headcell_field23' ),
array( 'cell' => 'headcell_field24' ),
array( 'cell' => 'headcell_field25' ),
array( 'cell' => 'headcell_field26' ),
array( 'cell' => 'headcell_field27' ),
array( 'cell' => 'headcell_field28' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_field22' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'cell_field24' ),
array( 'cell' => 'cell_field25' ),
array( 'cell' => 'cell_field26' ),
array( 'cell' => 'cell_field27' ),
array( 'cell' => 'cell_field28' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_checkbox' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field19' ),
array( 'cell' => 'footcell_field20' ),
array( 'cell' => 'footcell_field21' ),
array( 'cell' => 'footcell_field22' ),
array( 'cell' => 'footcell_field23' ),
array( 'cell' => 'footcell_field24' ),
array( 'cell' => 'footcell_field25' ),
array( 'cell' => 'footcell_field26' ),
array( 'cell' => 'footcell_field27' ),
array( 'cell' => 'footcell_field28' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'indicator_id',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'indicator_id',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'result_area',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'result_area',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field31' ),
'field' => 'indicator_name',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'indicator_name',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field32' ),
'field' => 'indicator_description',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'indicator_description',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field33' ),
'field' => 'indicator_type',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'indicator_type',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field34' ),
'field' => 'unit_of_measurement',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'unit_of_measurement',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field35' ),
'field' => 'formula',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'formula',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field36' ),
'field' => 'reporting_frequency',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'reporting_frequency',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field37' ),
'field' => 'year',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'year',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field38' ),
'field' => 'baseline',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'baseline',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field39' ),
'field' => 'q1_target',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'q1_target',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field40' ),
'field' => 'q2_target',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'q2_target',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field41' ),
'field' => 'q3_target',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'q3_target',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field42' ),
'field' => 'q4_target',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'q4_target',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field43' ),
'field' => 'q1_actual',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'q1_actual',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field44' ),
'field' => 'q2_actual',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'q2_actual',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field45' ),
'field' => 'q3_actual',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'q3_actual',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field46' ),
'field' => 'q4_actual',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'q4_actual',
'columnName' => 'field' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field47' ),
'field' => 'q1_calculated',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'q1_calculated',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field19' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field48' ),
'field' => 'q2_calculated',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'q2_calculated',
'columnName' => 'field' ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field20' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field49' ),
'field' => 'q3_calculated',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'q3_calculated',
'columnName' => 'field' ),
'footcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field21' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field50' ),
'field' => 'q4_calculated',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'q4_calculated',
'columnName' => 'field' ),
'footcell_field21' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field22' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field51' ),
'field' => 'q1_combined',
'columnName' => 'field' ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'q1_combined',
'columnName' => 'field' ),
'footcell_field22' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field23' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field52' ),
'field' => 'q2_combined',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field25' ),
'field' => 'q2_combined',
'columnName' => 'field' ),
'footcell_field23' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field24' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field53' ),
'field' => 'q3_combined',
'columnName' => 'field' ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'q3_combined',
'columnName' => 'field' ),
'footcell_field24' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field25' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field54' ),
'field' => 'q4_combined',
'columnName' => 'field' ),
'cell_field25' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'q4_combined',
'columnName' => 'field' ),
'footcell_field25' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field26' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field55' ),
'field' => 'actuals_updated_at',
'columnName' => 'field' ),
'cell_field26' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'actuals_updated_at',
'columnName' => 'field' ),
'footcell_field26' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field27' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field56' ),
'field' => 'created_at',
'columnName' => 'field' ),
'cell_field27' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'created_at',
'columnName' => 'field' ),
'footcell_field27' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field28' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field57' ),
'field' => 'updated_at',
'columnName' => 'field' ),
'cell_field28' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'updated_at',
'columnName' => 'field' ),
'footcell_field28' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ) ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ) ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'details_found' => array( 'type' => 'details_found' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field',
'search_panel_field28',
'search_panel_field27',
'search_panel_field26',
'search_panel_field25',
'search_panel_field24',
'search_panel_field23',
'search_panel_field22',
'search_panel_field21',
'search_panel_field20',
'search_panel_field19',
'search_panel_field18',
'search_panel_field17',
'search_panel_field16',
'search_panel_field15',
'search_panel_field14',
'search_panel_field13',
'search_panel_field12',
'search_panel_field11',
'search_panel_field10',
'search_panel_field9',
'search_panel_field8',
'search_panel_field7',
'search_panel_field6',
'search_panel_field5',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1' ) ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-2',
'export' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field' => array( 'field' => 'baseline',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field1' => array( 'field' => 'created_at',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field2' => array( 'field' => 'formula',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field3' => array( 'field' => 'indicator_description',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field4' => array( 'field' => 'indicator_id',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field5' => array( 'field' => 'indicator_name',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field6' => array( 'field' => 'indicator_type',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field7' => array( 'field' => 'q1_actual',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field8' => array( 'field' => 'q1_calculated',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field9' => array( 'field' => 'q1_target',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field10' => array( 'field' => 'q2_actual',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field11' => array( 'field' => 'q2_calculated',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field12' => array( 'field' => 'q2_target',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field13' => array( 'field' => 'q3_actual',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field14' => array( 'field' => 'q3_calculated',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field15' => array( 'field' => 'q3_target',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field16' => array( 'field' => 'q4_actual',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field17' => array( 'field' => 'q4_calculated',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field18' => array( 'field' => 'q4_target',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field19' => array( 'field' => 'reporting_frequency',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field20' => array( 'field' => 'result_area',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field21' => array( 'field' => 'unit_of_measurement',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field22' => array( 'field' => 'updated_at',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field23' => array( 'field' => 'year',
'type' => 'search_panel_field',
'required' => false ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'export' => array( 'type' => 'export' ),
'-' => array( 'type' => '-' ),
'-1' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'-2' => array( 'type' => '-' ),
'search_panel_field24' => array( 'field' => 'q1_combined',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field25' => array( 'field' => 'q2_combined',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field26' => array( 'field' => 'q3_combined',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field27' => array( 'field' => 'q4_combined',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field28' => array( 'field' => 'actuals_updated_at',
'type' => 'search_panel_field',
'required' => false ),
'simple_grid_field' => array( 'field' => 'indicator_id',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field29' => array( 'type' => 'grid_field_label',
'field' => 'indicator_id' ),
'simple_grid_field1' => array( 'field' => 'result_area',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field30' => array( 'type' => 'grid_field_label',
'field' => 'result_area' ),
'simple_grid_field2' => array( 'field' => 'indicator_name',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field31' => array( 'type' => 'grid_field_label',
'field' => 'indicator_name' ),
'simple_grid_field3' => array( 'field' => 'indicator_description',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field32' => array( 'type' => 'grid_field_label',
'field' => 'indicator_description' ),
'simple_grid_field4' => array( 'field' => 'indicator_type',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field33' => array( 'type' => 'grid_field_label',
'field' => 'indicator_type' ),
'simple_grid_field5' => array( 'field' => 'unit_of_measurement',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field34' => array( 'type' => 'grid_field_label',
'field' => 'unit_of_measurement' ),
'simple_grid_field6' => array( 'field' => 'formula',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field35' => array( 'type' => 'grid_field_label',
'field' => 'formula' ),
'simple_grid_field7' => array( 'field' => 'reporting_frequency',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field36' => array( 'type' => 'grid_field_label',
'field' => 'reporting_frequency' ),
'simple_grid_field8' => array( 'field' => 'year',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field37' => array( 'type' => 'grid_field_label',
'field' => 'year' ),
'simple_grid_field9' => array( 'field' => 'baseline',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field38' => array( 'type' => 'grid_field_label',
'field' => 'baseline' ),
'simple_grid_field10' => array( 'field' => 'q1_target',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field39' => array( 'type' => 'grid_field_label',
'field' => 'q1_target' ),
'simple_grid_field11' => array( 'field' => 'q2_target',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field40' => array( 'type' => 'grid_field_label',
'field' => 'q2_target' ),
'simple_grid_field12' => array( 'field' => 'q3_target',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field41' => array( 'type' => 'grid_field_label',
'field' => 'q3_target' ),
'simple_grid_field13' => array( 'field' => 'q4_target',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field42' => array( 'type' => 'grid_field_label',
'field' => 'q4_target' ),
'simple_grid_field14' => array( 'field' => 'q1_actual',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field43' => array( 'type' => 'grid_field_label',
'field' => 'q1_actual' ),
'simple_grid_field15' => array( 'field' => 'q2_actual',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field44' => array( 'type' => 'grid_field_label',
'field' => 'q2_actual' ),
'simple_grid_field16' => array( 'field' => 'q3_actual',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field45' => array( 'type' => 'grid_field_label',
'field' => 'q3_actual' ),
'simple_grid_field17' => array( 'field' => 'q4_actual',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field46' => array( 'type' => 'grid_field_label',
'field' => 'q4_actual' ),
'simple_grid_field18' => array( 'field' => 'q1_calculated',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field47' => array( 'type' => 'grid_field_label',
'field' => 'q1_calculated' ),
'simple_grid_field19' => array( 'field' => 'q2_calculated',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field48' => array( 'type' => 'grid_field_label',
'field' => 'q2_calculated' ),
'simple_grid_field20' => array( 'field' => 'q3_calculated',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field49' => array( 'type' => 'grid_field_label',
'field' => 'q3_calculated' ),
'simple_grid_field21' => array( 'field' => 'q4_calculated',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field50' => array( 'type' => 'grid_field_label',
'field' => 'q4_calculated' ),
'simple_grid_field24' => array( 'field' => 'q1_combined',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field51' => array( 'type' => 'grid_field_label',
'field' => 'q1_combined' ),
'simple_grid_field25' => array( 'field' => 'q2_combined',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field52' => array( 'type' => 'grid_field_label',
'field' => 'q2_combined' ),
'simple_grid_field26' => array( 'field' => 'q3_combined',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field53' => array( 'type' => 'grid_field_label',
'field' => 'q3_combined' ),
'simple_grid_field27' => array( 'field' => 'q4_combined',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field54' => array( 'type' => 'grid_field_label',
'field' => 'q4_combined' ),
'simple_grid_field28' => array( 'field' => 'actuals_updated_at',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field55' => array( 'type' => 'grid_field_label',
'field' => 'actuals_updated_at' ),
'simple_grid_field22' => array( 'field' => 'created_at',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field56' => array( 'type' => 'grid_field_label',
'field' => 'created_at' ),
'simple_grid_field23' => array( 'field' => 'updated_at',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field57' => array( 'type' => 'grid_field_label',
'field' => 'updated_at' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'spreadsheetGrid' => false,
'version' => 14,
'reorderRows' => false,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>