<?php
			$optionsArray = array( 'totals' => array( 'indicator_id' => array( 'totalsType' => '' ),
'result_area' => array( 'totalsType' => '' ),
'indicator_name' => array( 'totalsType' => '' ),
'indicator_description' => array( 'totalsType' => '' ),
'indicator_type' => array( 'totalsType' => '' ),
'unit_of_measurement' => array( 'totalsType' => '' ),
'formula' => array( 'totalsType' => '' ),
'reporting_frequency' => array( 'totalsType' => '' ),
'year' => array( 'totalsType' => '' ),
'baseline' => array( 'totalsType' => '' ),
'q1_target' => array( 'totalsType' => '' ),
'q2_target' => array( 'totalsType' => '' ),
'q3_target' => array( 'totalsType' => '' ),
'q4_target' => array( 'totalsType' => '' ),
'q1_actual' => array( 'totalsType' => '' ),
'q2_actual' => array( 'totalsType' => '' ),
'q3_actual' => array( 'totalsType' => '' ),
'q4_actual' => array( 'totalsType' => '' ),
'q1_calculated' => array( 'totalsType' => '' ),
'q2_calculated' => array( 'totalsType' => '' ),
'q3_calculated' => array( 'totalsType' => '' ),
'q4_calculated' => array( 'totalsType' => '' ),
'q1_combined' => array( 'totalsType' => '' ),
'q2_combined' => array( 'totalsType' => '' ),
'q3_combined' => array( 'totalsType' => '' ),
'q4_combined' => array( 'totalsType' => '' ),
'created_at' => array( 'totalsType' => '' ),
'updated_at' => array( 'totalsType' => '' ),
'actuals_updated_at' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'indicator_id',
'result_area',
'indicator_name',
'indicator_description',
'indicator_type',
'unit_of_measurement',
'formula',
'reporting_frequency',
'year',
'baseline',
'q1_target',
'q2_target',
'q3_target',
'q4_target',
'q1_actual',
'q2_actual',
'q3_actual',
'q4_actual',
'q1_calculated',
'q2_calculated',
'q3_calculated',
'q4_calculated',
'created_at',
'updated_at',
'q1_combined',
'q2_combined',
'q3_combined',
'q4_combined',
'actuals_updated_at' ),
'exportFields' => array( 'indicator_id',
'result_area',
'indicator_name',
'indicator_description',
'indicator_type',
'unit_of_measurement',
'formula',
'reporting_frequency',
'year',
'baseline',
'q1_target',
'q2_target',
'q3_target',
'q4_target',
'q1_actual',
'q2_actual',
'q3_actual',
'q4_actual',
'q1_calculated',
'q2_calculated',
'q3_calculated',
'q4_calculated',
'q1_combined',
'q2_combined',
'q3_combined',
'q4_combined',
'actuals_updated_at',
'created_at',
'updated_at' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'indicator_id' => array( 'export_field' ),
'result_area' => array( 'export_field1' ),
'indicator_name' => array( 'export_field2' ),
'indicator_description' => array( 'export_field3' ),
'indicator_type' => array( 'export_field4' ),
'unit_of_measurement' => array( 'export_field5' ),
'formula' => array( 'export_field6' ),
'reporting_frequency' => array( 'export_field7' ),
'year' => array( 'export_field8' ),
'baseline' => array( 'export_field9' ),
'q1_target' => array( 'export_field10' ),
'q2_target' => array( 'export_field11' ),
'q3_target' => array( 'export_field12' ),
'q4_target' => array( 'export_field13' ),
'q1_actual' => array( 'export_field14' ),
'q2_actual' => array( 'export_field15' ),
'q3_actual' => array( 'export_field16' ),
'q4_actual' => array( 'export_field17' ),
'q1_calculated' => array( 'export_field18' ),
'q2_calculated' => array( 'export_field19' ),
'q3_calculated' => array( 'export_field20' ),
'q4_calculated' => array( 'export_field21' ),
'created_at' => array( 'export_field22' ),
'updated_at' => array( 'export_field23' ),
'q1_combined' => array( 'export_field24' ),
'q2_combined' => array( 'export_field25' ),
'q3_combined' => array( 'export_field26' ),
'q4_combined' => array( 'export_field27' ),
'actuals_updated_at' => array( 'export_field28' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field22',
'export_field23' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field22',
'export_field23' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'indicator_id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'result_area',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'indicator_name',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'indicator_description',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'indicator_type',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'unit_of_measurement',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'formula',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'reporting_frequency',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'year',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'baseline',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'q1_target',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'q2_target',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'q3_target',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'q4_target',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'q1_actual',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'q2_actual',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'q3_actual',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'q4_actual',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'q1_calculated',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'q2_calculated',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'q3_calculated',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'q4_calculated',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'created_at',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'updated_at',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'q1_combined',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'q2_combined',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'q3_combined',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'q4_combined',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'actuals_updated_at',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>