<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'totals' => array( 'indicator_group_id' => array( 'totalsType' => '' ),
'indicator_group_name' => array( 'totalsType' => '' ),
'indicator_group_code' => array( 'totalsType' => '' ),
'indicator_id' => array( 'totalsType' => '' ),
'indicator_name' => array( 'totalsType' => '' ),
'indicator_code' => array( 'totalsType' => '' ),
'indicator_type' => array( 'totalsType' => '' ),
'formula' => array( 'totalsType' => '' ),
'period_type' => array( 'totalsType' => '' ),
'period_year' => array( 'totalsType' => '' ),
'period_quarter' => array( 'totalsType' => '' ),
'period_month' => array( 'totalsType' => '' ),
'region_id' => array( 'totalsType' => '' ),
'region_name' => array( 'totalsType' => '' ),
'country_id' => array( 'totalsType' => '' ),
'country_name' => array( 'totalsType' => '' ),
'facility_id' => array( 'totalsType' => '' ),
'facility_name' => array( 'totalsType' => '' ),
'actual_value' => array( 'totalsType' => '' ),
'target_value' => array( 'totalsType' => '' ),
'variance' => array( 'totalsType' => '' ),
'variance_percentage' => array( 'totalsType' => '' ),
'calculation_timestamp' => array( 'totalsType' => '' ),
'is_calculated' => array( 'totalsType' => '' ),
'decimals' => array( 'totalsType' => '' ),
'annualized' => array( 'totalsType' => '' ),
'data_completeness' => array( 'totalsType' => '' ),
'overall_completion_percentage' => array( 'totalsType' => '' ),
'actual_value_completion' => array( 'totalsType' => '' ),
'target_value_completion' => array( 'totalsType' => '' ),
'completion_status' => array( 'totalsType' => '' ),
'is_actual_missing' => array( 'totalsType' => '' ),
'is_target_missing' => array( 'totalsType' => '' ),
'data_freshness' => array( 'totalsType' => '' ),
'days_since_last_calculation' => array( 'totalsType' => '' ),
'performance_status' => array( 'totalsType' => '' ),
'performance_percentage' => array( 'totalsType' => '' ),
'data_quality_flag' => array( 'totalsType' => '' ),
'data_hierarchy_level' => array( 'totalsType' => '' ),
'period_completeness' => array( 'totalsType' => '' ),
'calculation_method' => array( 'totalsType' => '' ),
'formula_type' => array( 'totalsType' => '' ),
'org_unit_validity' => array( 'totalsType' => '' ),
'period_validity' => array( 'totalsType' => '' ),
'legacy_performance_status' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'indicator_group_id',
'indicator_group_name',
'indicator_group_code',
'indicator_id',
'indicator_name',
'indicator_type',
'formula',
'indicator_code',
'period_type',
'period_year',
'period_quarter',
'period_month',
'region_id',
'region_name',
'country_id',
'country_name',
'facility_id',
'facility_name',
'actual_value',
'target_value',
'variance',
'variance_percentage',
'calculation_timestamp',
'is_calculated',
'decimals',
'annualized',
'data_completeness',
'performance_status',
'overall_completion_percentage',
'actual_value_completion',
'target_value_completion',
'completion_status',
'is_actual_missing',
'is_target_missing',
'data_freshness',
'days_since_last_calculation',
'performance_percentage',
'data_quality_flag',
'data_hierarchy_level',
'period_completeness',
'calculation_method',
'formula_type',
'org_unit_validity',
'period_validity',
'legacy_performance_status' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'indicator_group_id' => array( 'simple_grid_field42',
'simple_grid_field45' ),
'indicator_group_name' => array( 'simple_grid_field44',
'simple_grid_field46' ),
'indicator_group_code' => array( 'simple_grid_field43',
'simple_grid_field47' ),
'indicator_id' => array( 'simple_grid_field',
'simple_grid_field48' ),
'indicator_name' => array( 'simple_grid_field2',
'simple_grid_field49' ),
'indicator_type' => array( 'simple_grid_field4',
'simple_grid_field50' ),
'formula' => array( 'simple_grid_field6',
'simple_grid_field51' ),
'indicator_code' => array( 'simple_grid_field1',
'simple_grid_field52' ),
'period_type' => array( 'simple_grid_field3',
'simple_grid_field53' ),
'period_year' => array( 'simple_grid_field5',
'simple_grid_field54' ),
'period_quarter' => array( 'simple_grid_field7',
'simple_grid_field55' ),
'period_month' => array( 'simple_grid_field8',
'simple_grid_field56' ),
'region_id' => array( 'simple_grid_field9',
'simple_grid_field57' ),
'region_name' => array( 'simple_grid_field10',
'simple_grid_field58' ),
'country_id' => array( 'simple_grid_field11',
'simple_grid_field59' ),
'country_name' => array( 'simple_grid_field12',
'simple_grid_field60' ),
'facility_id' => array( 'simple_grid_field13',
'simple_grid_field61' ),
'facility_name' => array( 'simple_grid_field14',
'simple_grid_field62' ),
'actual_value' => array( 'simple_grid_field15',
'simple_grid_field63' ),
'target_value' => array( 'simple_grid_field16',
'simple_grid_field64' ),
'variance' => array( 'simple_grid_field17',
'simple_grid_field65' ),
'variance_percentage' => array( 'simple_grid_field18',
'simple_grid_field66' ),
'calculation_timestamp' => array( 'simple_grid_field19',
'simple_grid_field67' ),
'is_calculated' => array( 'simple_grid_field20',
'simple_grid_field68' ),
'decimals' => array( 'simple_grid_field21',
'simple_grid_field69' ),
'annualized' => array( 'simple_grid_field22',
'simple_grid_field70' ),
'data_completeness' => array( 'simple_grid_field23',
'simple_grid_field71' ),
'performance_status' => array( 'simple_grid_field24',
'simple_grid_field72' ),
'overall_completion_percentage' => array( 'simple_grid_field25',
'simple_grid_field73' ),
'actual_value_completion' => array( 'simple_grid_field26',
'simple_grid_field74' ),
'target_value_completion' => array( 'simple_grid_field27',
'simple_grid_field75' ),
'completion_status' => array( 'simple_grid_field28',
'simple_grid_field76' ),
'is_actual_missing' => array( 'simple_grid_field29',
'simple_grid_field77' ),
'is_target_missing' => array( 'simple_grid_field30',
'simple_grid_field78' ),
'data_freshness' => array( 'simple_grid_field31',
'simple_grid_field79' ),
'days_since_last_calculation' => array( 'simple_grid_field32',
'simple_grid_field80' ),
'performance_percentage' => array( 'simple_grid_field33',
'simple_grid_field81' ),
'data_quality_flag' => array( 'simple_grid_field34',
'simple_grid_field82' ),
'data_hierarchy_level' => array( 'simple_grid_field35',
'simple_grid_field83' ),
'period_completeness' => array( 'simple_grid_field36',
'simple_grid_field84' ),
'calculation_method' => array( 'simple_grid_field37',
'simple_grid_field85' ),
'formula_type' => array( 'simple_grid_field38',
'simple_grid_field86' ),
'org_unit_validity' => array( 'simple_grid_field39',
'simple_grid_field87' ),
'period_validity' => array( 'simple_grid_field40',
'simple_grid_field88' ),
'legacy_performance_status' => array( 'simple_grid_field41',
'simple_grid_field89' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ),
'top' => array( 'print_header',
'print_subheader' ),
'grid' => array( 'simple_grid_field45',
'simple_grid_field42',
'simple_grid_field46',
'simple_grid_field44',
'simple_grid_field47',
'simple_grid_field43',
'simple_grid_field48',
'simple_grid_field',
'simple_grid_field49',
'simple_grid_field2',
'simple_grid_field50',
'simple_grid_field4',
'simple_grid_field51',
'simple_grid_field6',
'simple_grid_field52',
'simple_grid_field1',
'simple_grid_field53',
'simple_grid_field3',
'simple_grid_field54',
'simple_grid_field5',
'simple_grid_field55',
'simple_grid_field7',
'simple_grid_field56',
'simple_grid_field8',
'simple_grid_field57',
'simple_grid_field9',
'simple_grid_field58',
'simple_grid_field10',
'simple_grid_field59',
'simple_grid_field11',
'simple_grid_field60',
'simple_grid_field12',
'simple_grid_field61',
'simple_grid_field13',
'simple_grid_field62',
'simple_grid_field14',
'simple_grid_field63',
'simple_grid_field15',
'simple_grid_field64',
'simple_grid_field16',
'simple_grid_field65',
'simple_grid_field17',
'simple_grid_field66',
'simple_grid_field18',
'simple_grid_field67',
'simple_grid_field19',
'simple_grid_field68',
'simple_grid_field20',
'simple_grid_field69',
'simple_grid_field21',
'simple_grid_field70',
'simple_grid_field22',
'simple_grid_field71',
'simple_grid_field23',
'simple_grid_field72',
'simple_grid_field24',
'simple_grid_field73',
'simple_grid_field25',
'simple_grid_field74',
'simple_grid_field26',
'simple_grid_field75',
'simple_grid_field27',
'simple_grid_field76',
'simple_grid_field28',
'simple_grid_field77',
'simple_grid_field29',
'simple_grid_field78',
'simple_grid_field30',
'simple_grid_field79',
'simple_grid_field31',
'simple_grid_field80',
'simple_grid_field32',
'simple_grid_field81',
'simple_grid_field33',
'simple_grid_field82',
'simple_grid_field34',
'simple_grid_field83',
'simple_grid_field35',
'simple_grid_field84',
'simple_grid_field36',
'simple_grid_field85',
'simple_grid_field37',
'simple_grid_field86',
'simple_grid_field38',
'simple_grid_field87',
'simple_grid_field39',
'simple_grid_field88',
'simple_grid_field40',
'simple_grid_field89',
'simple_grid_field41' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_pages' => 'above-grid',
'print_header' => 'top',
'print_subheader' => 'top',
'simple_grid_field45' => 'grid',
'simple_grid_field42' => 'grid',
'simple_grid_field46' => 'grid',
'simple_grid_field44' => 'grid',
'simple_grid_field47' => 'grid',
'simple_grid_field43' => 'grid',
'simple_grid_field48' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field49' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field50' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field51' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field52' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field53' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field54' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field55' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field56' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field57' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field58' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field59' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field60' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field61' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field62' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field63' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field64' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field65' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field66' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field67' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field68' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field69' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field70' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field71' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field72' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field73' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field74' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field75' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field76' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field77' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field78' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field79' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field80' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field81' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field82' => 'grid',
'simple_grid_field34' => 'grid',
'simple_grid_field83' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field84' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field85' => 'grid',
'simple_grid_field37' => 'grid',
'simple_grid_field86' => 'grid',
'simple_grid_field38' => 'grid',
'simple_grid_field87' => 'grid',
'simple_grid_field39' => 'grid',
'simple_grid_field88' => 'grid',
'simple_grid_field40' => 'grid',
'simple_grid_field89' => 'grid',
'simple_grid_field41' => 'grid' ),
'itemLocations' => array( 'simple_grid_field45' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field42' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field46' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field44' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field47' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field43' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field48' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field49' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field50' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field51' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field52' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field53' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field54' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field55' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field56' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field57' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field58' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field59' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field60' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field61' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field62' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field63' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field64' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'simple_grid_field65' => array( 'location' => 'grid',
'cellId' => 'headcell_field20' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'simple_grid_field66' => array( 'location' => 'grid',
'cellId' => 'headcell_field21' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'simple_grid_field67' => array( 'location' => 'grid',
'cellId' => 'headcell_field22' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field22' ),
'simple_grid_field68' => array( 'location' => 'grid',
'cellId' => 'headcell_field23' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'simple_grid_field69' => array( 'location' => 'grid',
'cellId' => 'headcell_field24' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field24' ),
'simple_grid_field70' => array( 'location' => 'grid',
'cellId' => 'headcell_field25' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field25' ),
'simple_grid_field71' => array( 'location' => 'grid',
'cellId' => 'headcell_field26' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field26' ),
'simple_grid_field72' => array( 'location' => 'grid',
'cellId' => 'headcell_field27' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_field27' ),
'simple_grid_field73' => array( 'location' => 'grid',
'cellId' => 'headcell_field28' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'cell_field28' ),
'simple_grid_field74' => array( 'location' => 'grid',
'cellId' => 'headcell_field29' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field29' ),
'simple_grid_field75' => array( 'location' => 'grid',
'cellId' => 'headcell_field30' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'cell_field30' ),
'simple_grid_field76' => array( 'location' => 'grid',
'cellId' => 'headcell_field31' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'cell_field31' ),
'simple_grid_field77' => array( 'location' => 'grid',
'cellId' => 'headcell_field32' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'cell_field32' ),
'simple_grid_field78' => array( 'location' => 'grid',
'cellId' => 'headcell_field33' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'cell_field33' ),
'simple_grid_field79' => array( 'location' => 'grid',
'cellId' => 'headcell_field34' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'cell_field34' ),
'simple_grid_field80' => array( 'location' => 'grid',
'cellId' => 'headcell_field35' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'cell_field35' ),
'simple_grid_field81' => array( 'location' => 'grid',
'cellId' => 'headcell_field36' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'cell_field36' ),
'simple_grid_field82' => array( 'location' => 'grid',
'cellId' => 'headcell_field37' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'cell_field37' ),
'simple_grid_field83' => array( 'location' => 'grid',
'cellId' => 'headcell_field38' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'cell_field38' ),
'simple_grid_field84' => array( 'location' => 'grid',
'cellId' => 'headcell_field39' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'cell_field39' ),
'simple_grid_field85' => array( 'location' => 'grid',
'cellId' => 'headcell_field40' ),
'simple_grid_field37' => array( 'location' => 'grid',
'cellId' => 'cell_field40' ),
'simple_grid_field86' => array( 'location' => 'grid',
'cellId' => 'headcell_field41' ),
'simple_grid_field38' => array( 'location' => 'grid',
'cellId' => 'cell_field41' ),
'simple_grid_field87' => array( 'location' => 'grid',
'cellId' => 'headcell_field42' ),
'simple_grid_field39' => array( 'location' => 'grid',
'cellId' => 'cell_field42' ),
'simple_grid_field88' => array( 'location' => 'grid',
'cellId' => 'headcell_field43' ),
'simple_grid_field40' => array( 'location' => 'grid',
'cellId' => 'cell_field43' ),
'simple_grid_field89' => array( 'location' => 'grid',
'cellId' => 'headcell_field44' ),
'simple_grid_field41' => array( 'location' => 'grid',
'cellId' => 'cell_field44' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'grid_field' => array( 'simple_grid_field42',
'simple_grid_field44',
'simple_grid_field43',
'simple_grid_field',
'simple_grid_field2',
'simple_grid_field4',
'simple_grid_field6',
'simple_grid_field1',
'simple_grid_field3',
'simple_grid_field5',
'simple_grid_field7',
'simple_grid_field8',
'simple_grid_field9',
'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field12',
'simple_grid_field13',
'simple_grid_field14',
'simple_grid_field15',
'simple_grid_field16',
'simple_grid_field17',
'simple_grid_field18',
'simple_grid_field19',
'simple_grid_field20',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field23',
'simple_grid_field24',
'simple_grid_field25',
'simple_grid_field26',
'simple_grid_field27',
'simple_grid_field28',
'simple_grid_field29',
'simple_grid_field30',
'simple_grid_field31',
'simple_grid_field32',
'simple_grid_field33',
'simple_grid_field34',
'simple_grid_field35',
'simple_grid_field36',
'simple_grid_field37',
'simple_grid_field38',
'simple_grid_field39',
'simple_grid_field40',
'simple_grid_field41' ),
'grid_field_label' => array( 'simple_grid_field45',
'simple_grid_field46',
'simple_grid_field47',
'simple_grid_field48',
'simple_grid_field49',
'simple_grid_field50',
'simple_grid_field51',
'simple_grid_field52',
'simple_grid_field53',
'simple_grid_field54',
'simple_grid_field55',
'simple_grid_field56',
'simple_grid_field57',
'simple_grid_field58',
'simple_grid_field59',
'simple_grid_field60',
'simple_grid_field61',
'simple_grid_field62',
'simple_grid_field63',
'simple_grid_field64',
'simple_grid_field65',
'simple_grid_field66',
'simple_grid_field67',
'simple_grid_field68',
'simple_grid_field69',
'simple_grid_field70',
'simple_grid_field71',
'simple_grid_field72',
'simple_grid_field73',
'simple_grid_field74',
'simple_grid_field75',
'simple_grid_field76',
'simple_grid_field77',
'simple_grid_field78',
'simple_grid_field79',
'simple_grid_field80',
'simple_grid_field81',
'simple_grid_field82',
'simple_grid_field83',
'simple_grid_field84',
'simple_grid_field85',
'simple_grid_field86',
'simple_grid_field87',
'simple_grid_field88',
'simple_grid_field89' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'indicator_group_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field45' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'indicator_group_name_fieldheadercolumn' ),
'items' => array( 'simple_grid_field46' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'indicator_group_code_fieldheadercolumn' ),
'items' => array( 'simple_grid_field47' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'indicator_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field48' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'indicator_name_fieldheadercolumn' ),
'items' => array( 'simple_grid_field49' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'indicator_type_fieldheadercolumn' ),
'items' => array( 'simple_grid_field50' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'formula_fieldheadercolumn' ),
'items' => array( 'simple_grid_field51' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'indicator_code_fieldheadercolumn' ),
'items' => array( 'simple_grid_field52' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'period_type_fieldheadercolumn' ),
'items' => array( 'simple_grid_field53' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'period_year_fieldheadercolumn' ),
'items' => array( 'simple_grid_field54' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'period_quarter_fieldheadercolumn' ),
'items' => array( 'simple_grid_field55' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'period_month_fieldheadercolumn' ),
'items' => array( 'simple_grid_field56' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'region_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field57' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'region_name_fieldheadercolumn' ),
'items' => array( 'simple_grid_field58' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'country_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field59' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'country_name_fieldheadercolumn' ),
'items' => array( 'simple_grid_field60' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'facility_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field61' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'facility_name_fieldheadercolumn' ),
'items' => array( 'simple_grid_field62' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'actual_value_fieldheadercolumn' ),
'items' => array( 'simple_grid_field63' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array( 'target_value_fieldheadercolumn' ),
'items' => array( 'simple_grid_field64' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 0 ),
'tags' => array( 'variance_fieldheadercolumn' ),
'items' => array( 'simple_grid_field65' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 0 ),
'tags' => array( 'variance_percentage_fieldheadercolumn' ),
'items' => array( 'simple_grid_field66' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 0 ),
'tags' => array( 'calculation_timestamp_fieldheadercolumn' ),
'items' => array( 'simple_grid_field67' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 0 ),
'tags' => array( 'is_calculated_fieldheadercolumn' ),
'items' => array( 'simple_grid_field68' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 0 ),
'tags' => array( 'decimals_fieldheadercolumn' ),
'items' => array( 'simple_grid_field69' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 0 ),
'tags' => array( 'annualized_fieldheadercolumn' ),
'items' => array( 'simple_grid_field70' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 0 ),
'tags' => array( 'data_completeness_fieldheadercolumn' ),
'items' => array( 'simple_grid_field71' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 0 ),
'tags' => array( 'performance_status_fieldheadercolumn' ),
'items' => array( 'simple_grid_field72' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 0 ),
'tags' => array( 'overall_completion_percentage_fieldheadercolumn' ),
'items' => array( 'simple_grid_field73' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 0 ),
'tags' => array( 'actual_value_completion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field74' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 0 ),
'tags' => array( 'target_value_completion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field75' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 0 ),
'tags' => array( 'completion_status_fieldheadercolumn' ),
'items' => array( 'simple_grid_field76' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 0 ),
'tags' => array( 'is_actual_missing_fieldheadercolumn' ),
'items' => array( 'simple_grid_field77' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 0 ),
'tags' => array( 'is_target_missing_fieldheadercolumn' ),
'items' => array( 'simple_grid_field78' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 0 ),
'tags' => array( 'data_freshness_fieldheadercolumn' ),
'items' => array( 'simple_grid_field79' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 0 ),
'tags' => array( 'days_since_last_calculation_fieldheadercolumn' ),
'items' => array( 'simple_grid_field80' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 0 ),
'tags' => array( 'performance_percentage_fieldheadercolumn' ),
'items' => array( 'simple_grid_field81' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 0 ),
'tags' => array( 'data_quality_flag_fieldheadercolumn' ),
'items' => array( 'simple_grid_field82' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 0 ),
'tags' => array( 'data_hierarchy_level_fieldheadercolumn' ),
'items' => array( 'simple_grid_field83' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 0 ),
'tags' => array( 'period_completeness_fieldheadercolumn' ),
'items' => array( 'simple_grid_field84' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field40' => array( 'cols' => array( 40 ),
'rows' => array( 0 ),
'tags' => array( 'calculation_method_fieldheadercolumn' ),
'items' => array( 'simple_grid_field85' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field41' => array( 'cols' => array( 41 ),
'rows' => array( 0 ),
'tags' => array( 'formula_type_fieldheadercolumn' ),
'items' => array( 'simple_grid_field86' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field42' => array( 'cols' => array( 42 ),
'rows' => array( 0 ),
'tags' => array( 'org_unit_validity_fieldheadercolumn' ),
'items' => array( 'simple_grid_field87' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field43' => array( 'cols' => array( 43 ),
'rows' => array( 0 ),
'tags' => array( 'period_validity_fieldheadercolumn' ),
'items' => array( 'simple_grid_field88' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field44' => array( 'cols' => array( 44 ),
'rows' => array( 0 ),
'tags' => array( 'legacy_performance_status_fieldheadercolumn' ),
'items' => array( 'simple_grid_field89' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'indicator_group_id_fieldcolumn' ),
'items' => array( 'simple_grid_field42' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'indicator_group_name_fieldcolumn' ),
'items' => array( 'simple_grid_field44' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'indicator_group_code_fieldcolumn' ),
'items' => array( 'simple_grid_field43' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'indicator_id_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'indicator_name_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'indicator_type_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'formula_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'indicator_code_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'period_type_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'period_year_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'period_quarter_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'period_month_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'region_id_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'region_name_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'country_id_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'country_name_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'facility_id_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'facility_name_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'actual_value_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'target_value_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 1 ),
'tags' => array( 'variance_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 1 ),
'tags' => array( 'variance_percentage_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 1 ),
'tags' => array( 'calculation_timestamp_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 1 ),
'tags' => array( 'is_calculated_fieldcolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 1 ),
'tags' => array( 'decimals_fieldcolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 1 ),
'tags' => array( 'annualized_fieldcolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 1 ),
'tags' => array( 'data_completeness_fieldcolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 1 ),
'tags' => array( 'performance_status_fieldcolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 1 ),
'tags' => array( 'overall_completion_percentage_fieldcolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 1 ),
'tags' => array( 'actual_value_completion_fieldcolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 1 ),
'tags' => array( 'target_value_completion_fieldcolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 1 ),
'tags' => array( 'completion_status_fieldcolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 1 ),
'tags' => array( 'is_actual_missing_fieldcolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 1 ),
'tags' => array( 'is_target_missing_fieldcolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 1 ),
'tags' => array( 'data_freshness_fieldcolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 1 ),
'tags' => array( 'days_since_last_calculation_fieldcolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 1 ),
'tags' => array( 'performance_percentage_fieldcolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 1 ),
'tags' => array( 'data_quality_flag_fieldcolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 1 ),
'tags' => array( 'data_hierarchy_level_fieldcolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 1 ),
'tags' => array( 'period_completeness_fieldcolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field40' => array( 'cols' => array( 40 ),
'rows' => array( 1 ),
'tags' => array( 'calculation_method_fieldcolumn' ),
'items' => array( 'simple_grid_field37' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field41' => array( 'cols' => array( 41 ),
'rows' => array( 1 ),
'tags' => array( 'formula_type_fieldcolumn' ),
'items' => array( 'simple_grid_field38' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field42' => array( 'cols' => array( 42 ),
'rows' => array( 1 ),
'tags' => array( 'org_unit_validity_fieldcolumn' ),
'items' => array( 'simple_grid_field39' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field43' => array( 'cols' => array( 43 ),
'rows' => array( 1 ),
'tags' => array( 'period_validity_fieldcolumn' ),
'items' => array( 'simple_grid_field40' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field44' => array( 'cols' => array( 44 ),
'rows' => array( 1 ),
'tags' => array( 'legacy_performance_status_fieldcolumn' ),
'items' => array( 'simple_grid_field41' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field40' => array( 'cols' => array( 40 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field41' => array( 'cols' => array( 41 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field42' => array( 'cols' => array( 42 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field43' => array( 'cols' => array( 43 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field44' => array( 'cols' => array( 44 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 45,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'print',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'print',
'type' => 'print',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field19' ),
array( 'cell' => 'headcell_field20' ),
array( 'cell' => 'headcell_field21' ),
array( 'cell' => 'headcell_field22' ),
array( 'cell' => 'headcell_field23' ),
array( 'cell' => 'headcell_field24' ),
array( 'cell' => 'headcell_field25' ),
array( 'cell' => 'headcell_field26' ),
array( 'cell' => 'headcell_field27' ),
array( 'cell' => 'headcell_field28' ),
array( 'cell' => 'headcell_field29' ),
array( 'cell' => 'headcell_field30' ),
array( 'cell' => 'headcell_field31' ),
array( 'cell' => 'headcell_field32' ),
array( 'cell' => 'headcell_field33' ),
array( 'cell' => 'headcell_field34' ),
array( 'cell' => 'headcell_field35' ),
array( 'cell' => 'headcell_field36' ),
array( 'cell' => 'headcell_field37' ),
array( 'cell' => 'headcell_field38' ),
array( 'cell' => 'headcell_field39' ),
array( 'cell' => 'headcell_field40' ),
array( 'cell' => 'headcell_field41' ),
array( 'cell' => 'headcell_field42' ),
array( 'cell' => 'headcell_field43' ),
array( 'cell' => 'headcell_field44' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_field22' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'cell_field24' ),
array( 'cell' => 'cell_field25' ),
array( 'cell' => 'cell_field26' ),
array( 'cell' => 'cell_field27' ),
array( 'cell' => 'cell_field28' ),
array( 'cell' => 'cell_field29' ),
array( 'cell' => 'cell_field30' ),
array( 'cell' => 'cell_field31' ),
array( 'cell' => 'cell_field32' ),
array( 'cell' => 'cell_field33' ),
array( 'cell' => 'cell_field34' ),
array( 'cell' => 'cell_field35' ),
array( 'cell' => 'cell_field36' ),
array( 'cell' => 'cell_field37' ),
array( 'cell' => 'cell_field38' ),
array( 'cell' => 'cell_field39' ),
array( 'cell' => 'cell_field40' ),
array( 'cell' => 'cell_field41' ),
array( 'cell' => 'cell_field42' ),
array( 'cell' => 'cell_field43' ),
array( 'cell' => 'cell_field44' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field19' ),
array( 'cell' => 'footcell_field20' ),
array( 'cell' => 'footcell_field21' ),
array( 'cell' => 'footcell_field22' ),
array( 'cell' => 'footcell_field23' ),
array( 'cell' => 'footcell_field24' ),
array( 'cell' => 'footcell_field25' ),
array( 'cell' => 'footcell_field26' ),
array( 'cell' => 'footcell_field27' ),
array( 'cell' => 'footcell_field28' ),
array( 'cell' => 'footcell_field29' ),
array( 'cell' => 'footcell_field30' ),
array( 'cell' => 'footcell_field31' ),
array( 'cell' => 'footcell_field32' ),
array( 'cell' => 'footcell_field33' ),
array( 'cell' => 'footcell_field34' ),
array( 'cell' => 'footcell_field35' ),
array( 'cell' => 'footcell_field36' ),
array( 'cell' => 'footcell_field37' ),
array( 'cell' => 'footcell_field38' ),
array( 'cell' => 'footcell_field39' ),
array( 'cell' => 'footcell_field40' ),
array( 'cell' => 'footcell_field41' ),
array( 'cell' => 'footcell_field42' ),
array( 'cell' => 'footcell_field43' ),
array( 'cell' => 'footcell_field44' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field45' ),
'field' => 'indicator_group_id',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field42' ),
'field' => 'indicator_group_id',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field46' ),
'field' => 'indicator_group_name',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field44' ),
'field' => 'indicator_group_name',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field47' ),
'field' => 'indicator_group_code',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field43' ),
'field' => 'indicator_group_code',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field48' ),
'field' => 'indicator_id',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'indicator_id',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field49' ),
'field' => 'indicator_name',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'indicator_name',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field50' ),
'field' => 'indicator_type',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'indicator_type',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field51' ),
'field' => 'formula',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'formula',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field52' ),
'field' => 'indicator_code',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'indicator_code',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field53' ),
'field' => 'period_type',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'period_type',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field54' ),
'field' => 'period_year',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'period_year',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field55' ),
'field' => 'period_quarter',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'period_quarter',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field56' ),
'field' => 'period_month',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'period_month',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field57' ),
'field' => 'region_id',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'region_id',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field58' ),
'field' => 'region_name',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'region_name',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field59' ),
'field' => 'country_id',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'country_id',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field60' ),
'field' => 'country_name',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'country_name',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field61' ),
'field' => 'facility_id',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'facility_id',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field62' ),
'field' => 'facility_name',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'facility_name',
'columnName' => 'field' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field63' ),
'field' => 'actual_value',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'actual_value',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field19' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field64' ),
'field' => 'target_value',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'target_value',
'columnName' => 'field' ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field20' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field65' ),
'field' => 'variance',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'variance',
'columnName' => 'field' ),
'footcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field21' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field66' ),
'field' => 'variance_percentage',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'variance_percentage',
'columnName' => 'field' ),
'footcell_field21' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field22' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field67' ),
'field' => 'calculation_timestamp',
'columnName' => 'field' ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'calculation_timestamp',
'columnName' => 'field' ),
'footcell_field22' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field23' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field68' ),
'field' => 'is_calculated',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'is_calculated',
'columnName' => 'field' ),
'footcell_field23' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field24' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field69' ),
'field' => 'decimals',
'columnName' => 'field' ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'decimals',
'columnName' => 'field' ),
'footcell_field24' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field25' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field70' ),
'field' => 'annualized',
'columnName' => 'field' ),
'cell_field25' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'annualized',
'columnName' => 'field' ),
'footcell_field25' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field26' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field71' ),
'field' => 'data_completeness',
'columnName' => 'field' ),
'cell_field26' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'data_completeness',
'columnName' => 'field' ),
'footcell_field26' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field27' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field72' ),
'field' => 'performance_status',
'columnName' => 'field' ),
'cell_field27' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'performance_status',
'columnName' => 'field' ),
'footcell_field27' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field28' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field73' ),
'field' => 'overall_completion_percentage',
'columnName' => 'field' ),
'cell_field28' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field25' ),
'field' => 'overall_completion_percentage',
'columnName' => 'field' ),
'footcell_field28' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field29' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field74' ),
'field' => 'actual_value_completion',
'columnName' => 'field' ),
'cell_field29' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'actual_value_completion',
'columnName' => 'field' ),
'footcell_field29' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field30' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field75' ),
'field' => 'target_value_completion',
'columnName' => 'field' ),
'cell_field30' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'target_value_completion',
'columnName' => 'field' ),
'footcell_field30' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field31' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field76' ),
'field' => 'completion_status',
'columnName' => 'field' ),
'cell_field31' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'completion_status',
'columnName' => 'field' ),
'footcell_field31' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field32' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field77' ),
'field' => 'is_actual_missing',
'columnName' => 'field' ),
'cell_field32' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'is_actual_missing',
'columnName' => 'field' ),
'footcell_field32' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field33' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field78' ),
'field' => 'is_target_missing',
'columnName' => 'field' ),
'cell_field33' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'is_target_missing',
'columnName' => 'field' ),
'footcell_field33' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field34' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field79' ),
'field' => 'data_freshness',
'columnName' => 'field' ),
'cell_field34' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field31' ),
'field' => 'data_freshness',
'columnName' => 'field' ),
'footcell_field34' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field35' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field80' ),
'field' => 'days_since_last_calculation',
'columnName' => 'field' ),
'cell_field35' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field32' ),
'field' => 'days_since_last_calculation',
'columnName' => 'field' ),
'footcell_field35' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field36' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field81' ),
'field' => 'performance_percentage',
'columnName' => 'field' ),
'cell_field36' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field33' ),
'field' => 'performance_percentage',
'columnName' => 'field' ),
'footcell_field36' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field37' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field82' ),
'field' => 'data_quality_flag',
'columnName' => 'field' ),
'cell_field37' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field34' ),
'field' => 'data_quality_flag',
'columnName' => 'field' ),
'footcell_field37' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field38' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field83' ),
'field' => 'data_hierarchy_level',
'columnName' => 'field' ),
'cell_field38' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field35' ),
'field' => 'data_hierarchy_level',
'columnName' => 'field' ),
'footcell_field38' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field39' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field84' ),
'field' => 'period_completeness',
'columnName' => 'field' ),
'cell_field39' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field36' ),
'field' => 'period_completeness',
'columnName' => 'field' ),
'footcell_field39' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field40' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field85' ),
'field' => 'calculation_method',
'columnName' => 'field' ),
'cell_field40' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field37' ),
'field' => 'calculation_method',
'columnName' => 'field' ),
'footcell_field40' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field41' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field86' ),
'field' => 'formula_type',
'columnName' => 'field' ),
'cell_field41' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field38' ),
'field' => 'formula_type',
'columnName' => 'field' ),
'footcell_field41' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field42' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field87' ),
'field' => 'org_unit_validity',
'columnName' => 'field' ),
'cell_field42' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field39' ),
'field' => 'org_unit_validity',
'columnName' => 'field' ),
'footcell_field42' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field43' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field88' ),
'field' => 'period_validity',
'columnName' => 'field' ),
'cell_field43' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field40' ),
'field' => 'period_validity',
'columnName' => 'field' ),
'footcell_field43' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field44' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field89' ),
'field' => 'legacy_performance_status',
'columnName' => 'field' ),
'cell_field44' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field41' ),
'field' => 'legacy_performance_status',
'columnName' => 'field' ),
'footcell_field44' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'simple_grid_field42' => array( 'field' => 'indicator_group_id',
'type' => 'grid_field' ),
'simple_grid_field45' => array( 'type' => 'grid_field_label',
'field' => 'indicator_group_id' ),
'simple_grid_field44' => array( 'field' => 'indicator_group_name',
'type' => 'grid_field' ),
'simple_grid_field46' => array( 'type' => 'grid_field_label',
'field' => 'indicator_group_name' ),
'simple_grid_field43' => array( 'field' => 'indicator_group_code',
'type' => 'grid_field' ),
'simple_grid_field47' => array( 'type' => 'grid_field_label',
'field' => 'indicator_group_code' ),
'simple_grid_field' => array( 'field' => 'indicator_id',
'type' => 'grid_field' ),
'simple_grid_field48' => array( 'type' => 'grid_field_label',
'field' => 'indicator_id' ),
'simple_grid_field2' => array( 'field' => 'indicator_name',
'type' => 'grid_field' ),
'simple_grid_field49' => array( 'type' => 'grid_field_label',
'field' => 'indicator_name' ),
'simple_grid_field4' => array( 'field' => 'indicator_type',
'type' => 'grid_field' ),
'simple_grid_field50' => array( 'type' => 'grid_field_label',
'field' => 'indicator_type' ),
'simple_grid_field6' => array( 'field' => 'formula',
'type' => 'grid_field' ),
'simple_grid_field51' => array( 'type' => 'grid_field_label',
'field' => 'formula' ),
'simple_grid_field1' => array( 'field' => 'indicator_code',
'type' => 'grid_field' ),
'simple_grid_field52' => array( 'type' => 'grid_field_label',
'field' => 'indicator_code' ),
'simple_grid_field3' => array( 'field' => 'period_type',
'type' => 'grid_field' ),
'simple_grid_field53' => array( 'type' => 'grid_field_label',
'field' => 'period_type' ),
'simple_grid_field5' => array( 'field' => 'period_year',
'type' => 'grid_field' ),
'simple_grid_field54' => array( 'type' => 'grid_field_label',
'field' => 'period_year' ),
'simple_grid_field7' => array( 'field' => 'period_quarter',
'type' => 'grid_field' ),
'simple_grid_field55' => array( 'type' => 'grid_field_label',
'field' => 'period_quarter' ),
'simple_grid_field8' => array( 'field' => 'period_month',
'type' => 'grid_field' ),
'simple_grid_field56' => array( 'type' => 'grid_field_label',
'field' => 'period_month' ),
'simple_grid_field9' => array( 'field' => 'region_id',
'type' => 'grid_field' ),
'simple_grid_field57' => array( 'type' => 'grid_field_label',
'field' => 'region_id' ),
'simple_grid_field10' => array( 'field' => 'region_name',
'type' => 'grid_field' ),
'simple_grid_field58' => array( 'type' => 'grid_field_label',
'field' => 'region_name' ),
'simple_grid_field11' => array( 'field' => 'country_id',
'type' => 'grid_field' ),
'simple_grid_field59' => array( 'type' => 'grid_field_label',
'field' => 'country_id' ),
'simple_grid_field12' => array( 'field' => 'country_name',
'type' => 'grid_field' ),
'simple_grid_field60' => array( 'type' => 'grid_field_label',
'field' => 'country_name' ),
'simple_grid_field13' => array( 'field' => 'facility_id',
'type' => 'grid_field' ),
'simple_grid_field61' => array( 'type' => 'grid_field_label',
'field' => 'facility_id' ),
'simple_grid_field14' => array( 'field' => 'facility_name',
'type' => 'grid_field' ),
'simple_grid_field62' => array( 'type' => 'grid_field_label',
'field' => 'facility_name' ),
'simple_grid_field15' => array( 'field' => 'actual_value',
'type' => 'grid_field' ),
'simple_grid_field63' => array( 'type' => 'grid_field_label',
'field' => 'actual_value' ),
'simple_grid_field16' => array( 'field' => 'target_value',
'type' => 'grid_field' ),
'simple_grid_field64' => array( 'type' => 'grid_field_label',
'field' => 'target_value' ),
'simple_grid_field17' => array( 'field' => 'variance',
'type' => 'grid_field' ),
'simple_grid_field65' => array( 'type' => 'grid_field_label',
'field' => 'variance' ),
'simple_grid_field18' => array( 'field' => 'variance_percentage',
'type' => 'grid_field' ),
'simple_grid_field66' => array( 'type' => 'grid_field_label',
'field' => 'variance_percentage' ),
'simple_grid_field19' => array( 'field' => 'calculation_timestamp',
'type' => 'grid_field' ),
'simple_grid_field67' => array( 'type' => 'grid_field_label',
'field' => 'calculation_timestamp' ),
'simple_grid_field20' => array( 'field' => 'is_calculated',
'type' => 'grid_field' ),
'simple_grid_field68' => array( 'type' => 'grid_field_label',
'field' => 'is_calculated' ),
'simple_grid_field21' => array( 'field' => 'decimals',
'type' => 'grid_field' ),
'simple_grid_field69' => array( 'type' => 'grid_field_label',
'field' => 'decimals' ),
'simple_grid_field22' => array( 'field' => 'annualized',
'type' => 'grid_field' ),
'simple_grid_field70' => array( 'type' => 'grid_field_label',
'field' => 'annualized' ),
'simple_grid_field23' => array( 'field' => 'data_completeness',
'type' => 'grid_field' ),
'simple_grid_field71' => array( 'type' => 'grid_field_label',
'field' => 'data_completeness' ),
'simple_grid_field24' => array( 'field' => 'performance_status',
'type' => 'grid_field' ),
'simple_grid_field72' => array( 'type' => 'grid_field_label',
'field' => 'performance_status' ),
'simple_grid_field25' => array( 'field' => 'overall_completion_percentage',
'type' => 'grid_field' ),
'simple_grid_field73' => array( 'type' => 'grid_field_label',
'field' => 'overall_completion_percentage' ),
'simple_grid_field26' => array( 'field' => 'actual_value_completion',
'type' => 'grid_field' ),
'simple_grid_field74' => array( 'type' => 'grid_field_label',
'field' => 'actual_value_completion' ),
'simple_grid_field27' => array( 'field' => 'target_value_completion',
'type' => 'grid_field' ),
'simple_grid_field75' => array( 'type' => 'grid_field_label',
'field' => 'target_value_completion' ),
'simple_grid_field28' => array( 'field' => 'completion_status',
'type' => 'grid_field' ),
'simple_grid_field76' => array( 'type' => 'grid_field_label',
'field' => 'completion_status' ),
'simple_grid_field29' => array( 'field' => 'is_actual_missing',
'type' => 'grid_field' ),
'simple_grid_field77' => array( 'type' => 'grid_field_label',
'field' => 'is_actual_missing' ),
'simple_grid_field30' => array( 'field' => 'is_target_missing',
'type' => 'grid_field' ),
'simple_grid_field78' => array( 'type' => 'grid_field_label',
'field' => 'is_target_missing' ),
'simple_grid_field31' => array( 'field' => 'data_freshness',
'type' => 'grid_field' ),
'simple_grid_field79' => array( 'type' => 'grid_field_label',
'field' => 'data_freshness' ),
'simple_grid_field32' => array( 'field' => 'days_since_last_calculation',
'type' => 'grid_field' ),
'simple_grid_field80' => array( 'type' => 'grid_field_label',
'field' => 'days_since_last_calculation' ),
'simple_grid_field33' => array( 'field' => 'performance_percentage',
'type' => 'grid_field' ),
'simple_grid_field81' => array( 'type' => 'grid_field_label',
'field' => 'performance_percentage' ),
'simple_grid_field34' => array( 'field' => 'data_quality_flag',
'type' => 'grid_field' ),
'simple_grid_field82' => array( 'type' => 'grid_field_label',
'field' => 'data_quality_flag' ),
'simple_grid_field35' => array( 'field' => 'data_hierarchy_level',
'type' => 'grid_field' ),
'simple_grid_field83' => array( 'type' => 'grid_field_label',
'field' => 'data_hierarchy_level' ),
'simple_grid_field36' => array( 'field' => 'period_completeness',
'type' => 'grid_field' ),
'simple_grid_field84' => array( 'type' => 'grid_field_label',
'field' => 'period_completeness' ),
'simple_grid_field37' => array( 'field' => 'calculation_method',
'type' => 'grid_field' ),
'simple_grid_field85' => array( 'type' => 'grid_field_label',
'field' => 'calculation_method' ),
'simple_grid_field38' => array( 'field' => 'formula_type',
'type' => 'grid_field' ),
'simple_grid_field86' => array( 'type' => 'grid_field_label',
'field' => 'formula_type' ),
'simple_grid_field39' => array( 'field' => 'org_unit_validity',
'type' => 'grid_field' ),
'simple_grid_field87' => array( 'type' => 'grid_field_label',
'field' => 'org_unit_validity' ),
'simple_grid_field40' => array( 'field' => 'period_validity',
'type' => 'grid_field' ),
'simple_grid_field88' => array( 'type' => 'grid_field_label',
'field' => 'period_validity' ),
'simple_grid_field41' => array( 'field' => 'legacy_performance_status',
'type' => 'grid_field' ),
'simple_grid_field89' => array( 'type' => 'grid_field_label',
'field' => 'legacy_performance_status' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>