<?php
			$optionsArray = array( 'totals' => array( 'LB_Int_ID' => array( 'totalsType' => '' ),
'LB_Int' => array( 'totalsType' => '' ),
'Cont_ID' => array( 'totalsType' => '' ),
'Continent' => array( 'totalsType' => '' ),
'Count_ID' => array( 'totalsType' => '' ),
'Country' => array( 'totalsType' => '' ),
'Hosp_Fac_ID' => array( 'totalsType' => '' ),
'Hospital_Facility' => array( 'totalsType' => '' ),
'Level' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'LB_Int_ID',
'LB_Int',
'Cont_ID',
'Continent',
'Count_ID',
'Country',
'Hosp_Fac_ID',
'Hospital_Facility',
'Level' ),
'exportFields' => array( 'Continent',
'Country',
'Level',
'LB_Int_ID',
'LB_Int',
'Cont_ID',
'Count_ID',
'Hosp_Fac_ID',
'Hospital_Facility' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'LB_Int_ID' => array( 'export_field' ),
'LB_Int' => array( 'export_field1' ),
'Cont_ID' => array( 'export_field2' ),
'Continent' => array( 'export_field3' ),
'Count_ID' => array( 'export_field4' ),
'Country' => array( 'export_field5' ),
'Hosp_Fac_ID' => array( 'export_field6' ),
'Hospital_Facility' => array( 'export_field7' ),
'Level' => array( 'export_field8' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field3',
'export_field5',
'export_field8',
'export_field',
'export_field1',
'export_field2',
'export_field4',
'export_field6',
'export_field7' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field3' => 'grid',
'export_field5' => 'grid',
'export_field8' => 'grid',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field4' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field3',
'export_field5',
'export_field8',
'export_field',
'export_field1',
'export_field2',
'export_field4',
'export_field6',
'export_field7' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'LB_Int_ID',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'LB_Int',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'Cont_ID',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'Continent',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'Count_ID',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'Country',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'Hosp_Fac_ID',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'Hospital_Facility',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'Level',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>