<?php
			$optionsArray = array( 'totals' => array( 'id' => array( 'totalsType' => '' ),
'setting_id' => array( 'totalsType' => '' ),
'dx_id' => array( 'totalsType' => '' ),
'dx_name' => array( 'totalsType' => '' ),
'dx_shortname' => array( 'totalsType' => '' ),
'dx_displayname' => array( 'totalsType' => '' ),
'dx_dimensiontype' => array( 'totalsType' => '' ),
'ou_id' => array( 'totalsType' => '' ),
'ou_name' => array( 'totalsType' => '' ),
'ou_parent_id' => array( 'totalsType' => '' ),
'ou_parent_name' => array( 'totalsType' => '' ),
'pe_id' => array( 'totalsType' => '' ),
'pe_name' => array( 'totalsType' => '' ),
'pe_relativeperiod' => array( 'totalsType' => '' ),
'value' => array( 'totalsType' => '' ),
'stored_by' => array( 'totalsType' => '' ),
'created' => array( 'totalsType' => '' ),
'last_updated' => array( 'totalsType' => '' ),
'fetched_at' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'id',
'setting_id',
'dx_id',
'dx_name',
'dx_shortname',
'dx_displayname',
'dx_dimensiontype',
'ou_id',
'ou_name',
'pe_id',
'pe_name',
'pe_relativeperiod',
'value',
'stored_by',
'created',
'last_updated',
'fetched_at',
'ou_parent_id',
'ou_parent_name' ),
'exportFields' => array( 'id',
'setting_id',
'dx_id',
'dx_name',
'dx_shortname',
'dx_displayname',
'dx_dimensiontype',
'ou_parent_id',
'ou_parent_name',
'ou_id',
'ou_name',
'pe_id',
'pe_name',
'pe_relativeperiod',
'value',
'stored_by',
'created',
'last_updated',
'fetched_at' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id' => array( 'export_field' ),
'setting_id' => array( 'export_field1' ),
'dx_id' => array( 'export_field2' ),
'dx_name' => array( 'export_field3' ),
'dx_shortname' => array( 'export_field4' ),
'dx_displayname' => array( 'export_field5' ),
'dx_dimensiontype' => array( 'export_field6' ),
'ou_id' => array( 'export_field7' ),
'ou_name' => array( 'export_field8' ),
'pe_id' => array( 'export_field9' ),
'pe_name' => array( 'export_field10' ),
'pe_relativeperiod' => array( 'export_field11' ),
'value' => array( 'export_field12' ),
'stored_by' => array( 'export_field13' ),
'created' => array( 'export_field14' ),
'last_updated' => array( 'export_field15' ),
'fetched_at' => array( 'export_field16' ),
'ou_parent_id' => array( 'export_field17' ),
'ou_parent_name' => array( 'export_field18' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field17',
'export_field18',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field17',
'export_field18',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'setting_id',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'dx_id',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'dx_name',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'dx_shortname',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'dx_displayname',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'dx_dimensiontype',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'ou_id',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'ou_name',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'pe_id',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'pe_name',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'pe_relativeperiod',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'value',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'stored_by',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'created',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'last_updated',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'fetched_at',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'ou_parent_id',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'ou_parent_name',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>