<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'case_id',
'facility_name',
'country_name',
'surgery_date',
'data_type',
'data_collector_name',
'location_of_surgery',
'patient_sex',
'patient_age',
'procedure_name',
'diagnosis_name',
'wound_classification',
'case_type',
'death_in_or',
'fetal_death',
'death_in_ward',
'neonatal_death',
'follow_up_status' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'case_id' => array( 'import_field' ),
'facility_name' => array( 'import_field1' ),
'country_name' => array( 'import_field2' ),
'surgery_date' => array( 'import_field3' ),
'data_type' => array( 'import_field4' ),
'data_collector_name' => array( 'import_field5' ),
'location_of_surgery' => array( 'import_field6' ),
'patient_sex' => array( 'import_field7' ),
'patient_age' => array( 'import_field8' ),
'procedure_name' => array( 'import_field9' ),
'diagnosis_name' => array( 'import_field10' ),
'wound_classification' => array( 'import_field11' ),
'case_type' => array( 'import_field12' ),
'death_in_or' => array( 'import_field13' ),
'fetal_death' => array( 'import_field14' ),
'death_in_ward' => array( 'import_field15' ),
'neonatal_death' => array( 'import_field16' ),
'follow_up_status' => array( 'import_field17' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'case_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'facility_name',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'country_name',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'surgery_date',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'data_type',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'data_collector_name',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'location_of_surgery',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'patient_sex',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'patient_age',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'procedure_name',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'diagnosis_name',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'wound_classification',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'case_type',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'death_in_or',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'fetal_death',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'death_in_ward',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'neonatal_death',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'follow_up_status',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>