<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'case_id',
'facility_id',
'country_id',
'surgery_date',
'data_type',
'data_collector_name',
'location_of_surgery',
'patient_sex',
'patient_asa_classification',
'patient_dob',
'patient_age',
'diabetes',
'hypertension',
'obese',
'malnourished',
'smoker',
'on_steroids',
'admitted_to_icu',
'hypothermic',
'preoperative_diagnosis_id',
'hours_since_injury',
'sterilizable_drill_used',
'drill_sterile_cover_used',
'holes_in_sterile_cover',
'sign_in_read_aloud',
'sign_in_completed_before_anesthesia',
'sterility_indicator_in_tray',
'sterility_indicator_color_changed',
'tray_wet_prior_to_operation',
'tray_replaced',
'gauze_count_performed',
'gauze_count_total',
'surgeon_scrubbed_hands',
'handwashing_available',
'alcohol_solution_applied',
'new_surgical_gloves_used',
'gown_sterility_indicator',
'gown_indicator_color_changed',
'gown_pack_replaced',
'gowns_or_drapes_wet',
'wet_gowns_replaced',
'holes_in_gowns',
'torn_gowns_replaced',
'holes_in_drapes',
'drapes_replaced',
'surgical_site_prep_method',
'vaginal_preparation',
'antibiotics_given',
'antibiotics_admin_location',
'antibiotics_time',
'on_scheduled_antibiotics',
'antibiotic_type',
'timeout_read_aloud',
'operation_type_announced',
'blood_loss_announced',
'estimated_blood_loss',
'time_of_incision',
'gauze_count_end_performed',
'gauze_count_end_total',
'time_dressing_applied',
'procedure_id',
'hardware_or_bioprosthetic_used',
'cesarean_indication',
'wound_closed_primarily',
'wound_classification',
'case_type',
'sign_out_read_aloud',
'sign_out_in_theatre',
'unplanned_intubation',
'urgent_tracheostomy',
'urgent_central_access',
'other_crisis_occurred',
'crisis_description',
'death_in_or',
'fetal_death',
'created_at',
'updated_at' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'case_id' => array( 'integrated_search_field' ),
'facility_id' => array( 'integrated_search_field1' ),
'country_id' => array( 'integrated_search_field2' ),
'surgery_date' => array( 'integrated_search_field3' ),
'data_type' => array( 'integrated_search_field4' ),
'data_collector_name' => array( 'integrated_search_field5' ),
'location_of_surgery' => array( 'integrated_search_field6' ),
'patient_sex' => array( 'integrated_search_field7' ),
'patient_asa_classification' => array( 'integrated_search_field8' ),
'patient_dob' => array( 'integrated_search_field9' ),
'patient_age' => array( 'integrated_search_field10' ),
'diabetes' => array( 'integrated_search_field11' ),
'hypertension' => array( 'integrated_search_field12' ),
'obese' => array( 'integrated_search_field13' ),
'malnourished' => array( 'integrated_search_field14' ),
'smoker' => array( 'integrated_search_field15' ),
'on_steroids' => array( 'integrated_search_field16' ),
'admitted_to_icu' => array( 'integrated_search_field17' ),
'hypothermic' => array( 'integrated_search_field18' ),
'preoperative_diagnosis_id' => array( 'integrated_search_field19' ),
'hours_since_injury' => array( 'integrated_search_field20' ),
'sterilizable_drill_used' => array( 'integrated_search_field21' ),
'drill_sterile_cover_used' => array( 'integrated_search_field22' ),
'holes_in_sterile_cover' => array( 'integrated_search_field23' ),
'sign_in_read_aloud' => array( 'integrated_search_field24' ),
'sign_in_completed_before_anesthesia' => array( 'integrated_search_field25' ),
'sterility_indicator_in_tray' => array( 'integrated_search_field26' ),
'sterility_indicator_color_changed' => array( 'integrated_search_field27' ),
'tray_wet_prior_to_operation' => array( 'integrated_search_field28' ),
'tray_replaced' => array( 'integrated_search_field29' ),
'gauze_count_performed' => array( 'integrated_search_field30' ),
'gauze_count_total' => array( 'integrated_search_field31' ),
'surgeon_scrubbed_hands' => array( 'integrated_search_field32' ),
'handwashing_available' => array( 'integrated_search_field33' ),
'alcohol_solution_applied' => array( 'integrated_search_field34' ),
'new_surgical_gloves_used' => array( 'integrated_search_field35' ),
'gown_sterility_indicator' => array( 'integrated_search_field36' ),
'gown_indicator_color_changed' => array( 'integrated_search_field37' ),
'gown_pack_replaced' => array( 'integrated_search_field38' ),
'gowns_or_drapes_wet' => array( 'integrated_search_field39' ),
'wet_gowns_replaced' => array( 'integrated_search_field40' ),
'holes_in_gowns' => array( 'integrated_search_field41' ),
'torn_gowns_replaced' => array( 'integrated_search_field42' ),
'holes_in_drapes' => array( 'integrated_search_field43' ),
'drapes_replaced' => array( 'integrated_search_field44' ),
'surgical_site_prep_method' => array( 'integrated_search_field45' ),
'vaginal_preparation' => array( 'integrated_search_field46' ),
'antibiotics_given' => array( 'integrated_search_field47' ),
'antibiotics_admin_location' => array( 'integrated_search_field48' ),
'antibiotics_time' => array( 'integrated_search_field49' ),
'on_scheduled_antibiotics' => array( 'integrated_search_field50' ),
'antibiotic_type' => array( 'integrated_search_field51' ),
'timeout_read_aloud' => array( 'integrated_search_field52' ),
'operation_type_announced' => array( 'integrated_search_field53' ),
'blood_loss_announced' => array( 'integrated_search_field54' ),
'estimated_blood_loss' => array( 'integrated_search_field55' ),
'time_of_incision' => array( 'integrated_search_field56' ),
'gauze_count_end_performed' => array( 'integrated_search_field57' ),
'gauze_count_end_total' => array( 'integrated_search_field58' ),
'time_dressing_applied' => array( 'integrated_search_field59' ),
'procedure_id' => array( 'integrated_search_field60' ),
'hardware_or_bioprosthetic_used' => array( 'integrated_search_field61' ),
'cesarean_indication' => array( 'integrated_search_field62' ),
'wound_closed_primarily' => array( 'integrated_search_field63' ),
'wound_classification' => array( 'integrated_search_field64' ),
'case_type' => array( 'integrated_search_field65' ),
'sign_out_read_aloud' => array( 'integrated_search_field66' ),
'sign_out_in_theatre' => array( 'integrated_search_field67' ),
'unplanned_intubation' => array( 'integrated_search_field68' ),
'urgent_tracheostomy' => array( 'integrated_search_field69' ),
'urgent_central_access' => array( 'integrated_search_field70' ),
'other_crisis_occurred' => array( 'integrated_search_field71' ),
'crisis_description' => array( 'integrated_search_field72' ),
'death_in_or' => array( 'integrated_search_field73' ),
'fetal_death' => array( 'integrated_search_field74' ),
'created_at' => array( 'integrated_search_field75' ),
'updated_at' => array( 'integrated_search_field76' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'below-grid' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'top' => array( 'search_header' ),
'grid' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53',
'integrated_search_field54',
'integrated_search_field55',
'integrated_search_field56',
'integrated_search_field57',
'integrated_search_field58',
'integrated_search_field59',
'integrated_search_field60',
'integrated_search_field61',
'integrated_search_field62',
'integrated_search_field63',
'integrated_search_field64',
'integrated_search_field65',
'integrated_search_field66',
'integrated_search_field67',
'integrated_search_field68',
'integrated_search_field69',
'integrated_search_field70',
'integrated_search_field71',
'integrated_search_field72',
'integrated_search_field73',
'integrated_search_field74',
'integrated_search_field75',
'integrated_search_field76' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'search_search' => 'below-grid',
'search_reset' => 'below-grid',
'search_back_list' => 'below-grid',
'search_cancel' => 'below-grid',
'search_header' => 'top',
'integrated_search_field' => 'grid',
'integrated_search_field1' => 'grid',
'integrated_search_field2' => 'grid',
'integrated_search_field3' => 'grid',
'integrated_search_field4' => 'grid',
'integrated_search_field5' => 'grid',
'integrated_search_field6' => 'grid',
'integrated_search_field7' => 'grid',
'integrated_search_field8' => 'grid',
'integrated_search_field9' => 'grid',
'integrated_search_field10' => 'grid',
'integrated_search_field11' => 'grid',
'integrated_search_field12' => 'grid',
'integrated_search_field13' => 'grid',
'integrated_search_field14' => 'grid',
'integrated_search_field15' => 'grid',
'integrated_search_field16' => 'grid',
'integrated_search_field17' => 'grid',
'integrated_search_field18' => 'grid',
'integrated_search_field19' => 'grid',
'integrated_search_field20' => 'grid',
'integrated_search_field21' => 'grid',
'integrated_search_field22' => 'grid',
'integrated_search_field23' => 'grid',
'integrated_search_field24' => 'grid',
'integrated_search_field25' => 'grid',
'integrated_search_field26' => 'grid',
'integrated_search_field27' => 'grid',
'integrated_search_field28' => 'grid',
'integrated_search_field29' => 'grid',
'integrated_search_field30' => 'grid',
'integrated_search_field31' => 'grid',
'integrated_search_field32' => 'grid',
'integrated_search_field33' => 'grid',
'integrated_search_field34' => 'grid',
'integrated_search_field35' => 'grid',
'integrated_search_field36' => 'grid',
'integrated_search_field37' => 'grid',
'integrated_search_field38' => 'grid',
'integrated_search_field39' => 'grid',
'integrated_search_field40' => 'grid',
'integrated_search_field41' => 'grid',
'integrated_search_field42' => 'grid',
'integrated_search_field43' => 'grid',
'integrated_search_field44' => 'grid',
'integrated_search_field45' => 'grid',
'integrated_search_field46' => 'grid',
'integrated_search_field47' => 'grid',
'integrated_search_field48' => 'grid',
'integrated_search_field49' => 'grid',
'integrated_search_field50' => 'grid',
'integrated_search_field51' => 'grid',
'integrated_search_field52' => 'grid',
'integrated_search_field53' => 'grid',
'integrated_search_field54' => 'grid',
'integrated_search_field55' => 'grid',
'integrated_search_field56' => 'grid',
'integrated_search_field57' => 'grid',
'integrated_search_field58' => 'grid',
'integrated_search_field59' => 'grid',
'integrated_search_field60' => 'grid',
'integrated_search_field61' => 'grid',
'integrated_search_field62' => 'grid',
'integrated_search_field63' => 'grid',
'integrated_search_field64' => 'grid',
'integrated_search_field65' => 'grid',
'integrated_search_field66' => 'grid',
'integrated_search_field67' => 'grid',
'integrated_search_field68' => 'grid',
'integrated_search_field69' => 'grid',
'integrated_search_field70' => 'grid',
'integrated_search_field71' => 'grid',
'integrated_search_field72' => 'grid',
'integrated_search_field73' => 'grid',
'integrated_search_field74' => 'grid',
'integrated_search_field75' => 'grid',
'integrated_search_field76' => 'grid' ),
'itemLocations' => array( 'integrated_search_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field5' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field8' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field9' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field10' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field11' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field12' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field13' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field14' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field15' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field16' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field17' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field18' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field19' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field20' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field21' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field22' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field23' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field24' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field25' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field26' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field27' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field28' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field29' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field30' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field31' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field32' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field33' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field34' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field35' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field36' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field37' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field38' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field39' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field40' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field41' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field42' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field43' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field44' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field45' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field46' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field47' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field48' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field49' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field50' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field51' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field52' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field53' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field54' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field55' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field56' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field57' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field58' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field59' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field60' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field61' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field62' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field63' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field64' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field65' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field66' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field67' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field68' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field69' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field70' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field71' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field72' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field73' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field74' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field75' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field76' => array( 'location' => 'grid',
'cellId' => 'c3' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'search_header' => array( 'search_header' ),
'search_reset' => array( 'search_reset' ),
'search_back_list' => array( 'search_back_list' ),
'search_search' => array( 'search_search' ),
'search_cancel' => array( 'search_cancel' ),
'integrated_search_field' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53',
'integrated_search_field54',
'integrated_search_field55',
'integrated_search_field56',
'integrated_search_field57',
'integrated_search_field58',
'integrated_search_field59',
'integrated_search_field60',
'integrated_search_field61',
'integrated_search_field62',
'integrated_search_field63',
'integrated_search_field64',
'integrated_search_field65',
'integrated_search_field66',
'integrated_search_field67',
'integrated_search_field68',
'integrated_search_field69',
'integrated_search_field70',
'integrated_search_field71',
'integrated_search_field72',
'integrated_search_field73',
'integrated_search_field74',
'integrated_search_field75',
'integrated_search_field76' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53',
'integrated_search_field54',
'integrated_search_field55',
'integrated_search_field56',
'integrated_search_field57',
'integrated_search_field58',
'integrated_search_field59',
'integrated_search_field60',
'integrated_search_field61',
'integrated_search_field62',
'integrated_search_field63',
'integrated_search_field64',
'integrated_search_field65',
'integrated_search_field66',
'integrated_search_field67',
'integrated_search_field68',
'integrated_search_field69',
'integrated_search_field70',
'integrated_search_field71',
'integrated_search_field72',
'integrated_search_field73',
'integrated_search_field74',
'integrated_search_field75',
'integrated_search_field76' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'search',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'search',
'type' => 'search',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'search-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'search-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'search-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-search',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53',
'integrated_search_field54',
'integrated_search_field55',
'integrated_search_field56',
'integrated_search_field57',
'integrated_search_field58',
'integrated_search_field59',
'integrated_search_field60',
'integrated_search_field61',
'integrated_search_field62',
'integrated_search_field63',
'integrated_search_field64',
'integrated_search_field65',
'integrated_search_field66',
'integrated_search_field67',
'integrated_search_field68',
'integrated_search_field69',
'integrated_search_field70',
'integrated_search_field71',
'integrated_search_field72',
'integrated_search_field73',
'integrated_search_field74',
'integrated_search_field75',
'integrated_search_field76' ) ) ),
'deferredItems' => array(  ),
'separateLabels' => false ) ),
'items' => array( 'search_header' => array( 'type' => 'search_header' ),
'search_reset' => array( 'type' => 'search_reset' ),
'search_back_list' => array( 'type' => 'search_back_list' ),
'search_search' => array( 'type' => 'search_search' ),
'search_cancel' => array( 'type' => 'search_cancel' ),
'integrated_search_field' => array( 'field' => 'case_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field1' => array( 'field' => 'facility_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field2' => array( 'field' => 'country_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field3' => array( 'field' => 'surgery_date',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field4' => array( 'field' => 'data_type',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field5' => array( 'field' => 'data_collector_name',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field6' => array( 'field' => 'location_of_surgery',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field7' => array( 'field' => 'patient_sex',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field8' => array( 'field' => 'patient_asa_classification',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field9' => array( 'field' => 'patient_dob',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field10' => array( 'field' => 'patient_age',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field11' => array( 'field' => 'diabetes',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field12' => array( 'field' => 'hypertension',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field13' => array( 'field' => 'obese',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field14' => array( 'field' => 'malnourished',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field15' => array( 'field' => 'smoker',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field16' => array( 'field' => 'on_steroids',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field17' => array( 'field' => 'admitted_to_icu',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field18' => array( 'field' => 'hypothermic',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field19' => array( 'field' => 'preoperative_diagnosis_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field20' => array( 'field' => 'hours_since_injury',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field21' => array( 'field' => 'sterilizable_drill_used',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field22' => array( 'field' => 'drill_sterile_cover_used',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field23' => array( 'field' => 'holes_in_sterile_cover',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field24' => array( 'field' => 'sign_in_read_aloud',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field25' => array( 'field' => 'sign_in_completed_before_anesthesia',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field26' => array( 'field' => 'sterility_indicator_in_tray',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field27' => array( 'field' => 'sterility_indicator_color_changed',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field28' => array( 'field' => 'tray_wet_prior_to_operation',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field29' => array( 'field' => 'tray_replaced',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field30' => array( 'field' => 'gauze_count_performed',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field31' => array( 'field' => 'gauze_count_total',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field32' => array( 'field' => 'surgeon_scrubbed_hands',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field33' => array( 'field' => 'handwashing_available',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field34' => array( 'field' => 'alcohol_solution_applied',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field35' => array( 'field' => 'new_surgical_gloves_used',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field36' => array( 'field' => 'gown_sterility_indicator',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field37' => array( 'field' => 'gown_indicator_color_changed',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field38' => array( 'field' => 'gown_pack_replaced',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field39' => array( 'field' => 'gowns_or_drapes_wet',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field40' => array( 'field' => 'wet_gowns_replaced',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field41' => array( 'field' => 'holes_in_gowns',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field42' => array( 'field' => 'torn_gowns_replaced',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field43' => array( 'field' => 'holes_in_drapes',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field44' => array( 'field' => 'drapes_replaced',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field45' => array( 'field' => 'surgical_site_prep_method',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field46' => array( 'field' => 'vaginal_preparation',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field47' => array( 'field' => 'antibiotics_given',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field48' => array( 'field' => 'antibiotics_admin_location',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field49' => array( 'field' => 'antibiotics_time',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field50' => array( 'field' => 'on_scheduled_antibiotics',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field51' => array( 'field' => 'antibiotic_type',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field52' => array( 'field' => 'timeout_read_aloud',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field53' => array( 'field' => 'operation_type_announced',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field54' => array( 'field' => 'blood_loss_announced',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field55' => array( 'field' => 'estimated_blood_loss',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field56' => array( 'field' => 'time_of_incision',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field57' => array( 'field' => 'gauze_count_end_performed',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field58' => array( 'field' => 'gauze_count_end_total',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field59' => array( 'field' => 'time_dressing_applied',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field60' => array( 'field' => 'procedure_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field61' => array( 'field' => 'hardware_or_bioprosthetic_used',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field62' => array( 'field' => 'cesarean_indication',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field63' => array( 'field' => 'wound_closed_primarily',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field64' => array( 'field' => 'wound_classification',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field65' => array( 'field' => 'case_type',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field66' => array( 'field' => 'sign_out_read_aloud',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field67' => array( 'field' => 'sign_out_in_theatre',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field68' => array( 'field' => 'unplanned_intubation',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field69' => array( 'field' => 'urgent_tracheostomy',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field70' => array( 'field' => 'urgent_central_access',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field71' => array( 'field' => 'other_crisis_occurred',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field72' => array( 'field' => 'crisis_description',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field73' => array( 'field' => 'death_in_or',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field74' => array( 'field' => 'fetal_death',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field75' => array( 'field' => 'created_at',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field76' => array( 'field' => 'updated_at',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>