<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'case_id',
'facility_id',
'country_id',
'surgery_date',
'data_type',
'data_collector_name',
'location_of_surgery',
'patient_sex',
'patient_asa_classification',
'patient_dob',
'patient_age',
'diabetes',
'hypertension',
'obese',
'malnourished',
'smoker',
'on_steroids',
'admitted_to_icu',
'hypothermic',
'preoperative_diagnosis_id',
'hours_since_injury',
'sterilizable_drill_used',
'drill_sterile_cover_used',
'holes_in_sterile_cover',
'sign_in_read_aloud',
'sign_in_completed_before_anesthesia',
'sterility_indicator_in_tray',
'sterility_indicator_color_changed',
'tray_wet_prior_to_operation',
'tray_replaced',
'gauze_count_performed',
'gauze_count_total',
'surgeon_scrubbed_hands',
'handwashing_available',
'alcohol_solution_applied',
'new_surgical_gloves_used',
'gown_sterility_indicator',
'gown_indicator_color_changed',
'gown_pack_replaced',
'gowns_or_drapes_wet',
'wet_gowns_replaced',
'holes_in_gowns',
'torn_gowns_replaced',
'holes_in_drapes',
'drapes_replaced',
'surgical_site_prep_method',
'vaginal_preparation',
'antibiotics_given',
'antibiotics_admin_location',
'antibiotics_time',
'on_scheduled_antibiotics',
'antibiotic_type',
'timeout_read_aloud',
'operation_type_announced',
'blood_loss_announced',
'estimated_blood_loss',
'time_of_incision',
'gauze_count_end_performed',
'gauze_count_end_total',
'time_dressing_applied',
'procedure_id',
'hardware_or_bioprosthetic_used',
'cesarean_indication',
'wound_closed_primarily',
'wound_classification',
'case_type',
'sign_out_read_aloud',
'sign_out_in_theatre',
'unplanned_intubation',
'urgent_tracheostomy',
'urgent_central_access',
'other_crisis_occurred',
'crisis_description',
'death_in_or',
'fetal_death',
'created_at',
'updated_at' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'case_id' => array( 'import_field' ),
'facility_id' => array( 'import_field1' ),
'country_id' => array( 'import_field2' ),
'surgery_date' => array( 'import_field3' ),
'data_type' => array( 'import_field4' ),
'data_collector_name' => array( 'import_field5' ),
'location_of_surgery' => array( 'import_field6' ),
'patient_sex' => array( 'import_field7' ),
'patient_asa_classification' => array( 'import_field8' ),
'patient_dob' => array( 'import_field9' ),
'patient_age' => array( 'import_field10' ),
'diabetes' => array( 'import_field11' ),
'hypertension' => array( 'import_field12' ),
'obese' => array( 'import_field13' ),
'malnourished' => array( 'import_field14' ),
'smoker' => array( 'import_field15' ),
'on_steroids' => array( 'import_field16' ),
'admitted_to_icu' => array( 'import_field17' ),
'hypothermic' => array( 'import_field18' ),
'preoperative_diagnosis_id' => array( 'import_field19' ),
'hours_since_injury' => array( 'import_field20' ),
'sterilizable_drill_used' => array( 'import_field21' ),
'drill_sterile_cover_used' => array( 'import_field22' ),
'holes_in_sterile_cover' => array( 'import_field23' ),
'sign_in_read_aloud' => array( 'import_field24' ),
'sign_in_completed_before_anesthesia' => array( 'import_field25' ),
'sterility_indicator_in_tray' => array( 'import_field26' ),
'sterility_indicator_color_changed' => array( 'import_field27' ),
'tray_wet_prior_to_operation' => array( 'import_field28' ),
'tray_replaced' => array( 'import_field29' ),
'gauze_count_performed' => array( 'import_field30' ),
'gauze_count_total' => array( 'import_field31' ),
'surgeon_scrubbed_hands' => array( 'import_field32' ),
'handwashing_available' => array( 'import_field33' ),
'alcohol_solution_applied' => array( 'import_field34' ),
'new_surgical_gloves_used' => array( 'import_field35' ),
'gown_sterility_indicator' => array( 'import_field36' ),
'gown_indicator_color_changed' => array( 'import_field37' ),
'gown_pack_replaced' => array( 'import_field38' ),
'gowns_or_drapes_wet' => array( 'import_field39' ),
'wet_gowns_replaced' => array( 'import_field40' ),
'holes_in_gowns' => array( 'import_field41' ),
'torn_gowns_replaced' => array( 'import_field42' ),
'holes_in_drapes' => array( 'import_field43' ),
'drapes_replaced' => array( 'import_field44' ),
'surgical_site_prep_method' => array( 'import_field45' ),
'vaginal_preparation' => array( 'import_field46' ),
'antibiotics_given' => array( 'import_field47' ),
'antibiotics_admin_location' => array( 'import_field48' ),
'antibiotics_time' => array( 'import_field49' ),
'on_scheduled_antibiotics' => array( 'import_field50' ),
'antibiotic_type' => array( 'import_field51' ),
'timeout_read_aloud' => array( 'import_field52' ),
'operation_type_announced' => array( 'import_field53' ),
'blood_loss_announced' => array( 'import_field54' ),
'estimated_blood_loss' => array( 'import_field55' ),
'time_of_incision' => array( 'import_field56' ),
'gauze_count_end_performed' => array( 'import_field57' ),
'gauze_count_end_total' => array( 'import_field58' ),
'time_dressing_applied' => array( 'import_field59' ),
'procedure_id' => array( 'import_field60' ),
'hardware_or_bioprosthetic_used' => array( 'import_field61' ),
'cesarean_indication' => array( 'import_field62' ),
'wound_closed_primarily' => array( 'import_field63' ),
'wound_classification' => array( 'import_field64' ),
'case_type' => array( 'import_field65' ),
'sign_out_read_aloud' => array( 'import_field66' ),
'sign_out_in_theatre' => array( 'import_field67' ),
'unplanned_intubation' => array( 'import_field68' ),
'urgent_tracheostomy' => array( 'import_field69' ),
'urgent_central_access' => array( 'import_field70' ),
'other_crisis_occurred' => array( 'import_field71' ),
'crisis_description' => array( 'import_field72' ),
'death_in_or' => array( 'import_field73' ),
'fetal_death' => array( 'import_field74' ),
'created_at' => array( 'import_field75' ),
'updated_at' => array( 'import_field76' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field52',
'import_field53',
'import_field54',
'import_field55',
'import_field56',
'import_field57',
'import_field58',
'import_field59',
'import_field60',
'import_field61',
'import_field62',
'import_field63',
'import_field64',
'import_field65',
'import_field66',
'import_field67',
'import_field68',
'import_field69',
'import_field70',
'import_field71',
'import_field72',
'import_field73',
'import_field74',
'import_field75',
'import_field76' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field31' => 'grid',
'import_field32' => 'grid',
'import_field33' => 'grid',
'import_field34' => 'grid',
'import_field35' => 'grid',
'import_field36' => 'grid',
'import_field37' => 'grid',
'import_field38' => 'grid',
'import_field39' => 'grid',
'import_field40' => 'grid',
'import_field41' => 'grid',
'import_field42' => 'grid',
'import_field43' => 'grid',
'import_field44' => 'grid',
'import_field45' => 'grid',
'import_field46' => 'grid',
'import_field47' => 'grid',
'import_field48' => 'grid',
'import_field49' => 'grid',
'import_field50' => 'grid',
'import_field51' => 'grid',
'import_field52' => 'grid',
'import_field53' => 'grid',
'import_field54' => 'grid',
'import_field55' => 'grid',
'import_field56' => 'grid',
'import_field57' => 'grid',
'import_field58' => 'grid',
'import_field59' => 'grid',
'import_field60' => 'grid',
'import_field61' => 'grid',
'import_field62' => 'grid',
'import_field63' => 'grid',
'import_field64' => 'grid',
'import_field65' => 'grid',
'import_field66' => 'grid',
'import_field67' => 'grid',
'import_field68' => 'grid',
'import_field69' => 'grid',
'import_field70' => 'grid',
'import_field71' => 'grid',
'import_field72' => 'grid',
'import_field73' => 'grid',
'import_field74' => 'grid',
'import_field75' => 'grid',
'import_field76' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field52',
'import_field53',
'import_field54',
'import_field55',
'import_field56',
'import_field57',
'import_field58',
'import_field59',
'import_field60',
'import_field61',
'import_field62',
'import_field63',
'import_field64',
'import_field65',
'import_field66',
'import_field67',
'import_field68',
'import_field69',
'import_field70',
'import_field71',
'import_field72',
'import_field73',
'import_field74',
'import_field75',
'import_field76' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field52',
'import_field53',
'import_field54',
'import_field55',
'import_field56',
'import_field57',
'import_field58',
'import_field59',
'import_field60',
'import_field61',
'import_field62',
'import_field63',
'import_field64',
'import_field65',
'import_field66',
'import_field67',
'import_field68',
'import_field69',
'import_field70',
'import_field71',
'import_field72',
'import_field73',
'import_field74',
'import_field75',
'import_field76' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'case_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'facility_id',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'country_id',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'surgery_date',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'data_type',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'data_collector_name',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'location_of_surgery',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'patient_sex',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'patient_asa_classification',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'patient_dob',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'patient_age',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'diabetes',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'hypertension',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'obese',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'malnourished',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'smoker',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'on_steroids',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'admitted_to_icu',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'hypothermic',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'preoperative_diagnosis_id',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'hours_since_injury',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'sterilizable_drill_used',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'drill_sterile_cover_used',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'holes_in_sterile_cover',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'sign_in_read_aloud',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'sign_in_completed_before_anesthesia',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'sterility_indicator_in_tray',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'sterility_indicator_color_changed',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'tray_wet_prior_to_operation',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'tray_replaced',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'gauze_count_performed',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'gauze_count_total',
'type' => 'import_field' ),
'import_field32' => array( 'field' => 'surgeon_scrubbed_hands',
'type' => 'import_field' ),
'import_field33' => array( 'field' => 'handwashing_available',
'type' => 'import_field' ),
'import_field34' => array( 'field' => 'alcohol_solution_applied',
'type' => 'import_field' ),
'import_field35' => array( 'field' => 'new_surgical_gloves_used',
'type' => 'import_field' ),
'import_field36' => array( 'field' => 'gown_sterility_indicator',
'type' => 'import_field' ),
'import_field37' => array( 'field' => 'gown_indicator_color_changed',
'type' => 'import_field' ),
'import_field38' => array( 'field' => 'gown_pack_replaced',
'type' => 'import_field' ),
'import_field39' => array( 'field' => 'gowns_or_drapes_wet',
'type' => 'import_field' ),
'import_field40' => array( 'field' => 'wet_gowns_replaced',
'type' => 'import_field' ),
'import_field41' => array( 'field' => 'holes_in_gowns',
'type' => 'import_field' ),
'import_field42' => array( 'field' => 'torn_gowns_replaced',
'type' => 'import_field' ),
'import_field43' => array( 'field' => 'holes_in_drapes',
'type' => 'import_field' ),
'import_field44' => array( 'field' => 'drapes_replaced',
'type' => 'import_field' ),
'import_field45' => array( 'field' => 'surgical_site_prep_method',
'type' => 'import_field' ),
'import_field46' => array( 'field' => 'vaginal_preparation',
'type' => 'import_field' ),
'import_field47' => array( 'field' => 'antibiotics_given',
'type' => 'import_field' ),
'import_field48' => array( 'field' => 'antibiotics_admin_location',
'type' => 'import_field' ),
'import_field49' => array( 'field' => 'antibiotics_time',
'type' => 'import_field' ),
'import_field50' => array( 'field' => 'on_scheduled_antibiotics',
'type' => 'import_field' ),
'import_field51' => array( 'field' => 'antibiotic_type',
'type' => 'import_field' ),
'import_field52' => array( 'field' => 'timeout_read_aloud',
'type' => 'import_field' ),
'import_field53' => array( 'field' => 'operation_type_announced',
'type' => 'import_field' ),
'import_field54' => array( 'field' => 'blood_loss_announced',
'type' => 'import_field' ),
'import_field55' => array( 'field' => 'estimated_blood_loss',
'type' => 'import_field' ),
'import_field56' => array( 'field' => 'time_of_incision',
'type' => 'import_field' ),
'import_field57' => array( 'field' => 'gauze_count_end_performed',
'type' => 'import_field' ),
'import_field58' => array( 'field' => 'gauze_count_end_total',
'type' => 'import_field' ),
'import_field59' => array( 'field' => 'time_dressing_applied',
'type' => 'import_field' ),
'import_field60' => array( 'field' => 'procedure_id',
'type' => 'import_field' ),
'import_field61' => array( 'field' => 'hardware_or_bioprosthetic_used',
'type' => 'import_field' ),
'import_field62' => array( 'field' => 'cesarean_indication',
'type' => 'import_field' ),
'import_field63' => array( 'field' => 'wound_closed_primarily',
'type' => 'import_field' ),
'import_field64' => array( 'field' => 'wound_classification',
'type' => 'import_field' ),
'import_field65' => array( 'field' => 'case_type',
'type' => 'import_field' ),
'import_field66' => array( 'field' => 'sign_out_read_aloud',
'type' => 'import_field' ),
'import_field67' => array( 'field' => 'sign_out_in_theatre',
'type' => 'import_field' ),
'import_field68' => array( 'field' => 'unplanned_intubation',
'type' => 'import_field' ),
'import_field69' => array( 'field' => 'urgent_tracheostomy',
'type' => 'import_field' ),
'import_field70' => array( 'field' => 'urgent_central_access',
'type' => 'import_field' ),
'import_field71' => array( 'field' => 'other_crisis_occurred',
'type' => 'import_field' ),
'import_field72' => array( 'field' => 'crisis_description',
'type' => 'import_field' ),
'import_field73' => array( 'field' => 'death_in_or',
'type' => 'import_field' ),
'import_field74' => array( 'field' => 'fetal_death',
'type' => 'import_field' ),
'import_field75' => array( 'field' => 'created_at',
'type' => 'import_field' ),
'import_field76' => array( 'field' => 'updated_at',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>