<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'training_id',
'course_name',
'training_type',
'training_approach',
'program',
'quarter',
'start_date',
'end_date',
'facility_name',
'country_name',
'region_name',
'ceu_points',
'num_participants',
'avg_pre_test_score',
'avg_post_test_score',
'trainers',
'partners',
'languages',
'remarks' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'training_id' => array( 'import_field' ),
'course_name' => array( 'import_field1' ),
'training_type' => array( 'import_field2' ),
'training_approach' => array( 'import_field3' ),
'program' => array( 'import_field4' ),
'quarter' => array( 'import_field5' ),
'start_date' => array( 'import_field6' ),
'end_date' => array( 'import_field7' ),
'facility_name' => array( 'import_field8' ),
'country_name' => array( 'import_field9' ),
'region_name' => array( 'import_field10' ),
'ceu_points' => array( 'import_field11' ),
'num_participants' => array( 'import_field12' ),
'avg_pre_test_score' => array( 'import_field13' ),
'avg_post_test_score' => array( 'import_field14' ),
'trainers' => array( 'import_field15' ),
'partners' => array( 'import_field16' ),
'languages' => array( 'import_field17' ),
'remarks' => array( 'import_field18' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'training_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'course_name',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'training_type',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'training_approach',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'program',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'quarter',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'start_date',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'end_date',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'facility_name',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'country_name',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'region_name',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'ceu_points',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'num_participants',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'avg_pre_test_score',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'avg_post_test_score',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'trainers',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'partners',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'languages',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'remarks',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>