<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'participant_id',
'first_name',
'last_name',
'sex_id',
'role_id',
'facility_id',
'phone',
'email',
'country_id',
'training_date',
'ceu_points',
'pre_test_score',
'post_test_score',
'created_at',
'updated_at',
'venue_id',
'title_salutation',
'middle_name' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'participant_id' => array( 'import_field' ),
'first_name' => array( 'import_field2' ),
'last_name' => array( 'import_field3' ),
'sex_id' => array( 'import_field4' ),
'role_id' => array( 'import_field5' ),
'facility_id' => array( 'import_field6' ),
'phone' => array( 'import_field7' ),
'email' => array( 'import_field8' ),
'country_id' => array( 'import_field9' ),
'venue_id' => array( 'import_field10' ),
'training_date' => array( 'import_field11' ),
'ceu_points' => array( 'import_field13' ),
'pre_test_score' => array( 'import_field14' ),
'post_test_score' => array( 'import_field15' ),
'created_at' => array( 'import_field16' ),
'updated_at' => array( 'import_field17' ),
'title_salutation' => array( 'import_field12' ),
'middle_name' => array( 'import_field18' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field11',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field10',
'import_field12',
'import_field18' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field11' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field10' => 'grid',
'import_field12' => 'grid',
'import_field18' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field12',
'import_field18' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field11',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field10',
'import_field12',
'import_field18' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'participant_id',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'first_name',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'last_name',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'sex_id',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'role_id',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'facility_id',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'phone',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'email',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'country_id',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'venue_id',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'training_date',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'ceu_points',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'pre_test_score',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'post_test_score',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'created_at',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'updated_at',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'title_salutation',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'middle_name',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>