<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'attendance_id',
'day_number',
'attended',
'attendance_date',
'notes',
'recorded_at',
'recorded_by',
'participation_id',
'participant_full_name',
'sex_name',
'facility_name',
'role_name',
'training_id',
'course_name',
'program_name',
'program_id',
'quarter',
'start_date',
'end_date',
'training_type',
'training_approach',
'host_country',
'host_region',
'venue_name',
'partner_name',
'training_lead_name' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'attendance_id' => array( 'import_field' ),
'participation_id' => array( 'import_field1' ),
'day_number' => array( 'import_field2' ),
'attended' => array( 'import_field3' ),
'attendance_date' => array( 'import_field4' ),
'notes' => array( 'import_field5' ),
'recorded_at' => array( 'import_field6' ),
'recorded_by' => array( 'import_field7' ),
'participant_full_name' => array( 'import_field8' ),
'sex_name' => array( 'import_field9' ),
'facility_name' => array( 'import_field10' ),
'role_name' => array( 'import_field11' ),
'training_id' => array( 'import_field12' ),
'course_name' => array( 'import_field13' ),
'program_name' => array( 'import_field14' ),
'program_id' => array( 'import_field15' ),
'quarter' => array( 'import_field16' ),
'start_date' => array( 'import_field17' ),
'end_date' => array( 'import_field18' ),
'training_type' => array( 'import_field19' ),
'training_approach' => array( 'import_field20' ),
'host_country' => array( 'import_field21' ),
'host_region' => array( 'import_field22' ),
'venue_name' => array( 'import_field23' ),
'partner_name' => array( 'import_field24' ),
'training_lead_name' => array( 'import_field25' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field1',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field1' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field1',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'attendance_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'participation_id',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'day_number',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'attended',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'attendance_date',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'notes',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'recorded_at',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'recorded_by',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'participant_full_name',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'sex_name',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'facility_name',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'role_name',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'training_id',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'course_name',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'program_name',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'program_id',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'quarter',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'start_date',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'end_date',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'training_type',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'training_approach',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'host_country',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'host_region',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'venue_name',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'partner_name',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'training_lead_name',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>