<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'totals' => array( 'training_id' => array( 'totalsType' => '' ),
'course_name' => array( 'totalsType' => '' ),
'training_type' => array( 'totalsType' => '' ),
'training_approach' => array( 'totalsType' => '' ),
'program' => array( 'totalsType' => '' ),
'quarter' => array( 'totalsType' => '' ),
'start_date' => array( 'totalsType' => '' ),
'end_date' => array( 'totalsType' => '' ),
'facility_name' => array( 'totalsType' => '' ),
'country_name' => array( 'totalsType' => '' ),
'region_name' => array( 'totalsType' => '' ),
'ceu_points' => array( 'totalsType' => '' ),
'num_participants' => array( 'totalsType' => '' ),
'avg_pre_test_score' => array( 'totalsType' => '' ),
'avg_post_test_score' => array( 'totalsType' => '' ),
'trainers' => array( 'totalsType' => '' ),
'partners' => array( 'totalsType' => '' ),
'languages' => array( 'totalsType' => '' ),
'remarks' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'training_id',
'course_name',
'training_type',
'training_approach',
'program',
'quarter',
'start_date',
'end_date',
'facility_name',
'country_name',
'region_name',
'ceu_points',
'num_participants',
'avg_pre_test_score',
'avg_post_test_score',
'trainers',
'partners',
'languages',
'remarks' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'training_id' => array( 'simple_grid_field',
'simple_grid_field19' ),
'course_name' => array( 'simple_grid_field1',
'simple_grid_field20' ),
'training_type' => array( 'simple_grid_field2',
'simple_grid_field21' ),
'training_approach' => array( 'simple_grid_field3',
'simple_grid_field22' ),
'program' => array( 'simple_grid_field4',
'simple_grid_field23' ),
'quarter' => array( 'simple_grid_field5',
'simple_grid_field24' ),
'start_date' => array( 'simple_grid_field6',
'simple_grid_field25' ),
'end_date' => array( 'simple_grid_field7',
'simple_grid_field26' ),
'facility_name' => array( 'simple_grid_field8',
'simple_grid_field27' ),
'country_name' => array( 'simple_grid_field9',
'simple_grid_field28' ),
'region_name' => array( 'simple_grid_field10',
'simple_grid_field29' ),
'ceu_points' => array( 'simple_grid_field11',
'simple_grid_field30' ),
'num_participants' => array( 'simple_grid_field12',
'simple_grid_field31' ),
'avg_pre_test_score' => array( 'simple_grid_field13',
'simple_grid_field32' ),
'avg_post_test_score' => array( 'simple_grid_field14',
'simple_grid_field33' ),
'trainers' => array( 'simple_grid_field15',
'simple_grid_field34' ),
'partners' => array( 'simple_grid_field16',
'simple_grid_field35' ),
'languages' => array( 'simple_grid_field17',
'simple_grid_field36' ),
'remarks' => array( 'simple_grid_field18',
'simple_grid_field37' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ),
'top' => array( 'print_header',
'print_subheader' ),
'grid' => array( 'simple_grid_field19',
'simple_grid_field',
'simple_grid_field20',
'simple_grid_field1',
'simple_grid_field21',
'simple_grid_field2',
'simple_grid_field22',
'simple_grid_field3',
'simple_grid_field23',
'simple_grid_field4',
'simple_grid_field24',
'simple_grid_field5',
'simple_grid_field25',
'simple_grid_field6',
'simple_grid_field26',
'simple_grid_field7',
'simple_grid_field27',
'simple_grid_field8',
'simple_grid_field28',
'simple_grid_field9',
'simple_grid_field29',
'simple_grid_field10',
'simple_grid_field30',
'simple_grid_field11',
'simple_grid_field31',
'simple_grid_field12',
'simple_grid_field32',
'simple_grid_field13',
'simple_grid_field33',
'simple_grid_field14',
'simple_grid_field34',
'simple_grid_field15',
'simple_grid_field35',
'simple_grid_field16',
'simple_grid_field36',
'simple_grid_field17',
'simple_grid_field37',
'simple_grid_field18' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_pages' => 'above-grid',
'print_header' => 'top',
'print_subheader' => 'top',
'simple_grid_field19' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field34' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field37' => 'grid',
'simple_grid_field18' => 'grid' ),
'itemLocations' => array( 'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field37' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'grid_field' => array( 'simple_grid_field',
'simple_grid_field1',
'simple_grid_field2',
'simple_grid_field3',
'simple_grid_field4',
'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field7',
'simple_grid_field8',
'simple_grid_field9',
'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field12',
'simple_grid_field13',
'simple_grid_field14',
'simple_grid_field15',
'simple_grid_field16',
'simple_grid_field17',
'simple_grid_field18' ),
'grid_field_label' => array( 'simple_grid_field19',
'simple_grid_field20',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field23',
'simple_grid_field24',
'simple_grid_field25',
'simple_grid_field26',
'simple_grid_field27',
'simple_grid_field28',
'simple_grid_field29',
'simple_grid_field30',
'simple_grid_field31',
'simple_grid_field32',
'simple_grid_field33',
'simple_grid_field34',
'simple_grid_field35',
'simple_grid_field36',
'simple_grid_field37' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'training_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'course_name_fieldheadercolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'training_type_fieldheadercolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'training_approach_fieldheadercolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'program_fieldheadercolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'quarter_fieldheadercolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'start_date_fieldheadercolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'end_date_fieldheadercolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'facility_name_fieldheadercolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'country_name_fieldheadercolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'region_name_fieldheadercolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'ceu_points_fieldheadercolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'num_participants_fieldheadercolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'avg_pre_test_score_fieldheadercolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'avg_post_test_score_fieldheadercolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'trainers_fieldheadercolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'partners_fieldheadercolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'languages_fieldheadercolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'remarks_fieldheadercolumn' ),
'items' => array( 'simple_grid_field37' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'training_id_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'course_name_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'training_type_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'training_approach_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'program_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'quarter_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'start_date_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'end_date_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'facility_name_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'country_name_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'region_name_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'ceu_points_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'num_participants_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'avg_pre_test_score_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'avg_post_test_score_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'trainers_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'partners_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'languages_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'remarks_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 19,
'height' => 3 ) ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'print',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'print',
'type' => 'print',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field18' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field18' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field18' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'training_id',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'training_id',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'course_name',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'course_name',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'training_type',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'training_type',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'training_approach',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'training_approach',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'program',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'program',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'quarter',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'quarter',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field25' ),
'field' => 'start_date',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'start_date',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'end_date',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'end_date',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'facility_name',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'facility_name',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'country_name',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'country_name',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'region_name',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'region_name',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'ceu_points',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'ceu_points',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field31' ),
'field' => 'num_participants',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'num_participants',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field32' ),
'field' => 'avg_pre_test_score',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'avg_pre_test_score',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field33' ),
'field' => 'avg_post_test_score',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'avg_post_test_score',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field34' ),
'field' => 'trainers',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'trainers',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field35' ),
'field' => 'partners',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'partners',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field36' ),
'field' => 'languages',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'languages',
'columnName' => 'field' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field37' ),
'field' => 'remarks',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'remarks',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'simple_grid_field' => array( 'field' => 'training_id',
'type' => 'grid_field' ),
'simple_grid_field19' => array( 'type' => 'grid_field_label',
'field' => 'training_id' ),
'simple_grid_field1' => array( 'field' => 'course_name',
'type' => 'grid_field' ),
'simple_grid_field20' => array( 'type' => 'grid_field_label',
'field' => 'course_name' ),
'simple_grid_field2' => array( 'field' => 'training_type',
'type' => 'grid_field' ),
'simple_grid_field21' => array( 'type' => 'grid_field_label',
'field' => 'training_type' ),
'simple_grid_field3' => array( 'field' => 'training_approach',
'type' => 'grid_field' ),
'simple_grid_field22' => array( 'type' => 'grid_field_label',
'field' => 'training_approach' ),
'simple_grid_field4' => array( 'field' => 'program',
'type' => 'grid_field' ),
'simple_grid_field23' => array( 'type' => 'grid_field_label',
'field' => 'program' ),
'simple_grid_field5' => array( 'field' => 'quarter',
'type' => 'grid_field' ),
'simple_grid_field24' => array( 'type' => 'grid_field_label',
'field' => 'quarter' ),
'simple_grid_field6' => array( 'field' => 'start_date',
'type' => 'grid_field' ),
'simple_grid_field25' => array( 'type' => 'grid_field_label',
'field' => 'start_date' ),
'simple_grid_field7' => array( 'field' => 'end_date',
'type' => 'grid_field' ),
'simple_grid_field26' => array( 'type' => 'grid_field_label',
'field' => 'end_date' ),
'simple_grid_field8' => array( 'field' => 'facility_name',
'type' => 'grid_field' ),
'simple_grid_field27' => array( 'type' => 'grid_field_label',
'field' => 'facility_name' ),
'simple_grid_field9' => array( 'field' => 'country_name',
'type' => 'grid_field' ),
'simple_grid_field28' => array( 'type' => 'grid_field_label',
'field' => 'country_name' ),
'simple_grid_field10' => array( 'field' => 'region_name',
'type' => 'grid_field' ),
'simple_grid_field29' => array( 'type' => 'grid_field_label',
'field' => 'region_name' ),
'simple_grid_field11' => array( 'field' => 'ceu_points',
'type' => 'grid_field' ),
'simple_grid_field30' => array( 'type' => 'grid_field_label',
'field' => 'ceu_points' ),
'simple_grid_field12' => array( 'field' => 'num_participants',
'type' => 'grid_field' ),
'simple_grid_field31' => array( 'type' => 'grid_field_label',
'field' => 'num_participants' ),
'simple_grid_field13' => array( 'field' => 'avg_pre_test_score',
'type' => 'grid_field' ),
'simple_grid_field32' => array( 'type' => 'grid_field_label',
'field' => 'avg_pre_test_score' ),
'simple_grid_field14' => array( 'field' => 'avg_post_test_score',
'type' => 'grid_field' ),
'simple_grid_field33' => array( 'type' => 'grid_field_label',
'field' => 'avg_post_test_score' ),
'simple_grid_field15' => array( 'field' => 'trainers',
'type' => 'grid_field' ),
'simple_grid_field34' => array( 'type' => 'grid_field_label',
'field' => 'trainers' ),
'simple_grid_field16' => array( 'field' => 'partners',
'type' => 'grid_field' ),
'simple_grid_field35' => array( 'type' => 'grid_field_label',
'field' => 'partners' ),
'simple_grid_field17' => array( 'field' => 'languages',
'type' => 'grid_field' ),
'simple_grid_field36' => array( 'type' => 'grid_field_label',
'field' => 'languages' ),
'simple_grid_field18' => array( 'field' => 'remarks',
'type' => 'grid_field' ),
'simple_grid_field37' => array( 'type' => 'grid_field_label',
'field' => 'remarks' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>