<?php
			$optionsArray = array( 'totals' => array( 'training_id' => array( 'totalsType' => '' ),
'course_name' => array( 'totalsType' => '' ),
'training_type' => array( 'totalsType' => '' ),
'training_approach' => array( 'totalsType' => '' ),
'program' => array( 'totalsType' => '' ),
'quarter' => array( 'totalsType' => '' ),
'start_date' => array( 'totalsType' => '' ),
'end_date' => array( 'totalsType' => '' ),
'facility_name' => array( 'totalsType' => '' ),
'country_name' => array( 'totalsType' => '' ),
'region_name' => array( 'totalsType' => '' ),
'ceu_points' => array( 'totalsType' => '' ),
'num_participants' => array( 'totalsType' => '' ),
'avg_pre_test_score' => array( 'totalsType' => '' ),
'avg_post_test_score' => array( 'totalsType' => '' ),
'trainers' => array( 'totalsType' => '' ),
'partners' => array( 'totalsType' => '' ),
'languages' => array( 'totalsType' => '' ),
'remarks' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'training_id',
'course_name',
'training_type',
'training_approach',
'program',
'quarter',
'start_date',
'end_date',
'facility_name',
'country_name',
'region_name',
'ceu_points',
'num_participants',
'avg_pre_test_score',
'avg_post_test_score',
'trainers',
'partners',
'languages',
'remarks' ),
'exportFields' => array( 'training_id',
'course_name',
'training_type',
'training_approach',
'program',
'quarter',
'start_date',
'end_date',
'facility_name',
'country_name',
'region_name',
'ceu_points',
'num_participants',
'avg_pre_test_score',
'avg_post_test_score',
'trainers',
'partners',
'languages',
'remarks' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'training_id' => array( 'export_field' ),
'course_name' => array( 'export_field1' ),
'training_type' => array( 'export_field2' ),
'training_approach' => array( 'export_field3' ),
'program' => array( 'export_field4' ),
'quarter' => array( 'export_field5' ),
'start_date' => array( 'export_field6' ),
'end_date' => array( 'export_field7' ),
'facility_name' => array( 'export_field8' ),
'country_name' => array( 'export_field9' ),
'region_name' => array( 'export_field10' ),
'ceu_points' => array( 'export_field11' ),
'num_participants' => array( 'export_field12' ),
'avg_pre_test_score' => array( 'export_field13' ),
'avg_post_test_score' => array( 'export_field14' ),
'trainers' => array( 'export_field15' ),
'partners' => array( 'export_field16' ),
'languages' => array( 'export_field17' ),
'remarks' => array( 'export_field18' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'training_id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'course_name',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'training_type',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'training_approach',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'program',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'quarter',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'start_date',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'end_date',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'facility_name',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'country_name',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'region_name',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'ceu_points',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'num_participants',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'avg_pre_test_score',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'avg_post_test_score',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'trainers',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'partners',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'languages',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'remarks',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>