<?php
			$optionsArray = array( 'totals' => array( 'attendance_id' => array( 'totalsType' => '' ),
'day_number' => array( 'totalsType' => '' ),
'attended' => array( 'totalsType' => '' ),
'attendance_date' => array( 'totalsType' => '' ),
'notes' => array( 'totalsType' => '' ),
'recorded_at' => array( 'totalsType' => '' ),
'recorded_by' => array( 'totalsType' => '' ),
'participation_id' => array( 'totalsType' => '' ),
'participant_full_name' => array( 'totalsType' => '' ),
'sex_name' => array( 'totalsType' => '' ),
'facility_name' => array( 'totalsType' => '' ),
'role_name' => array( 'totalsType' => '' ),
'training_id' => array( 'totalsType' => '' ),
'course_name' => array( 'totalsType' => '' ),
'program_name' => array( 'totalsType' => '' ),
'program_id' => array( 'totalsType' => '' ),
'quarter' => array( 'totalsType' => '' ),
'start_date' => array( 'totalsType' => '' ),
'end_date' => array( 'totalsType' => '' ),
'training_type' => array( 'totalsType' => '' ),
'training_approach' => array( 'totalsType' => '' ),
'host_country' => array( 'totalsType' => '' ),
'host_region' => array( 'totalsType' => '' ),
'venue_name' => array( 'totalsType' => '' ),
'partner_name' => array( 'totalsType' => '' ),
'training_lead_name' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'attendance_id',
'participation_id',
'day_number',
'attended',
'attendance_date',
'notes',
'recorded_at',
'recorded_by',
'participant_full_name',
'sex_name',
'facility_name',
'role_name',
'training_id',
'course_name',
'program_name',
'program_id',
'quarter',
'start_date',
'end_date',
'training_type',
'training_approach',
'host_country',
'host_region',
'venue_name',
'partner_name',
'training_lead_name' ),
'exportFields' => array( 'attendance_id',
'day_number',
'attended',
'attendance_date',
'notes',
'recorded_at',
'recorded_by',
'participation_id',
'participant_full_name',
'sex_name',
'facility_name',
'role_name',
'training_id',
'course_name',
'program_name',
'program_id',
'quarter',
'start_date',
'end_date',
'training_type',
'training_approach',
'host_country',
'host_region',
'venue_name',
'partner_name',
'training_lead_name' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'attendance_id' => array( 'export_field' ),
'participation_id' => array( 'export_field1' ),
'day_number' => array( 'export_field2' ),
'attended' => array( 'export_field3' ),
'attendance_date' => array( 'export_field4' ),
'notes' => array( 'export_field5' ),
'recorded_at' => array( 'export_field6' ),
'recorded_by' => array( 'export_field7' ),
'participant_full_name' => array( 'export_field8' ),
'sex_name' => array( 'export_field9' ),
'facility_name' => array( 'export_field10' ),
'role_name' => array( 'export_field11' ),
'training_id' => array( 'export_field12' ),
'course_name' => array( 'export_field13' ),
'program_name' => array( 'export_field14' ),
'program_id' => array( 'export_field15' ),
'quarter' => array( 'export_field16' ),
'start_date' => array( 'export_field17' ),
'end_date' => array( 'export_field18' ),
'training_type' => array( 'export_field19' ),
'training_approach' => array( 'export_field20' ),
'host_country' => array( 'export_field21' ),
'host_region' => array( 'export_field22' ),
'venue_name' => array( 'export_field23' ),
'partner_name' => array( 'export_field24' ),
'training_lead_name' => array( 'export_field25' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field1',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field1' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field1',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'attendance_id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'participation_id',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'day_number',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'attended',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'attendance_date',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'notes',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'recorded_at',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'recorded_by',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'participant_full_name',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'sex_name',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'facility_name',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'role_name',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'training_id',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'course_name',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'program_name',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'program_id',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'quarter',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'start_date',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'end_date',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'training_type',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'training_approach',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'host_country',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'host_region',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'venue_name',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'partner_name',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'training_lead_name',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>