<?php
			$optionsArray = array( 'totals' => array( 'venue_id' => array( 'totalsType' => '' ),
'venue_name' => array( 'totalsType' => '' ),
'facility_id' => array( 'totalsType' => '' ),
'address_line1' => array( 'totalsType' => '' ),
'address_line2' => array( 'totalsType' => '' ),
'city' => array( 'totalsType' => '' ),
'state_province' => array( 'totalsType' => '' ),
'postal_code' => array( 'totalsType' => '' ),
'country_id' => array( 'totalsType' => '' ),
'capacity' => array( 'totalsType' => '' ),
'room_type' => array( 'totalsType' => '' ),
'amenities' => array( 'totalsType' => '' ),
'is_active' => array( 'totalsType' => '' ),
'created_at' => array( 'totalsType' => '' ),
'updated_at' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'venue_id',
'venue_name',
'facility_id',
'address_line1',
'address_line2',
'city',
'state_province',
'postal_code',
'country_id',
'capacity',
'room_type',
'amenities',
'is_active',
'created_at',
'updated_at' ),
'exportFields' => array( 'venue_id',
'venue_name',
'facility_id',
'address_line1',
'address_line2',
'city',
'state_province',
'postal_code',
'country_id',
'capacity',
'room_type',
'amenities',
'is_active',
'created_at',
'updated_at' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'venue_id' => array( 'export_field' ),
'venue_name' => array( 'export_field1' ),
'facility_id' => array( 'export_field2' ),
'address_line1' => array( 'export_field3' ),
'address_line2' => array( 'export_field4' ),
'city' => array( 'export_field5' ),
'state_province' => array( 'export_field6' ),
'postal_code' => array( 'export_field7' ),
'country_id' => array( 'export_field8' ),
'capacity' => array( 'export_field9' ),
'room_type' => array( 'export_field10' ),
'amenities' => array( 'export_field11' ),
'is_active' => array( 'export_field12' ),
'created_at' => array( 'export_field13' ),
'updated_at' => array( 'export_field14' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'venue_id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'venue_name',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'facility_id',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'address_line1',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'address_line2',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'city',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'state_province',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'postal_code',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'country_id',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'capacity',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'room_type',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'amenities',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'is_active',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'created_at',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'updated_at',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>