<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'ward_round_id',
'case_id',
'facility_id',
'admission_date',
'rounding_date',
'data_collector_name',
'ward_name',
'ward_transfer',
'postop_day',
'dressing_not_removed',
'wound_clean_and_healthy',
'stitches_removed_or_wound_opened',
'wound_opened_spontaneously',
'pus_draining',
'abscess_present',
'redness_around_wound',
'bleeding',
'new_dressing',
'new_dressing_type',
'fever',
'on_antibiotics',
'antibiotics_prescribed',
'ssi_diagnosed_on_reoperation',
'returned_to_or',
'return_or_procedure',
'disposition',
'planned_reoperation',
'other_complications',
'endometritis',
'urinary_tract_infection',
'pneumonia',
'other_complication_description',
'eschar',
'discharged_today',
'discharge_date',
'death_in_ward',
'neonatal_death',
'created_at',
'updated_at' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'ward_round_id' => array( 'import_field' ),
'case_id' => array( 'import_field1' ),
'facility_id' => array( 'import_field2' ),
'admission_date' => array( 'import_field3' ),
'rounding_date' => array( 'import_field4' ),
'data_collector_name' => array( 'import_field5' ),
'ward_name' => array( 'import_field6' ),
'ward_transfer' => array( 'import_field7' ),
'postop_day' => array( 'import_field8' ),
'dressing_not_removed' => array( 'import_field9' ),
'wound_clean_and_healthy' => array( 'import_field10' ),
'stitches_removed_or_wound_opened' => array( 'import_field11' ),
'wound_opened_spontaneously' => array( 'import_field12' ),
'pus_draining' => array( 'import_field13' ),
'abscess_present' => array( 'import_field14' ),
'redness_around_wound' => array( 'import_field15' ),
'bleeding' => array( 'import_field16' ),
'new_dressing' => array( 'import_field17' ),
'new_dressing_type' => array( 'import_field18' ),
'fever' => array( 'import_field19' ),
'on_antibiotics' => array( 'import_field20' ),
'antibiotics_prescribed' => array( 'import_field21' ),
'ssi_diagnosed_on_reoperation' => array( 'import_field22' ),
'returned_to_or' => array( 'import_field23' ),
'return_or_procedure' => array( 'import_field24' ),
'disposition' => array( 'import_field25' ),
'planned_reoperation' => array( 'import_field26' ),
'other_complications' => array( 'import_field27' ),
'endometritis' => array( 'import_field28' ),
'urinary_tract_infection' => array( 'import_field29' ),
'pneumonia' => array( 'import_field30' ),
'other_complication_description' => array( 'import_field31' ),
'eschar' => array( 'import_field32' ),
'discharged_today' => array( 'import_field33' ),
'discharge_date' => array( 'import_field34' ),
'death_in_ward' => array( 'import_field35' ),
'neonatal_death' => array( 'import_field36' ),
'created_at' => array( 'import_field37' ),
'updated_at' => array( 'import_field38' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field31' => 'grid',
'import_field32' => 'grid',
'import_field33' => 'grid',
'import_field34' => 'grid',
'import_field35' => 'grid',
'import_field36' => 'grid',
'import_field37' => 'grid',
'import_field38' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'ward_round_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'case_id',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'facility_id',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'admission_date',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'rounding_date',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'data_collector_name',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'ward_name',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'ward_transfer',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'postop_day',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'dressing_not_removed',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'wound_clean_and_healthy',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'stitches_removed_or_wound_opened',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'wound_opened_spontaneously',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'pus_draining',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'abscess_present',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'redness_around_wound',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'bleeding',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'new_dressing',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'new_dressing_type',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'fever',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'on_antibiotics',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'antibiotics_prescribed',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'ssi_diagnosed_on_reoperation',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'returned_to_or',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'return_or_procedure',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'disposition',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'planned_reoperation',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'other_complications',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'endometritis',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'urinary_tract_infection',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'pneumonia',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'other_complication_description',
'type' => 'import_field' ),
'import_field32' => array( 'field' => 'eschar',
'type' => 'import_field' ),
'import_field33' => array( 'field' => 'discharged_today',
'type' => 'import_field' ),
'import_field34' => array( 'field' => 'discharge_date',
'type' => 'import_field' ),
'import_field35' => array( 'field' => 'death_in_ward',
'type' => 'import_field' ),
'import_field36' => array( 'field' => 'neonatal_death',
'type' => 'import_field' ),
'import_field37' => array( 'field' => 'created_at',
'type' => 'import_field' ),
'import_field38' => array( 'field' => 'updated_at',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>