<?php
			$optionsArray = array( 'totals' => array( 'ward_round_id' => array( 'totalsType' => '' ),
'case_id' => array( 'totalsType' => '' ),
'facility_id' => array( 'totalsType' => '' ),
'admission_date' => array( 'totalsType' => '' ),
'rounding_date' => array( 'totalsType' => '' ),
'data_collector_name' => array( 'totalsType' => '' ),
'ward_name' => array( 'totalsType' => '' ),
'ward_transfer' => array( 'totalsType' => '' ),
'postop_day' => array( 'totalsType' => '' ),
'dressing_not_removed' => array( 'totalsType' => '' ),
'wound_clean_and_healthy' => array( 'totalsType' => '' ),
'stitches_removed_or_wound_opened' => array( 'totalsType' => '' ),
'wound_opened_spontaneously' => array( 'totalsType' => '' ),
'pus_draining' => array( 'totalsType' => '' ),
'abscess_present' => array( 'totalsType' => '' ),
'redness_around_wound' => array( 'totalsType' => '' ),
'bleeding' => array( 'totalsType' => '' ),
'new_dressing' => array( 'totalsType' => '' ),
'new_dressing_type' => array( 'totalsType' => '' ),
'fever' => array( 'totalsType' => '' ),
'on_antibiotics' => array( 'totalsType' => '' ),
'antibiotics_prescribed' => array( 'totalsType' => '' ),
'ssi_diagnosed_on_reoperation' => array( 'totalsType' => '' ),
'returned_to_or' => array( 'totalsType' => '' ),
'return_or_procedure' => array( 'totalsType' => '' ),
'disposition' => array( 'totalsType' => '' ),
'planned_reoperation' => array( 'totalsType' => '' ),
'other_complications' => array( 'totalsType' => '' ),
'endometritis' => array( 'totalsType' => '' ),
'urinary_tract_infection' => array( 'totalsType' => '' ),
'pneumonia' => array( 'totalsType' => '' ),
'other_complication_description' => array( 'totalsType' => '' ),
'eschar' => array( 'totalsType' => '' ),
'discharged_today' => array( 'totalsType' => '' ),
'discharge_date' => array( 'totalsType' => '' ),
'death_in_ward' => array( 'totalsType' => '' ),
'neonatal_death' => array( 'totalsType' => '' ),
'created_at' => array( 'totalsType' => '' ),
'updated_at' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'ward_round_id',
'case_id',
'facility_id',
'admission_date',
'rounding_date',
'data_collector_name',
'ward_name',
'ward_transfer',
'postop_day',
'dressing_not_removed',
'wound_clean_and_healthy',
'stitches_removed_or_wound_opened',
'wound_opened_spontaneously',
'pus_draining',
'abscess_present',
'redness_around_wound',
'bleeding',
'new_dressing',
'new_dressing_type',
'fever',
'on_antibiotics',
'antibiotics_prescribed',
'ssi_diagnosed_on_reoperation',
'returned_to_or',
'return_or_procedure',
'disposition',
'planned_reoperation',
'other_complications',
'endometritis',
'urinary_tract_infection',
'pneumonia',
'other_complication_description',
'eschar',
'discharged_today',
'discharge_date',
'death_in_ward',
'neonatal_death',
'created_at',
'updated_at' ),
'exportFields' => array( 'ward_round_id',
'case_id',
'facility_id',
'admission_date',
'rounding_date',
'data_collector_name',
'ward_name',
'ward_transfer',
'postop_day',
'dressing_not_removed',
'wound_clean_and_healthy',
'stitches_removed_or_wound_opened',
'wound_opened_spontaneously',
'pus_draining',
'abscess_present',
'redness_around_wound',
'bleeding',
'new_dressing',
'new_dressing_type',
'fever',
'on_antibiotics',
'antibiotics_prescribed',
'ssi_diagnosed_on_reoperation',
'returned_to_or',
'return_or_procedure',
'disposition',
'planned_reoperation',
'other_complications',
'endometritis',
'urinary_tract_infection',
'pneumonia',
'other_complication_description',
'eschar',
'discharged_today',
'discharge_date',
'death_in_ward',
'neonatal_death',
'created_at',
'updated_at' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'ward_round_id' => array( 'export_field' ),
'case_id' => array( 'export_field1' ),
'facility_id' => array( 'export_field2' ),
'admission_date' => array( 'export_field3' ),
'rounding_date' => array( 'export_field4' ),
'data_collector_name' => array( 'export_field5' ),
'ward_name' => array( 'export_field6' ),
'ward_transfer' => array( 'export_field7' ),
'postop_day' => array( 'export_field8' ),
'dressing_not_removed' => array( 'export_field9' ),
'wound_clean_and_healthy' => array( 'export_field10' ),
'stitches_removed_or_wound_opened' => array( 'export_field11' ),
'wound_opened_spontaneously' => array( 'export_field12' ),
'pus_draining' => array( 'export_field13' ),
'abscess_present' => array( 'export_field14' ),
'redness_around_wound' => array( 'export_field15' ),
'bleeding' => array( 'export_field16' ),
'new_dressing' => array( 'export_field17' ),
'new_dressing_type' => array( 'export_field18' ),
'fever' => array( 'export_field19' ),
'on_antibiotics' => array( 'export_field20' ),
'antibiotics_prescribed' => array( 'export_field21' ),
'ssi_diagnosed_on_reoperation' => array( 'export_field22' ),
'returned_to_or' => array( 'export_field23' ),
'return_or_procedure' => array( 'export_field24' ),
'disposition' => array( 'export_field25' ),
'planned_reoperation' => array( 'export_field26' ),
'other_complications' => array( 'export_field27' ),
'endometritis' => array( 'export_field28' ),
'urinary_tract_infection' => array( 'export_field29' ),
'pneumonia' => array( 'export_field30' ),
'other_complication_description' => array( 'export_field31' ),
'eschar' => array( 'export_field32' ),
'discharged_today' => array( 'export_field33' ),
'discharge_date' => array( 'export_field34' ),
'death_in_ward' => array( 'export_field35' ),
'neonatal_death' => array( 'export_field36' ),
'created_at' => array( 'export_field37' ),
'updated_at' => array( 'export_field38' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_field31' => 'grid',
'export_field32' => 'grid',
'export_field33' => 'grid',
'export_field34' => 'grid',
'export_field35' => 'grid',
'export_field36' => 'grid',
'export_field37' => 'grid',
'export_field38' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'ward_round_id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'case_id',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'facility_id',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'admission_date',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'rounding_date',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'data_collector_name',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'ward_name',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'ward_transfer',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'postop_day',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'dressing_not_removed',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'wound_clean_and_healthy',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'stitches_removed_or_wound_opened',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'wound_opened_spontaneously',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'pus_draining',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'abscess_present',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'redness_around_wound',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'bleeding',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'new_dressing',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'new_dressing_type',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'fever',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'on_antibiotics',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'antibiotics_prescribed',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'ssi_diagnosed_on_reoperation',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'returned_to_or',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'return_or_procedure',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'disposition',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'planned_reoperation',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'other_complications',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'endometritis',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'urinary_tract_infection',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'pneumonia',
'type' => 'export_field' ),
'export_field31' => array( 'field' => 'other_complication_description',
'type' => 'export_field' ),
'export_field32' => array( 'field' => 'eschar',
'type' => 'export_field' ),
'export_field33' => array( 'field' => 'discharged_today',
'type' => 'export_field' ),
'export_field34' => array( 'field' => 'discharge_date',
'type' => 'export_field' ),
'export_field35' => array( 'field' => 'death_in_ward',
'type' => 'export_field' ),
'export_field36' => array( 'field' => 'neonatal_death',
'type' => 'export_field' ),
'export_field37' => array( 'field' => 'created_at',
'type' => 'export_field' ),
'export_field38' => array( 'field' => 'updated_at',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>